import type { MorphologyRoot } from '@/lib/capabilities'

// GENERATED by scripts/propose-morphology-roots.ts — affix ber-, home L11.
// Roots = taught learning_items whose ber--derived form kaikki attests as "ber-+root"
// (ADR 0020). Re-run additive (--regenerate to rebuild). Curation overrides live in the script config.

const CAT_0 = "BER- + basiswoord uit vijf woordklassen"
const CAT_1 = "Plaatsing van BER- — algemene regel en uitzonderingen"

export const morphologyRoots: MorphologyRoot[] = [
  // ── BER- + basiswoord uit vijf woordklassen ──
  { root: 'aku', affix: 'ber-', illustratesCategory: CAT_0 }, // beraku
  { root: 'dua', affix: 'ber-', illustratesCategory: CAT_0 }, // berdua
  { root: 'jalan', affix: 'ber-', illustratesCategory: CAT_0 }, // berjalan
  { root: 'sama', affix: 'ber-', illustratesCategory: CAT_0 }, // bersama
  { root: 'harga', affix: 'ber-', illustratesCategory: CAT_0 }, // berharga
  { root: 'main', affix: 'ber-', illustratesCategory: CAT_0 }, // bermain
  { root: 'malam', affix: 'ber-', illustratesCategory: CAT_0 }, // bermalam
  { root: 'layar', affix: 'ber-', illustratesCategory: CAT_0 }, // berlayar
  { root: 'kumpul', affix: 'ber-', illustratesCategory: CAT_0 }, // berkumpul
  { root: 'angkat', affix: 'ber-', illustratesCategory: CAT_0 }, // berangkat
  { root: 'nama', affix: 'ber-', illustratesCategory: CAT_0 }, // bernama
  { root: 'susah', affix: 'ber-', illustratesCategory: CAT_0 }, // bersusah
  { root: 'ada', affix: 'ber-', illustratesCategory: CAT_0 }, // berada
  { root: 'kata', affix: 'ber-', illustratesCategory: CAT_0 }, // berkata
  { root: 'laku', affix: 'ber-', illustratesCategory: CAT_0 }, // berlaku
  { root: 'satu', affix: 'ber-', illustratesCategory: CAT_0 }, // bersatu
  { root: 'diri', affix: 'ber-', illustratesCategory: CAT_0 }, // berdiri
  { root: 'salah', affix: 'ber-', illustratesCategory: CAT_0 }, // bersalah
  { root: 'akhir', affix: 'ber-', illustratesCategory: CAT_0 }, // berakhir
  { root: 'anak', affix: 'ber-', illustratesCategory: CAT_0 }, // beranak
  { root: 'buah', affix: 'ber-', illustratesCategory: CAT_0 }, // berbuah
  { root: 'temu', affix: 'ber-', illustratesCategory: CAT_0 }, // bertemu
  // ── Plaatsing van BER- — algemene regel en uitzonderingen ──
  { root: 'kerja', affix: 'ber-', illustratesCategory: CAT_1 }, // bekerja
  { root: 'ajar', affix: 'ber-', illustratesCategory: CAT_1 }, // belajar
]
