import type { MorphologyRoot } from '@/lib/capabilities'

// GENERATED by scripts/propose-morphology-roots.ts — affix reduplication, home L22 (ADR 0020).
// Roots = taught learning_items whose reduplication form kaikki attests (not a loanword). Re-run additive.
// Entries for other affixes in this lesson are preserved verbatim below.

const CAT_0 = "3. Verdubbeling van het bijvoeglijk naamwoord — versterking"
const CAT_1 = "2. Verdubbeling van het zelfstandig naamwoord — meervoud mét diversiteit"
const CAT_2 = "1. Verdubbeling van het werkwoord"

export const morphologyRoots: MorphologyRoot[] = [
  // ── 3. Verdubbeling van het bijvoeglijk naamwoord — versterking ──
  { root: 'banyak', affix: 'reduplication', illustratesCategory: CAT_0 }, // banyak-banyak
  // ── 2. Verdubbeling van het zelfstandig naamwoord — meervoud mét diversiteit ──
  { root: 'orang', affix: 'reduplication', illustratesCategory: CAT_1 }, // orang-orang
  { root: 'kata', affix: 'reduplication', illustratesCategory: CAT_1 }, // kata-kata
  { root: 'hari', affix: 'reduplication', illustratesCategory: CAT_1 }, // hari-hari
  { root: 'rumah', affix: 'reduplication', illustratesCategory: CAT_1 }, // rumah-rumah
  { root: 'anak', affix: 'reduplication', illustratesCategory: CAT_1 }, // anak-anak
  { root: 'jenis', affix: 'reduplication', illustratesCategory: CAT_1 }, // jenis-jenis
  { root: 'arah', affix: 'reduplication', illustratesCategory: CAT_1 }, // arah-arah
  { root: 'kota', affix: 'reduplication', illustratesCategory: CAT_1 }, // kota-kota
  // ── 1. Verdubbeling van het werkwoord ──
  { root: 'jalan', affix: 'reduplication', illustratesCategory: CAT_2 }, // jalan-jalan
  { root: 'lihat', affix: 'reduplication', illustratesCategory: CAT_2 }, // lihat-lihat
  { root: 'mau', affix: 'reduplication', illustratesCategory: CAT_2 }, // mau-mau
  { root: 'bangun', affix: 'reduplication', illustratesCategory: CAT_2 }, // bangun-bangun
  { root: 'minta', affix: 'reduplication', illustratesCategory: CAT_2 }, // minta-minta
  { root: 'makan', affix: 'reduplication', illustratesCategory: CAT_2 }, // makan-makan
  { root: 'bawa', affix: 'reduplication', illustratesCategory: CAT_2 }, // bawa-bawa
  { root: 'duduk', affix: 'reduplication', illustratesCategory: CAT_2 }, // duduk-duduk
  { root: 'baca', affix: 'reduplication', illustratesCategory: CAT_2 }, // baca-baca
  { root: 'dengar', affix: 'reduplication', illustratesCategory: CAT_2 }, // dengar-dengar
  { root: 'tidur', affix: 'reduplication', illustratesCategory: CAT_2 }, // tidur-tidur
  { root: 'minum', affix: 'reduplication', illustratesCategory: CAT_2 }, // minum-minum
  { root: 'mandi', affix: 'reduplication', illustratesCategory: CAT_2 }, // mandi-mandi
  // ── preserved: other affixes taught in this lesson ──
  { root: 'sayur', affix: 'reduplication-an', illustratesCategory: "Verdubbeling van het zelfstandig naamwoord plus -AN" }, // sayur-sayuran
  { root: 'buah', affix: 'reduplication-an', illustratesCategory: "Verdubbeling van het zelfstandig naamwoord plus -AN" }, // buah-buahan
  { root: 'biru', affix: 'ke-…-an-reduplication', illustratesCategory: "Kleurnuances — muda/tua, vruchtvergelijkingen en de ke-...-an \"-achtig\" verdubbeling" }, // kebiru-biruan
  { root: 'hitam', affix: 'ke-…-an-reduplication', illustratesCategory: "Kleurnuances — muda/tua, vruchtvergelijkingen en de ke-...-an \"-achtig\" verdubbeling" }, // kehitam-hitaman
  { root: 'kuning', affix: 'ke-…-an-reduplication', illustratesCategory: "Kleurnuances — muda/tua, vruchtvergelijkingen en de ke-...-an \"-achtig\" verdubbeling" }, // kekuning-kuningan
  { root: 'hijau', affix: 'ke-…-an-reduplication', illustratesCategory: "Kleurnuances — muda/tua, vruchtvergelijkingen en de ke-...-an \"-achtig\" verdubbeling" }, // kehijau-hijauan
  { root: 'putih', affix: 'ke-…-an-reduplication', illustratesCategory: "Kleurnuances — muda/tua, vruchtvergelijkingen en de ke-...-an \"-achtig\" verdubbeling" }, // keputih-putihan
]
