// Generated by generate-staging-files.ts
export const lessonPageBlocks = [
  {
    "block_key": "lesson-3-hero",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "hero",
    "display_order": 0,
    "payload_json": {
      "title": "Les 3 - Di Bandar Udara (Op het vliegveld)",
      "level": "A1"
    },
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-0",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 100,
    "payload_json": {
      "type": "dialogue",
      "lines": [
        {
          "text": "Pak! Di mana barang saya?",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Di sana, Bu.",
          "speaker": "Pekerja"
        },
        {
          "text": "Di sebelah kiri atau kanan?",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Kanan, Bu.",
          "speaker": "Pekerja"
        },
        {
          "text": "O, barang saya berat sekali. Ada dua koper dan satu tas besar. Pak, pengangkut barang, di mana, ya Pak?",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Di sana, Bu.",
          "speaker": "Pekerja"
        },
        {
          "text": "Terima kasih banyak, Pak.",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Terima kasih kembali, Bu.",
          "speaker": "Pekerja"
        },
        {
          "text": "Barang ini harus ke mana, Bu?",
          "speaker": "Pengangkut"
        },
        {
          "text": "Ke pabean saja, Pak.",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Ibu mau menginap di mana di kota?",
          "speaker": "Pengangkut"
        },
        {
          "text": "Belum tahu, Pak. Saya menginap dulu di rumah teman. Besok saya mau cari hotel.",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Nah, di sini pabean. Ini barang Ibu.",
          "speaker": "Pengangkut"
        },
        {
          "text": "Terima kasih, Pak.",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Selamat siang, Bu, silakan buka koper.",
          "speaker": "Pabean"
        },
        {
          "text": "Minta tolong, Pak, koper saya berat sekali, penuh pakaian dan oleh-oleh untuk teman.",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Oleh-oleh apa, Bu?",
          "speaker": "Pabean"
        },
        {
          "text": "O, coklat dan keju. Di sini tidak ada 'kan?",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Ya, benar. Silakan, Bu. Saya sudah selesai.",
          "speaker": "Pabean"
        },
        {
          "text": "Pak, di mana ada taksi, ya Pak?",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Di depan, Bu, di sebelah pintu keluar.",
          "speaker": "Pabean"
        },
        {
          "text": "Terima kasih, Pak.",
          "speaker": "Ibu Yulia"
        },
        {
          "text": "Sama-sama, Bu.",
          "speaker": "Pabean"
        }
      ],
      "closing": "Ibu jalan keluar, lalu naik taksi ke Jakarta.",
      "title": "Di Bandar Udara \"Soekarno-Hatta\" (dialoog)"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-1",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 200,
    "payload_json": {
      "type": "vocabulary",
      "items": [
        {
          "dutch": "is, zijn",
          "indonesian": "ada"
        },
        {
          "dutch": "haven",
          "indonesian": "bandar"
        },
        {
          "dutch": "luchthaven",
          "indonesian": "bandar udara"
        },
        {
          "dutch": "veel",
          "indonesian": "banyak"
        },
        {
          "dutch": "spullen, bagage",
          "indonesian": "barang"
        },
        {
          "dutch": "echt, waar",
          "indonesian": "benar"
        },
        {
          "dutch": "morgen",
          "notes": "besok",
          "indonesian": "besok"
        },
        {
          "dutch": "open(en)",
          "indonesian": "buka"
        },
        {
          "dutch": "bus",
          "indonesian": "bus/bis"
        },
        {
          "dutch": "zoeken",
          "indonesian": "cari"
        },
        {
          "dutch": "chocolade",
          "indonesian": "coklat"
        },
        {
          "dutch": "voorbeeld",
          "indonesian": "contoh"
        },
        {
          "dutch": "voorzijde",
          "indonesian": "depan"
        },
        {
          "dutch": "voor (plaatsbep.)",
          "indonesian": "di depan"
        },
        {
          "dutch": "aan de (zij)kant",
          "indonesian": "di sebelah"
        },
        {
          "dutch": "hier",
          "indonesian": "di sini"
        },
        {
          "dutch": "zitten",
          "indonesian": "duduk"
        },
        {
          "dutch": "moeten",
          "indonesian": "harus"
        },
        {
          "dutch": "is 't niet?",
          "indonesian": "'kan?"
        },
        {
          "dutch": "rechts",
          "indonesian": "kanan"
        },
        {
          "dutch": "kaas",
          "notes": "keju",
          "indonesian": "keju"
        },
        {
          "dutch": "naar buiten gaan",
          "indonesian": "keluar"
        },
        {
          "dutch": "terugkeren, terug",
          "indonesian": "kembali"
        },
        {
          "dutch": "waarheen?",
          "indonesian": "ke mana?"
        },
        {
          "dutch": "koffer",
          "indonesian": "koper"
        },
        {
          "dutch": "stad",
          "indonesian": "kota"
        },
        {
          "dutch": "vervolgens",
          "indonesian": "lalu"
        },
        {
          "dutch": "veld",
          "indonesian": "lapangan"
        },
        {
          "dutch": "honger",
          "indonesian": "lapar"
        },
        {
          "dutch": "zee",
          "indonesian": "laut"
        },
        {
          "dutch": "welk, welke?",
          "indonesian": "mana?"
        },
        {
          "dutch": "vragen om iets, verzoeken",
          "indonesian": "minta"
        },
        {
          "dutch": "auto",
          "indonesian": "mobil"
        },
        {
          "dutch": "cadeautje, souvenir",
          "notes": "oleh-oleh",
          "indonesian": "oleh-oleh"
        },
        {
          "dutch": "douane",
          "notes": "pabean",
          "indonesian": "pabean"
        },
        {
          "dutch": "kleding",
          "indonesian": "pakaian"
        },
        {
          "dutch": "kruier",
          "indonesian": "pengangkut"
        },
        {
          "dutch": "slechts, alleen maar",
          "indonesian": "saja"
        },
        {
          "dutch": "oceaan",
          "indonesian": "samudera"
        },
        {
          "dutch": "zijkant, naast",
          "indonesian": "sebelah"
        },
        {
          "dutch": "zeer, erg, heel",
          "indonesian": "sekali"
        },
        {
          "dutch": "klaar, gereed, afgelopen",
          "indonesian": "selesai"
        },
        {
          "dutch": "fiets",
          "notes": "sepeda",
          "indonesian": "sepeda"
        },
        {
          "dutch": "alstublieft, gaat uw gang",
          "indonesian": "silakan"
        },
        {
          "dutch": "weten",
          "indonesian": "tahu"
        },
        {
          "dutch": "vliegen",
          "indonesian": "terbang"
        },
        {
          "dutch": "helpen",
          "indonesian": "tolong"
        },
        {
          "dutch": "lucht, luchtruim",
          "indonesian": "udara"
        }
      ],
      "title": "Woordenlijst"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-2",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 300,
    "payload_json": {
      "type": "expressions",
      "items": [
        {
          "dutch": "vliegveld",
          "indonesian": "bandar udara / lapangan terbang"
        },
        {
          "dutch": "kunt u me helpen?; hulp vragen",
          "indonesian": "Minta tolong"
        },
        {
          "dutch": "met de fiets/bus/auto gaan",
          "indonesian": "naik sepeda/bus/mobil"
        },
        {
          "dutch": "uitgang",
          "indonesian": "pintu keluar"
        },
        {
          "dutch": "geen dank, van hetzelfde",
          "indonesian": "sama-sama"
        },
        {
          "dutch": "geen dank, graag gedaan",
          "indonesian": "terima kasih kembali"
        }
      ],
      "title": "Uitdrukkingen"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-3",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 400,
    "payload_json": {
      "type": "numbers",
      "items": [
        {
          "dutch": "10",
          "indonesian": "sepuluh"
        },
        {
          "dutch": "20",
          "indonesian": "dua puluh"
        },
        {
          "dutch": "21",
          "indonesian": "dua puluh satu"
        },
        {
          "dutch": "30",
          "indonesian": "tiga puluh"
        },
        {
          "dutch": "32",
          "indonesian": "tiga puluh dua"
        },
        {
          "dutch": "40",
          "indonesian": "empat puluh"
        },
        {
          "dutch": "50",
          "indonesian": "lima puluh"
        },
        {
          "dutch": "60",
          "indonesian": "enam puluh"
        },
        {
          "dutch": "70",
          "indonesian": "tujuh puluh"
        },
        {
          "dutch": "80",
          "indonesian": "delapan puluh"
        },
        {
          "dutch": "90",
          "indonesian": "sembilan puluh"
        },
        {
          "dutch": "100",
          "indonesian": "seratus"
        }
      ],
      "title": "Telwoorden"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-4-pattern-woorden-van-plaats-dari-di-ke",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 510,
    "payload_json": {
      "type": "grammar",
      "title": "Woorden van plaats: dari, di, ke",
      "categories": [
        {
          "rules": [
            "dari -- van, vanuit, vandaan (beweging van)",
            "di -- in, te, op (rust)",
            "ke -- naar (beweging ergens naar toe)",
            "Vergelijk: Saya dari Bali. Sekarang tinggal di Solo. Besok saya pulang ke Jakarta.",
            "Di, dari en ke worden altijd gebruikt in een plaatsbepaling en niet overdrachtelijk.",
            "'Ik kom van huis' -> Saya dari rumah (correct)",
            "'Het huis is van mij' -> NIET Rumah dari saya (fout)"
          ],
          "title": "Woorden van plaats: dari, di, ke"
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-4-pattern-gecombineerde-plaatsbepalingen",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 511,
    "payload_json": {
      "type": "grammar",
      "title": "Gecombineerde plaatsbepalingen",
      "categories": [
        {
          "table": [
            {
              "word": "atas",
              "dutch": "op, bovenkant",
              "combinations": [
                "dari atas -- van boven",
                "di atas -- boven (op)",
                "ke atas -- naar boven"
              ]
            },
            {
              "word": "bawah",
              "dutch": "onder, onderkant",
              "combinations": [
                "dari bawah -- van beneden",
                "di bawah -- onder (zijn)",
                "ke bawah -- naar beneden"
              ]
            },
            {
              "word": "belakang",
              "dutch": "achter, achterkant",
              "combinations": [
                "dari belakang -- van achter",
                "di belakang -- achter",
                "ke belakang -- naar achter"
              ]
            },
            {
              "word": "depan / muka",
              "dutch": "voor, voorkant",
              "combinations": [
                "dari depan -- van voor",
                "di depan -- voor",
                "ke depan -- naar voren"
              ]
            },
            {
              "word": "dalam",
              "dutch": "in",
              "combinations": []
            },
            {
              "word": "luar",
              "dutch": "buiten",
              "combinations": []
            },
            {
              "word": "tengah",
              "dutch": "midden",
              "combinations": []
            },
            {
              "word": "kiri",
              "dutch": "links",
              "combinations": [
                "dari kiri -- van links",
                "di kiri -- aan de linkerkant",
                "ke kiri -- naar links"
              ]
            },
            {
              "word": "kanan",
              "dutch": "rechts",
              "combinations": [
                "dari kanan -- van rechts",
                "di kanan -- aan de rechterkant",
                "ke kanan -- naar rechts"
              ]
            },
            {
              "word": "sini",
              "dutch": "hier",
              "combinations": [
                "dari sini -- van hier",
                "di sini -- hier (zijn)",
                "ke sini -- naar hier"
              ]
            },
            {
              "word": "situ",
              "dutch": "daar",
              "combinations": []
            },
            {
              "word": "sana",
              "dutch": "ginds, daar",
              "combinations": []
            }
          ],
          "title": "Gecombineerde plaatsbepalingen"
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-5-grammar-intro",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 600,
    "payload_json": {
      "type": "grammar",
      "title": "Grammatica: Vraagwoorden",
      "intro": "Vraagwoorden in het Indonesisch:"
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-5-pattern-vraagwoorden",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 610,
    "payload_json": {
      "type": "grammar",
      "title": "Vraagwoorden",
      "categories": [
        {
          "table": [
            {
              "asks": "Wat (is)? ding, zaak, kwestie",
              "word": "Apa?",
              "example": "Apa itu?"
            },
            {
              "asks": "Hoeveel? getal",
              "word": "Berapa?",
              "example": "Nomor berapa?"
            },
            {
              "asks": "Hoe? (op welke) wijze",
              "word": "Bagaimana?",
              "example": "Bagaimana ini?"
            },
            {
              "asks": "Waar vandaan? (van welke) plaats",
              "word": "Dari mana?",
              "example": "Bapak dari mana?"
            },
            {
              "asks": "Waar (is het)? (op welke) plaats",
              "word": "Di mana?",
              "example": "Di mana coklat itu?"
            },
            {
              "asks": "Wanneer? tijd, tijdstip",
              "word": "Kapan?",
              "example": "Kapan Ibu mau datang?"
            },
            {
              "asks": "Waarheen? (naar welke) plaats",
              "word": "Ke mana?",
              "example": "Ibu mau ke mana?"
            },
            {
              "asks": "Waarom? (welke) aktiviteit",
              "word": "Mengapa?",
              "example": "Mengapa Dewi pulang?"
            },
            {
              "asks": "Waarom? oorzaak",
              "word": "Kenapa?",
              "example": "Kenapa Bapak belum ada?"
            },
            {
              "asks": "Wie? Van wie? persoon",
              "word": "Siapa?",
              "example": "Siapa Ibu itu? Nama Bapak siapa?"
            },
            {
              "asks": "Welk(e)? ding, zaak",
              "word": "Yang mana?",
              "example": "Rumah yang mana?"
            }
          ],
          "title": "Vraagwoorden"
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-6-grammar-intro",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 700,
    "payload_json": {
      "type": "grammar",
      "title": "Grammatica: Sekali",
      "intro": "sekali = 'erg, zeer, heel' -- komt achter het bijvoeglijk naamwoord."
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-6-pattern-sekali",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 710,
    "payload_json": {
      "type": "grammar",
      "title": "Sekali",
      "categories": [
        {
          "rules": [
            "Hotel itu mahal sekali -- Dat hotel is erg duur",
            "Sepeda ini bagus sekali -- Deze fiets is erg mooi"
          ],
          "title": "Sekali"
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-7-grammar-intro",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 800,
    "payload_json": {
      "type": "grammar",
      "title": "Grammatica: Ada",
      "intro": "Ada is een werkwoord dat 'er is' of 'er zijn' ('zich bevinden') betekent. Ada is geen koppelwerkwoord."
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-section-7-pattern-gebruik-van-ada",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 810,
    "payload_json": {
      "type": "grammar",
      "title": "Gebruik van ada",
      "categories": [
        {
          "rules": [
            "Di sana ada banyak mobil -- Er zijn daar veel auto's",
            "Ada keju? - Ya, ada -- Is er kaas? - Ja, dat is er",
            "Ada berapa sepeda? -- Hoeveel fietsen zijn er?",
            "In het Nederlands maakt men dikwijls gebruik van de koppelwerkwoorden 'zijn' en 'hebben'. Het Indonesisch kent deze koppelwerkwoorden niet.",
            "Dit huis is mooi -> Rumah ini bagus (NIET: ada bagus)",
            "Ik heb honger -> Saya lapar (NIET: saya ada lapar)",
            "Opmerking: Adalah = is, zijn. Het Nederlandse koppelwerkwoord kan worden vertaald met adalah, maar dit wordt slechts toegepast in officieel taalgebruik."
          ],
          "title": "Gebruik van ada"
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-3-cloze",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [
      "item-sepuluh",
      "item-dua-puluh",
      "item-contoh",
      "item-kan",
      "item-coklat",
      "item-buka"
    ],
    "block_kind": "section",
    "display_order": 1000,
    "payload_json": {
      "type": "reading",
      "title": "cloze",
      "items": [
        {
          "indonesian": "sepuluh",
          "dutch": "10"
        },
        {
          "indonesian": "dua puluh",
          "dutch": "twintig"
        },
        {
          "indonesian": "contoh",
          "dutch": "voorbeeld"
        },
        {
          "indonesian": "'kan?",
          "dutch": "nietwaar?, toch?"
        },
        {
          "indonesian": "coklat",
          "dutch": "bruin"
        },
        {
          "indonesian": "buka",
          "dutch": "openen"
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/sepuluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sepuluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sepuluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepuluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/dua-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/dua-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/contoh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/contoh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/contoh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/contoh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/coklat:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/coklat:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/coklat:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/coklat:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/buka:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/buka:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/buka:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/buka:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-3-lesson-snippet",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [
      "item-naik-bus",
      "item-enam-puluh",
      "item-delapan-puluh",
      "item-ke-mana",
      "item-lah",
      "item-mana",
      "item-naik-mobil",
      "item-tiga-puluh",
      "item-tujuh-puluh",
      "item-sembilan-puluh",
      "item-empat-puluh",
      "item-silakan",
      "item-lima-puluh",
      "item-naik-sepeda"
    ],
    "block_kind": "section",
    "display_order": 1010,
    "payload_json": {
      "type": "reading",
      "title": "lesson snippet",
      "items": [
        {
          "indonesian": "naik bus",
          "dutch": "met de bus gaan"
        },
        {
          "indonesian": "enam puluh",
          "dutch": "zestig"
        },
        {
          "indonesian": "delapan puluh",
          "dutch": "tachtig"
        },
        {
          "indonesian": "ke mana?",
          "dutch": "waarheen?"
        },
        {
          "indonesian": "lah",
          "dutch": "vervolgens"
        },
        {
          "indonesian": "mana?",
          "dutch": "welk/welke?"
        },
        {
          "indonesian": "naik mobil",
          "dutch": "met de auto gaan"
        },
        {
          "indonesian": "tiga puluh",
          "dutch": "dertig"
        },
        {
          "indonesian": "tujuh puluh",
          "dutch": "zeventig"
        },
        {
          "indonesian": "sembilan puluh",
          "dutch": "negentig"
        },
        {
          "indonesian": "empat puluh",
          "dutch": "veertig"
        },
        {
          "indonesian": "silakan",
          "dutch": "alstublieft/gaat uw gang"
        },
        {
          "indonesian": "lima puluh",
          "dutch": "vijftig"
        },
        {
          "indonesian": "naik sepeda",
          "dutch": "met de fiets gaan"
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/naik-bus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/naik-bus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/naik-bus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-bus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enam-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/enam-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/enam-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enam-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/delapan-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/delapan-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/delapan-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/delapan-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ke-mana:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ke-mana:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ke-mana:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ke-mana:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mana:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mana:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mana:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mana:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-mobil:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/naik-mobil:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/naik-mobil:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-mobil:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tiga-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tiga-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tiga-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tiga-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tujuh-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tujuh-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tujuh-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tujuh-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sembilan-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sembilan-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sembilan-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sembilan-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/empat-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/empat-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/empat-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/empat-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/silakan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/silakan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/silakan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/silakan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lima-puluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lima-puluh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lima-puluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lima-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-sepeda:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/naik-sepeda:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/naik-sepeda:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-sepeda:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-3-vocabulary-list",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [
      "item-keluar",
      "item-barang",
      "item-bus",
      "item-depan",
      "item-di-sebelah",
      "item-duduk",
      "item-kota",
      "item-lapangan",
      "item-laut",
      "item-minta",
      "item-pakaian",
      "item-minta-tolong",
      "item-terima-kasih-kembali",
      "item-udara",
      "item-bandar",
      "item-ada",
      "item-cari",
      "item-di-depan",
      "item-harus",
      "item-kembali",
      "item-koper",
      "item-mobil",
      "item-pabean",
      "item-pengangkut",
      "item-samudera",
      "item-sekali",
      "item-selesai",
      "item-sepeda",
      "item-tahu",
      "item-pintu-keluar",
      "item-bandar-udara",
      "item-besok",
      "item-kanan",
      "item-oleh-oleh",
      "item-saja",
      "item-sebelah",
      "item-terbang",
      "item-seratus",
      "item-banyak",
      "item-benar",
      "item-di-sini",
      "item-keju",
      "item-tolong",
      "item-sama-sama",
      "item-lapangan-terbang",
      "item-dua-puluh-satu",
      "item-lalu",
      "item-lapar"
    ],
    "block_kind": "section",
    "display_order": 1020,
    "payload_json": {
      "type": "vocabulary",
      "title": "Woordenschat",
      "items": [
        {
          "indonesian": "keluar",
          "dutch": "naar buiten gaan"
        },
        {
          "indonesian": "barang",
          "dutch": "spullen/bagage"
        },
        {
          "indonesian": "bus",
          "dutch": "bus"
        },
        {
          "indonesian": "depan",
          "dutch": "voorzijde"
        },
        {
          "indonesian": "di sebelah",
          "dutch": "aan de zijkant"
        },
        {
          "indonesian": "duduk",
          "dutch": "zitten"
        },
        {
          "indonesian": "kota",
          "dutch": "stad"
        },
        {
          "indonesian": "lapangan",
          "dutch": "veld"
        },
        {
          "indonesian": "laut",
          "dutch": "zee"
        },
        {
          "indonesian": "minta",
          "dutch": "vragen om iets"
        },
        {
          "indonesian": "pakaian",
          "dutch": "kleding"
        },
        {
          "indonesian": "minta tolong",
          "dutch": "kunt u me helpen?"
        },
        {
          "indonesian": "terima kasih kembali",
          "dutch": "geen dank graag gedaan"
        },
        {
          "indonesian": "udara",
          "dutch": "lucht/luchtruim"
        },
        {
          "indonesian": "bandar",
          "dutch": "haven"
        },
        {
          "indonesian": "ada",
          "dutch": "er is/er zijn"
        },
        {
          "indonesian": "cari",
          "dutch": "zoeken"
        },
        {
          "indonesian": "di depan",
          "dutch": "voor(plaatsbep.)"
        },
        {
          "indonesian": "harus",
          "dutch": "moeten"
        },
        {
          "indonesian": "kembali",
          "dutch": "terugkeren/terug"
        },
        {
          "indonesian": "koper",
          "dutch": "koffer"
        },
        {
          "indonesian": "mobil",
          "dutch": "auto"
        },
        {
          "indonesian": "pabean",
          "dutch": "douane"
        },
        {
          "indonesian": "pengangkut",
          "dutch": "kruier"
        },
        {
          "indonesian": "samudera",
          "dutch": "oceaan"
        },
        {
          "indonesian": "sekali",
          "dutch": "zeer/erg/heel"
        },
        {
          "indonesian": "selesai",
          "dutch": "klaar/gereed/afgelopen"
        },
        {
          "indonesian": "sepeda",
          "dutch": "fiets"
        },
        {
          "indonesian": "tahu",
          "dutch": "weten"
        },
        {
          "indonesian": "pintu keluar",
          "dutch": "uitgang"
        },
        {
          "indonesian": "bandar udara",
          "dutch": "luchthaven"
        },
        {
          "indonesian": "besok",
          "dutch": "morgen"
        },
        {
          "indonesian": "kanan",
          "dutch": "rechts"
        },
        {
          "indonesian": "oleh-oleh",
          "dutch": "cadeautje/souvenir"
        },
        {
          "indonesian": "saja",
          "dutch": "slechts/alleen maar"
        },
        {
          "indonesian": "sebelah",
          "dutch": "zijkant/naast"
        },
        {
          "indonesian": "terbang",
          "dutch": "vliegen"
        },
        {
          "indonesian": "seratus",
          "dutch": "100"
        },
        {
          "indonesian": "banyak",
          "dutch": "veel"
        },
        {
          "indonesian": "benar",
          "dutch": "echt/waar"
        },
        {
          "indonesian": "di sini",
          "dutch": "hier"
        },
        {
          "indonesian": "keju",
          "dutch": "kaas"
        },
        {
          "indonesian": "tolong",
          "dutch": "helpen"
        },
        {
          "indonesian": "sama-sama",
          "dutch": "geen dank"
        },
        {
          "indonesian": "lapangan terbang",
          "dutch": "vliegveld"
        },
        {
          "indonesian": "dua puluh satu",
          "dutch": "eenentwintig"
        },
        {
          "indonesian": "lalu",
          "dutch": "vervolgens"
        },
        {
          "indonesian": "lapar",
          "dutch": "honger"
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/keluar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/keluar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/keluar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/keluar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/barang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/barang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/barang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/barang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/depan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/depan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/depan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/depan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-sebelah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-sebelah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-sebelah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-sebelah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/duduk:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/duduk:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/duduk:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/duduk:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kota:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kota:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kota:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kota:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapangan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lapangan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lapangan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapangan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/laut:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/laut:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/laut:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/laut:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/minta:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/minta:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/minta:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/minta:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pakaian:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pakaian:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pakaian:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pakaian:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/minta-tolong:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/minta-tolong:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/minta-tolong:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/minta-tolong:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima-kasih-kembali:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terima-kasih-kembali:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terima-kasih-kembali:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima-kasih-kembali:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/udara:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/udara:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/udara:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/udara:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bandar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bandar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bandar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bandar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ada:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ada:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ada:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ada:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/cari:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/cari:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/cari:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/cari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-depan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-depan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-depan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-depan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/harus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/harus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kembali:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kembali:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kembali:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kembali:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/koper:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/koper:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/koper:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/koper:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mobil:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mobil:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mobil:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mobil:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pabean:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pabean:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pabean:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pabean:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pengangkut:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pengangkut:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pengangkut:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pengangkut:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/samudera:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/samudera:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/samudera:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/samudera:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sekali:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sekali:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sekali:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sekali:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selesai:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/selesai:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/selesai:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selesai:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepeda:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sepeda:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sepeda:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepeda:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tahu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tahu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tahu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tahu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pintu-keluar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pintu-keluar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pintu-keluar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pintu-keluar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bandar-udara:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bandar-udara:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bandar-udara:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bandar-udara:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besok:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/besok:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/besok:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besok:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kanan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kanan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kanan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kanan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/oleh-oleh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/oleh-oleh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/oleh-oleh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/oleh-oleh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/saja:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/saja:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/saja:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/saja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sebelah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sebelah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sebelah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sebelah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terbang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terbang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terbang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terbang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/seratus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/seratus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/seratus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/seratus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/banyak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/banyak:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/banyak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/banyak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/benar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/benar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/benar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/benar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-sini:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-sini:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-sini:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-sini:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/keju:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/keju:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/keju:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/keju:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tolong:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tolong:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tolong:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tolong:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sama-sama:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sama-sama:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sama-sama:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sama-sama:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapangan-terbang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lapangan-terbang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lapangan-terbang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapangan-terbang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua-puluh-satu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/dua-puluh-satu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/dua-puluh-satu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua-puluh-satu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lalu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lalu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lalu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lalu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lapar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lapar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapar:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-3-practice-bridge",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "practice_bridge",
    "display_order": 9000,
    "payload_json": {
      "label": "Oefen deze les"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ada:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bandar-udara:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bandar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/banyak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/barang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/benar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besok:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/buka:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/cari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/coklat:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/contoh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/delapan-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/depan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-depan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-sebelah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-sini:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua-puluh-satu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/duduk:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/empat-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enam-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kanan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ke-mana:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/keju:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/keluar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kembali:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/koper:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kota:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lalu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapangan-terbang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapangan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lapar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/laut:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lima-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mana:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/minta-tolong:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/minta:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mobil:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-bus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-mobil:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/naik-sepeda:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/oleh-oleh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pabean:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pakaian:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pengangkut:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pintu-keluar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/saja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sama-sama:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/samudera:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sebelah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sekali:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selesai:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sembilan-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepeda:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepuluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/seratus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/silakan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tahu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terbang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima-kasih-kembali:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tiga-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tolong:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tujuh-puluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/udara:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-3-recap",
    "source_ref": "lesson-3",
    "source_refs": [
      "lesson-3"
    ],
    "content_unit_slugs": [],
    "block_kind": "recap",
    "display_order": 9999,
    "payload_json": {
      "title": "Samenvatting"
    },
    "source_progress_event": "lesson_completed",
    "capability_key_refs": []
  }
]
