import type { MorphologyRoot } from '@/lib/capabilities'

// GENERATED by scripts/propose-morphology-roots.ts — affix se-, home L2 (ADR 0020).
// Roots = taught learning_items whose se- form kaikki attests (not a loanword). Re-run additive.

const CAT_0 = "Classificeerwoorden"

export const morphologyRoots: MorphologyRoot[] = [
  // ── Classificeerwoorden ──
  { root: 'orang', affix: 'se-', illustratesCategory: CAT_0 }, // seorang
  { root: 'buah', affix: 'se-', illustratesCategory: CAT_0 }, // sebuah
  { root: 'tiap', affix: 'se-', illustratesCategory: CAT_0 }, // setiap
  { root: 'lama', affix: 'se-', illustratesCategory: CAT_0 }, // selama
  { root: 'cara', affix: 'se-', illustratesCategory: CAT_0 }, // secara
  { root: 'panjang', affix: 'se-', illustratesCategory: CAT_0 }, // sepanjang
  { root: 'macam', affix: 'se-', illustratesCategory: CAT_0 }, // semacam
  { root: 'lain', affix: 'se-', illustratesCategory: CAT_0 }, // selain
  { root: 'malam', affix: 'se-', illustratesCategory: CAT_0 }, // semalam
  { root: 'puluh', affix: 'se-', illustratesCategory: CAT_0 }, // sepuluh
  { root: 'minggu', affix: 'se-', illustratesCategory: CAT_0 }, // seminggu
  { root: 'tahun', affix: 'se-', illustratesCategory: CAT_0 }, // setahun
  { root: 'bulan', affix: 'se-', illustratesCategory: CAT_0 }, // sebulan
  { root: 'besar', affix: 'se-', illustratesCategory: CAT_0 }, // sebesar
  { root: 'ratus', affix: 'se-', illustratesCategory: CAT_0 }, // seratus
  { root: 'mi', affix: 'se-', illustratesCategory: CAT_0 }, // semi
  { root: 'ribu', affix: 'se-', illustratesCategory: CAT_0 }, // seribu
  { root: 'saat', affix: 'se-', illustratesCategory: CAT_0 }, // sesaat
  { root: 'jumlah', affix: 'se-', illustratesCategory: CAT_0 }, // sejumlah
  { root: 'baik', affix: 'se-', illustratesCategory: CAT_0 }, // sebaik
  { root: 'tempat', affix: 'se-', illustratesCategory: CAT_0 }, // setempat
  { root: 'waktu', affix: 'se-', illustratesCategory: CAT_0 }, // sewaktu
]
