import type { TranscriptSegment, PodcastAttribution } from '@/services/textService'

export interface PodcastData {
  title: string
  description: string | null
  level: string
  /** NULL for a read-only text (no narration — the Read face only, ADR 0023). */
  duration_seconds: number | null
  /** Local file name for upload (e.g. "lesson-1.mp3"); NULL for a read-only text. */
  audio_filename: string | null
  transcript_dutch: string | null
  transcript_indonesian: string | null
  transcript_english: string | null
  // Sentence-aligned transcript for read-along (ADR 0022). Optional: the legacy
  // story rows predate it. The transcript_* full-text above is these joined.
  transcript_segments?: TranscriptSegment[] | null
  // CC attribution for openly-licensed source episodes; null for LLM-original.
  attribution?: PodcastAttribution | null
}

// The hand-seeded "Les 1/Les 2" entries were lesson-companion grammar/narration
// audio, removed 2026-06-27 — the podcasts surface is for standalone Story podcasts
// (CONTEXT.md → "Story podcast"), generated by scripts/podcasts/ and seeded directly.
// `seed-podcasts.ts` still reads this array for any hand-authored episodes.
export const podcasts: PodcastData[] = []
