#!/usr/bin/env tsx
/**
 * server.ts
 *
 * Local Express server for the review UI to read/write staging files.
 * Runs on port 3001.
 */

import express from 'express'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const app = express()
const PORT = 3001

app.use(express.json())

// CORS for local Vite dev server
app.use((_req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*')
  res.header('Access-Control-Allow-Headers', 'Content-Type')
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE')
  next()
})

// Helper: Get root directory (parent of tools/review)
function getRepoRoot(): string {
  return path.join(__dirname, '..', '..')
}

// GET /api/lessons — List available lessons
app.get('/api/lessons', (_req, res) => {
  try {
    const stagingDir = path.join(getRepoRoot(), 'scripts', 'data', 'staging')
    if (!fs.existsSync(stagingDir)) {
      return res.json([])
    }

    const lessons = fs
      .readdirSync(stagingDir)
      .filter(f => f.startsWith('lesson-') && fs.statSync(path.join(stagingDir, f)).isDirectory())
      .map(f => parseInt(f.replace('lesson-', ''), 10))
      .filter(n => !isNaN(n))
      .sort((a, b) => a - b)

    res.json(lessons)
  } catch (err) {
    console.error('Error listing lessons:', err)
    res.status(500).json({ error: 'Failed to list lessons' })
  }
})

// GET /api/candidates/:lesson — Load candidates for a lesson
app.get('/api/candidates/:lesson', (req, res) => {
  try {
    const { lesson } = req.params
    const candidatesPath = path.join(
      getRepoRoot(),
      'scripts',
      'data',
      'staging',
      `lesson-${lesson}`,
      'candidates.ts',
    )

    if (!fs.existsSync(candidatesPath)) {
      return res.status(404).json({ error: 'Candidates file not found' })
    }

    const content = fs.readFileSync(candidatesPath, 'utf-8')
    const jsonMatch = content.match(/\[\s*(?:\{[\s\S]*?\}(?:,\s*)?)*\]/)

    if (!jsonMatch) {
      return res.status(400).json({ error: 'Invalid candidates file format' })
    }

    const candidates = JSON.parse(jsonMatch[0])
    res.json(candidates)
  } catch (err) {
    console.error('Error loading candidates:', err)
    res.status(500).json({ error: 'Failed to load candidates' })
  }
})

// POST /api/candidates/:lesson/save — Save candidates with updated review status
app.post('/api/candidates/:lesson/save', (req, res) => {
  try {
    const { lesson } = req.params
    const { candidates } = req.body

    if (!Array.isArray(candidates)) {
      return res.status(400).json({ error: 'Invalid candidates format' })
    }

    const candidatesPath = path.join(
      getRepoRoot(),
      'scripts',
      'data',
      'staging',
      `lesson-${lesson}`,
      'candidates.ts',
    )

    const ts = `// Auto-generated by review UI
// Do not edit manually

import type { GeneratedExerciseCandidate } from '@/types/contentGeneration'

export const candidates: GeneratedExerciseCandidate[] = ${JSON.stringify(candidates, null, 2)}
`

    fs.writeFileSync(candidatesPath, ts)
    res.json({ success: true })
  } catch (err) {
    console.error('Error saving candidates:', err)
    res.status(500).json({ error: 'Failed to save candidates' })
  }
})

// GET /api/pages/:lesson — Load page content for preview
app.get('/api/pages/:lesson', (req, res) => {
  try {
    const { lesson } = req.params
    const pagesPath = path.join(getRepoRoot(), 'scripts', 'data', 'staging', `lesson-${lesson}`, 'pages.ts')

    if (!fs.existsSync(pagesPath)) {
      return res.status(404).json({ error: 'Pages file not found' })
    }

    const content = fs.readFileSync(pagesPath, 'utf-8')
    const jsonMatch = content.match(/\[\s*(?:\{[\s\S]*?\}(?:,\s*)?)*\]/)

    if (!jsonMatch) {
      return res.status(400).json({ error: 'Invalid pages file format' })
    }

    const pages = JSON.parse(jsonMatch[0])
    res.json(pages)
  } catch (err) {
    console.error('Error loading pages:', err)
    res.status(500).json({ error: 'Failed to load pages' })
  }
})

app.listen(PORT, () => {
  console.log(`Review server running on http://localhost:${PORT}`)
  console.log(`Frontend will be at http://localhost:5173`)
})
