// src/pages/Landing.copy.ts — landing-page copy, NL-primary with EN.
//
// Deliberately NOT in src/lib/i18n.ts: that module is entry-chunk-resident,
// and the slice-1 bundle rule is "the app entry chunk must not grow"
// (docs/plans/2026-07-03-desktop-program-design.md §Slice 1). Only Landing.tsx
// imports this file, so the copy ships inside the lazy landing chunk. It
// follows the same nl/en shape and Lang type as i18n.ts.
//
// Copy-honesty rule (owner, 2026-07-03): all audio is TTS — never claim native
// speakers or human narration; audio is mentioned neutrally where it describes
// a real feature, nowhere else.

import type { Lang } from '@/lib/i18n'

const nl = {
  login: 'Inloggen',
  registerCta: 'Gratis beginnen',
  heroEyebrow: 'Les 1 t/m 3 gratis',
  heroTitlePre: 'Leer Indonesisch dat',
  heroTitleEm: 'blijft hangen',
  heroSub: 'Echte lessen met grammatica, dialogen en audio — en een dagelijkse sessie die precies weet wanneer je een woord bijna vergeet, en het dán terugbrengt.',
  heroCta: 'Gratis beginnen',
  heroLogin: 'Al een account? Inloggen →',
  specAria: 'Een woordkaart uit de app: pasar betekent de markt',
  specTag: 'Woordenschat · markt',
  specNr: 'nr. 412',
  specPhon: '/ˈpa.sar/ · zelfstandig naamwoord',
  specGloss: 'de markt',
  specExample: '“Saya pergi ke pasar.”',
  specExampleTr: 'Ik ga naar de markt.',
  specNext: 'Volgende herhaling over 3 dagen',
  bridgeKicker: 'Je kent er al ruim 170',
  bridgeTitle: 'Je spreekt meer Indonesisch dan je denkt.',
  bridgeBody: 'Drie eeuwen gedeelde geschiedenis liet honderden Nederlandse woorden achter in het Indonesisch. Je herkent ze meteen — en dat zijn meteen je eerste woorden.',
  bridgeMore: 'En andersom: pasar, ketjap, tahoe en nasi goreng kwamen mee terug naar het Nederlands.',
  howKicker: 'Zo werkt het',
  howTitle: 'Lezen, oefenen, onthouden — elke dag een beetje.',
  how1Title: 'Lees een les',
  how1Body: 'Grammatica helder uitgelegd, met dialogen uit het echte leven.',
  how2Title: 'Oefen één sessie per dag',
  how2Body: 'De app plant slim: woorden die je bijna vergeet komen terug, wat je al kent blijft weg.',
  how3Title: 'Zie je woordenschat groeien',
  how3Body: 'Volg per woord hoe goed je het kent — van eerste kennismaking tot blijvend gekend.',
  featKicker: 'Wat je krijgt',
  feat1Title: '30 lessen, A1–B1',
  feat1Body: 'Een doorlopende cursus, van eerste woorden tot vlot lezen.',
  feat2Title: 'Podcasts & verhalen',
  feat2Body: 'Luister en lees op jouw niveau, met meelezen per zin.',
  feat3Title: 'Uitspraak & woordbouw',
  feat3Body: 'Train de affixen en klanken — de motor van het Indonesisch.',
  feat4Title: 'Voortgang per woord',
  feat4Body: 'Zie hoeveel je kent van de 1000 meest gebruikte woorden.',
  feat4BarCap: '640 / 1000 gekend',
  pricingEyebrow: 'Abonnement',
  pricingTitle: 'Begin gratis. Ga verder als het klikt.',
  pricingBody: 'Les 1 tot en met 3 en de uitspraakpodcast zijn gratis — geen betaalgegevens nodig. Wil je de hele cursus, dan kost dat €7 per maand of €56 per jaar, inclusief btw. Je kunt op elk moment opzeggen; je houdt toegang tot het einde van de periode die je al betaald hebt.',
  footerMade: 'gemaakt in Nederland',
  footerPrivacy: 'Privacy',
  footerTerms: 'Voorwaarden',
  footerRefunds: 'Restitutie',
}

const en: typeof nl = {
  login: 'Log in',
  registerCta: 'Start free',
  heroEyebrow: 'Lessons 1–3 free',
  heroTitlePre: 'Learn Indonesian that',
  heroTitleEm: 'sticks',
  heroSub: 'Real lessons with grammar, dialogues and audio — and a daily session that knows exactly when you are about to forget a word, and brings it back right then.',
  heroCta: 'Start free',
  heroLogin: 'Already have an account? Log in →',
  specAria: 'A word card from the app: pasar means the market',
  specTag: 'Vocabulary · market',
  specNr: 'no. 412',
  specPhon: '/ˈpa.sar/ · noun',
  specGloss: 'the market',
  specExample: '“Saya pergi ke pasar.”',
  specExampleTr: 'I am going to the market.',
  specNext: 'Next review in 3 days',
  bridgeKicker: 'You already know 170+',
  bridgeTitle: 'You speak more Indonesian than you think.',
  bridgeBody: 'Three centuries of shared history left hundreds of Dutch words behind in Indonesian. You recognise them instantly — and they become your first words.',
  bridgeMore: 'And the other way round: pasar, ketjap, tahoe and nasi goreng travelled back into Dutch.',
  howKicker: 'How it works',
  howTitle: 'Read, practise, remember — a little every day.',
  how1Title: 'Read a lesson',
  how1Body: 'Grammar clearly explained, with dialogues from real life.',
  how2Title: 'Practise one session a day',
  how2Body: 'The app schedules smartly: words you are about to forget come back, what you already know stays away.',
  how3Title: 'Watch your vocabulary grow',
  how3Body: 'Track how well you know each word — from first encounter to lasting knowledge.',
  featKicker: 'What you get',
  feat1Title: '30 lessons, A1–B1',
  feat1Body: 'A continuous course, from your first words to fluent reading.',
  feat2Title: 'Podcasts & stories',
  feat2Body: 'Listen and read at your level, with sentence-by-sentence follow-along.',
  feat3Title: 'Pronunciation & word building',
  feat3Body: 'Train the affixes and sounds — the engine of Indonesian.',
  feat4Title: 'Progress per word',
  feat4Body: 'See how many of the 1000 most common words you know.',
  feat4BarCap: '640 / 1000 known',
  pricingEyebrow: 'Subscription',
  pricingTitle: 'Start free. Continue if it clicks.',
  pricingBody: 'Lessons 1 to 3 and the pronunciation podcast are free — no payment details needed. For the full course it is €7 per month or €56 per year, VAT included. Cancel any time; you keep access until the end of the period you have already paid for.',
  footerMade: 'made in the Netherlands',
  footerPrivacy: 'Privacy',
  footerTerms: 'Terms',
  footerRefunds: 'Refunds',
}

export const landingCopy: Record<Lang, typeof nl> = { nl, en }
