// Generated by generate-staging-files.ts from sections-catalog.json
export const learningItems = [
  {
    "base_text": "Sekarang rapat ini saya mulai. Apakah Anda semua sudah menerima kertas-kertas bersangkutan?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Nu open ik deze vergadering. Hebben jullie allemaal de betreffende papieren al ontvangen?",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Sebenarnya saya belum menerima acara rapat, tetapi mungkin hanya saya yang belum menerimanya?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Eigenlijk heb ik de vergaderagenda nog niet ontvangen, maar misschien ben ik de enige die hem nog niet heeft gekregen?",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Mungkin juga, coba saya tanya dulu kepada sekretaris. Eh, Tri, Tri, mana acara untuk Pak Oka?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Dat zou kunnen, laat me het eerst even aan de secretaresse vragen. Eh, Tri, Tri, waar is de agenda voor meneer Oka?",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Oh, mungkin saya lupa mengirimnya. Maaf Pak, ini dia.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "O, ik ben misschien vergeten hem te versturen. Sorry meneer, hier is hij.",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Ada baiknya saya meringkaskan dulu garis besar persoalan rapat ini. Seperti Anda ketahui, ada beberapa masalah dengan sponsor kita di Jakarta. Katanya uang untuk membangunkan gedung kantor sudah dikirimkannya dari sana. Tetapi sampai saat ini belum kita terima. Kalau uang itu tidak datang pada waktunya, jelas kita tidak mungkin dapat meneruskan pembukaan cabang kantor di Singaraja. Kecuali kalau kita dapat mencari uang dulu, walaupun untuk sementara saja.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Het is beter dat ik eerst de grote lijnen van het probleem van deze vergadering samenvat. Zoals u weet, zijn er enkele problemen met onze sponsor in Jakarta. Naar verluidt is het geld om het kantoorgebouw te bouwen daar al verstuurd. Maar tot op heden hebben wij het nog niet ontvangen. Als dat geld niet op tijd komt, kunnen wij de opening van het filiaal in Singaraja duidelijk niet voortzetten. Behalve als we eerst geld kunnen vinden, al is het maar tijdelijk.",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Menurut saya lebih baik kita kirim faks mengenai pengiriman uang kepada pimpinan kita di Jakarta. Mungkin saja sudah dikirim, namun belum sampai di bank. Itu lebih baik kita tanya dulu ke bank.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Volgens mij kunnen we beter een fax sturen over de overmaking van het geld aan onze leiding in Jakarta. Misschien is het al verstuurd, maar nog niet bij de bank aangekomen. We kunnen het beter eerst bij de bank navragen.",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Gagasan itu baik. Tetapi kalau belum, apa yang dapat kita putuskan? Sudah saya cek pada wakil setempat, dan menurut dia tidak ada yang dapat kita lakukan.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Dat idee is goed. Maar als het nog niet zo is, wat kunnen we dan besluiten? Ik heb het al bij de plaatselijke vertegenwoordiger nagevraagd, en volgens hem is er niets wat we kunnen doen.",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Sebaiknya kita menyusun laporan sebagai bukti. Nanti laporan itu kita kirimkan kepada panitia yayasan, supaya mereka tahu.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "We kunnen het beste een verslag opstellen als bewijs. Dat verslag sturen we straks naar de commissie van de stichting, zodat zij het weten.",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "Jadi, kita putuskan saja menunggu jawaban dari Jakarta. Karena itu rapat ini saya tunda dulu. Besok pagi kita berkumpul lagi di sini.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Dus laten we gewoon besluiten om op het antwoord uit Jakarta te wachten. Daarom verdaag ik deze vergadering voorlopig. Morgenochtend komen we hier weer bijeen.",
    "translation_en": "",
    "source_page": 1,
    "review_status": "pending_review"
  },
  {
    "base_text": "acara",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "programma / agenda",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bangun, mem~kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bouwen / oprichten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "bersangkutan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "betreffende",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "biasa, ~nya",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gewoonlijk",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "buka, pem~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "opening",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bukti",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bewijs",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "cabang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "filiaal",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "faks",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "fax",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gagas, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gedachte / idee",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "garis",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "lijn",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "hadir, meng~i",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "aanwezig zijn / bijwonen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "jelas",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "helder / duidelijk",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "kecuali",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "behalve",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "preposition"
  },
  {
    "base_text": "ketua, mengetuai",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "voorzitter / voorzitten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "laku, me~kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "doen / uitvoeren",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "lapor, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "rapport / verslag",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "panitia",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "commissie / comité",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "pimpin, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "leiding / leider",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "putus, memutuskan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "besluiten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "rapat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vergadering",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "ringkas, me~kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "beknopt / kort / samenvatten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "ruang, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ruimte / vertrek",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "runding, be~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "overleggen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "sekretaris",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "secretaris / secretaresse",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "sementara",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "tijdelijk",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "soal, per~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "probleem",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "sponsor",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "sponsor",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "susun, menyusun",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "samenstellen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "tempat, se~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "plaatselijk",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "tentu, ter~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bepaald(e)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "terus, meneruskan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "voortzetten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "tunda, menunda",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verdagen / uitstellen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "wakil",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vertegenwoordiger",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "yayasan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "stichting / instituut",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "ada baiknya",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "het is beter dat ...",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  }
]
