// Generated by generate-staging-files.ts from sections-catalog.json
export const learningItems = [
  {
    "base_text": "bahwa",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dat",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "conjunction"
  },
  {
    "base_text": "baju",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "blouse",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "banjir",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "overstroming",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bayang, mem-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zich voorstellen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "beri tahu, mem-kan",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "meedelen / berichten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "berkat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dankzij",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "preposition"
  },
  {
    "base_text": "biar (s)aja",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "laat maar",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  },
  {
    "base_text": "buaya",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "krokodil",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "butik",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "boetiek",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "cinta",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "liefde / genegenheid",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "ciut",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "krimpen / gekrompen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "gadis",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "meisje / jonge vrouw",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gara-gara",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "opschudding",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "goblok",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "stommeling",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "harap",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "hopen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "hormat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "eerbied",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "industri",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "industrie",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kabupaten",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "district",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kabur",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verbleekt / wazig",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "keadaan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "toestand / situatie",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kelas",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "klas",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kelihatan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zichtbaar",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "landa, me-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "treffen / raken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "luap, me-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "overstromen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "pinjam, meminjamkan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "uitlenen (aan)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "panik",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "paniek",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "peta",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "plattegrond / kaart",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "pintar",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "knap / intelligent",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "rencana, me-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "plannen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "sederhana",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "eenvoudig",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "sehat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gezond",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "sekeluarga",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "van dezelfde familie",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "senantiasa",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "voortdurend / steeds",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "singkat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kort",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "singkat, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "afkorting",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "tercinta",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "geliefd / dierbaar",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "tertanggal",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gedateerd / de dato",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "tetangga",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "buur / buurman / buurvrouw",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "tulip",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "tulp",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "ucap, meng-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zeggen / uitspreken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  }
]
