// Regenerated by regenerate-all-lesson-page-blocks.ts
export const lessonPageBlocks = [
  {
    "block_key": "lesson-5-hero",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "hero",
    "display_order": 0,
    "payload_json": {
      "title": "Les 5 - Belajar",
      "level": "A1"
    },
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-0",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 100,
    "payload_json": {
      "type": "text",
      "paragraphs": [
        "Het koken van rijst kan op diverse manieren gebeuren. De aanwijzingen op de verpakking voor de behandeling van de betreffende rijst zijn meestal goed. Naast witte gekookte rijst kunt u wellicht eens onderstaande varianten proberen.",
        "Nasi gurih\n\nNasi gurih wordt bereid met santan (het witte sap verkregen door het uitpersen van natte kokospulp). Het krijgt daardoor een volle smaak. Bij de nasi gurih kunt u twee tot drie andere gerechten maken, bijvoorbeeld een 'droog' vleesgerecht, een groentegerecht en eventueel wat kroepoek.",
        "Benodigdheden voor 4 personen:\n– circa 400 gram rijst, – 2 koppen dikke santan, – snufje zout,\n– 2-3 pandanbladeren.",
        "Was de rijst en breng daarna in een pan de rijst aan de kook met een 'vingerkootje' (niet meer dan 2,5 cm) water boven de rijst. Voeg dan toe de santan, een snufje zout en de pandanbladeren en meng ze door de rijst. Zodra het vocht begint te borrelen, zetten we het vuur zacht en gebruiken eventueel een vlamverdeler. Wanneer de rijst na 15 tot 20 minuten droog staat, kan het vuur uit. De rijst is dan half gaar. De rijst wordt vervolgens in een 'stomer' (tweedelige pan) overgebracht en in 15-20 minuten gaar gestoomd.",
        "Nasi kuning\n\nOok nasi kuning wordt met santan bereid. De gele kleur geeft de rijst een feestelijk aanzien. Het gerecht ligt vrij zwaar op de maag en men doet er goed aan een tikje bescheiden te zijn bij het opscheppen.",
        "Benodigdheden voor 4 personen:\n– circa 400 gram rijst, – 2 koppen dikke santan, – snufje zout,\n– 2 mespunten kunyitpoeder (geelwortel = kurkuma), – 2 stukjes verse serehstengels of serehbladeren, – 1 jeruk purutblad en – eventueel een pandanblad.",
        "Was de rijst en stoom hem in een vergiet gedurende 20 minuten (dus niet in het water). Intussen brengen we de santan met wat zout, kunyitpoeder, sereh, jeruk purut en pandanblad aan de kook. Zet het vuur laag en voeg de dampende rijst toe. Even goed doorroeren, het vuur uit doen, deksel op de pan en 5-7 minuten laten staan.",
        "De lauwe, gele rijst overbrengen in een vergiet en nog 20 minuten stomen om hem gaar te laten worden. De nasi kuning overbrengen op een grote schaal en garneren met gebakken uitjes, schijfjes komkommer, kleine stukjes gebakken tempe, reepjes gebakken geklopt ei en lombok (Spaanse pepers)."
      ],
      "title": "Nasi gerechten"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-1",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 200,
    "payload_json": {
      "type": "dialogue",
      "intro": "Hari Rabu Ibu dan bapak pergi ke Taman Mini. Mereka tidak pulang sampai sore. Anaknya, Titin dan Nanang, tidak boleh ikut ke Taman Mini. Mereka harus belajar.",
      "lines": [
        {
          "text": "Ibu dan bapak enak saja ke Taman Mini. Kita harus belajar di rumah. Aku juga mau ke Taman Mini, dan kamu Nanang?",
          "speaker": "Titin",
          "translation": ""
        },
        {
          "text": "Aku tidak senang tinggal di rumah terus. Mari! Kita juga pergi saja, Tin.",
          "speaker": "Nanang",
          "translation": ""
        },
        {
          "text": "Kita harus kerja dulu sebentar. Nanti kita pergi.",
          "speaker": "Titin",
          "translation": ""
        },
        {
          "text": "Ayo, kerja dulu anak-anak!",
          "speaker": "Pembantu",
          "translation": ""
        },
        {
          "text": "Aduh, kami mau ke luar, jalan-jalan dan makan di restoran \"Mi Enak\" tetapi tidak ada uang.",
          "speaker": "Titin",
          "translation": ""
        },
        {
          "text": "Saya juga tidak punya uang. Jadi, tinggal di rumah saja Tin. Besok saja jalan-jalan dengan ayahmu. Mari! Sekarang kerja. Besok harus ke sekolah 'kan?",
          "speaker": "Pembantu",
          "translation": ""
        },
        {
          "text": "Baiklah, tapi boleh minta setrop susu ya?",
          "speaker": "Titin",
          "translation": ""
        }
      ],
      "title": "Dialoog: Belajar"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-2-pattern-ik-saya-aku-en-eigennaam",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 310,
    "payload_json": {
      "type": "grammar",
      "title": "Ik — saya, aku en eigennaam",
      "categories": [
        {
          "rules": [
            "Gebruik saya als neutraal-formele vorm van 'ik' bij kennismakingen en in formele situaties.",
            "Aku is de informele vorm van 'ik', gebruikt in huiselijke kring en tussen vrienden.",
            "Indonesiërs verwijzen vaak naar zichzelf met hun eigen naam in plaats van saya of aku."
          ],
          "title": "Ik — saya, aku en eigennaam",
          "examples": [
            {
              "dutch": "Mijn vriend en ik",
              "indonesian": "Saya dan teman saya"
            },
            {
              "dutch": "Ik wil ook naar Taman Mini (informeel)",
              "indonesian": "Aku juga mau ke Taman Mini"
            },
            {
              "dutch": "Ik (Awan) wil naar de stad (eigennaam als 'ik')",
              "indonesian": "Awan mau ke kota"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-2-pattern-jij-beleefd-via-naam-of-kamu-engkau",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 311,
    "payload_json": {
      "type": "grammar",
      "title": "Jij — beleefd via naam of kamu/engkau",
      "categories": [
        {
          "rules": [
            "De beleefdste manier om 'jij' te zeggen is de eigen naam of voornaam van de ander te gebruiken.",
            "Kamu en engkau zijn informele aanspreekvormen, beperkt tot huiselijke kring en vrienden.",
            "Gebruik nooit kamu tegen een volwassen gast of onbekende — dat wordt als schokken ervaren."
          ],
          "title": "Jij — beleefd via naam of kamu/engkau",
          "examples": [
            {
              "dutch": "Wat wil jij (Awan) in de stad kopen?",
              "indonesian": "Awan mau beli apa di kota?"
            },
            {
              "dutch": "Ga jij (Siti) met de auto naar de markt?",
              "indonesian": "Siti naik mobil ke pasar?"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-2-pattern-u-tuan-nyonya-bapak-ibu-anda-saudara",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 312,
    "payload_json": {
      "type": "grammar",
      "title": "U — Tuan/Nyonya, Bapak/Ibu, Anda, Saudara",
      "categories": [
        {
          "rules": [
            "Formeel: Tuan (meneer) en Nyonya (mevrouw) voor westerlingen en officiele situaties.",
            "Neutraal dagelijks gebruik: Bapak (meneer) en Ibu (mevrouw), ook met naam: Bapak Sahid.",
            "Anda is sexe- en sociaal-neutraal 'u', populair in reclame en formele teksten.",
            "Saudara (vriend/gelijke) voor collega's en gelijken in neutrale situaties."
          ],
          "title": "U — Tuan/Nyonya, Bapak/Ibu, Anda, Saudara",
          "examples": [
            {
              "dutch": "Waar komt u (meneer Sahid) vandaan?",
              "indonesian": "Bapak Sahid dari mana?"
            },
            {
              "dutch": "Houdt u (mevrouw Sutrisno) van thee?",
              "indonesian": "Ibu Sutrisno suka teh?"
            },
            {
              "dutch": "Wat wilt u eten?",
              "indonesian": "Anda ingin makan apa?"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-2-pattern-broers-en-zusters-kakak-adik-abang",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 313,
    "payload_json": {
      "type": "grammar",
      "title": "Broers en zusters — kakak, adik, abang",
      "categories": [
        {
          "rules": [
            "Onderscheid: kakak (oudere broer/zus), adik (jongere broer/zus) — geslacht is secundair.",
            "Abang (informeel: bang) = oudere broer; kakak perempuan = oudere zus.",
            "Deze familietermen worden ook informeel gebruikt voor bekenden en buren."
          ],
          "title": "Broers en zusters — kakak, adik, abang",
          "examples": [
            {
              "dutch": "oudere broer",
              "indonesian": "kakak laki-laki (of: abang)"
            },
            {
              "dutch": "oudere zus",
              "indonesian": "kakak perempuan"
            },
            {
              "dutch": "jongere broer",
              "indonesian": "adik laki-laki"
            },
            {
              "dutch": "jongere zus",
              "indonesian": "adik perempuan"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-2-pattern-hij-zij-dia-ia-beliau",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 314,
    "payload_json": {
      "type": "grammar",
      "title": "Hij/zij — dia, ia, beliau",
      "categories": [
        {
          "rules": [
            "Dia en ia zijn beide correct voor 'hij' en 'zij' — er is geen geslachtsverschil.",
            "Beliau is de respectvolle vorm: wordt gebruikt om over iemand te spreken met ontzag."
          ],
          "title": "Hij/zij — dia, ia, beliau",
          "examples": [
            {
              "dutch": "hij of zij (beide correct)",
              "indonesian": "Dia atau ia"
            },
            {
              "dutch": "Zij is mijn lerares (respectvol)",
              "indonesian": "Beliau adalah guru saya"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-2-pattern-wij-kita-inclusief-versus-kami-exclusief",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 315,
    "payload_json": {
      "type": "grammar",
      "title": "Wij — kita (inclusief) versus kami (exclusief)",
      "categories": [
        {
          "rules": [
            "Kita = 'wij' inclusief de aangesprokene (de persoon tot wie je spreekt telt mee).",
            "Kami = 'wij' exclusief de aangesprokene (de persoon tot wie je spreekt is niet inbegrepen).",
            "Dit onderscheid bestaat niet in het Nederlands — context bepaalt de keuze."
          ],
          "title": "Wij — kita (inclusief) versus kami (exclusief)",
          "examples": [
            {
              "dutch": "Wij moeten thuis studeren (jij ook — Titin tegen Nanang)",
              "indonesian": "Kita harus belajar di rumah"
            },
            {
              "dutch": "Wij willen naar buiten (jij niet — Titin tegen pembantu)",
              "indonesian": "Aduh, kami mau ke luar"
            },
            {
              "dutch": "Ma, wij gaan alvast naar school! (jij gaat niet mee)",
              "indonesian": "Bu, kami ke sekolah dulu ya!"
            },
            {
              "dutch": "Pa, laten wij gaan wandelen (kom mee)",
              "indonesian": "Bapak, mari kita jalan-jalan"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-2-pattern-jullie-u-meervoud-en-zij-meervoud",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 316,
    "payload_json": {
      "type": "grammar",
      "title": "Jullie, U (meervoud) en Zij (meervoud)",
      "categories": [
        {
          "rules": [
            "Kalian = 'jullie' (neutraal meervoud tweede persoon).",
            "U meervoud: Bapak-Bapak / Ibu-Ibu / Saudara-Saudari / Anda (semua).",
            "Zij meervoud: mereka (één woord, geen geslachtsverschil)."
          ],
          "title": "Jullie, U (meervoud) en Zij (meervoud)",
          "examples": [
            {
              "dutch": "Waar gaan jullie naartoe?",
              "indonesian": "Kalian mau ke mana?"
            },
            {
              "dutch": "Dames en heren (formele aanspreekvorm)",
              "indonesian": "Saudara-Saudari yang terhormat"
            },
            {
              "dutch": "Zij hebben een net restaurant",
              "indonesian": "Mereka punya restoran yang rapi"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-3",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 400,
    "payload_json": {
      "type": "reference_table",
      "intro": "Het bezittelijk voornaamwoord wordt achter het zelfstandig naamwoord geplaatst.\n\nBezittelijke voornaamwoorden zijn praktisch gelijk aan de persoonlijke voornaamwoorden, met dien verstande dat voor aku en kamu/engkau respectievelijk de afgekorte vormen -ku en -mu/-kau worden gebruikt. De afgekorte vorm wordt direct aan het woord gekoppeld.\n\nBij de derde persoon enkelvoud (zijn/haar) wordt bij voorkeur -nya gebruikt. Bij de derde persoon meervoud (hun) wordt -nya eveneens dikwijls gebruikt.",
      "columns": [
        "",
        "formeel",
        "neutraal",
        "informeel"
      ],
      "examples": [
        {
          "dutch": "Waar is mijn boek?",
          "indonesian": "Di mana buku saya? / Di mana bukuku?"
        },
        {
          "dutch": "Jouw auto is kapot",
          "indonesian": "Mobilmu rusak"
        },
        {
          "dutch": "Zijn/haar hulpje is ziek",
          "indonesian": "Pembantunya sakit"
        },
        {
          "dutch": "Onze kleding is nog niet droog",
          "indonesian": "Pakaian kami belum kering"
        },
        {
          "dutch": "Ons geld is al op",
          "indonesian": "Uang kita sudah habis"
        },
        {
          "dutch": "Hun huis is erg mooi",
          "indonesian": "Rumah mereka bagus sekali / Rumahnya bagus sekali"
        }
      ],
      "sections": [
        {
          "rows": [
            {
              "cells": [
                "saya eigennaam",
                "saya eigennaam",
                "-ku"
              ],
              "label": "(ik) mijn"
            },
            {
              "cells": [
                "-",
                "(voor)naam van de persoon",
                "-mu (-kau)"
              ],
              "label": "(jij) jouw"
            },
            {
              "cells": [
                "Tuan",
                "Bapak",
                "oom, om"
              ],
              "label": "uw (man)"
            },
            {
              "cells": [
                "Nyonya",
                "Ibu",
                "tante"
              ],
              "label": "uw (vrouw)"
            },
            {
              "cells": [
                "-",
                "Mas, Saudara",
                "kakak, abang"
              ],
              "label": "uw (jongeman)"
            },
            {
              "cells": [
                "-",
                "Nona, Saudari",
                "zus, sus"
              ],
              "label": "uw (jonge vrouw)"
            },
            {
              "cells": [
                "-",
                "Anda, Saudara",
                "-"
              ],
              "label": "uw (sexe-neutraal)"
            },
            {
              "cells": [
                "Beliau",
                "dia, -nya *",
                "-"
              ],
              "label": "(hij) zijn"
            },
            {
              "cells": [
                "Beliau",
                "dia, -nya *",
                "-"
              ],
              "label": "(zij) haar"
            }
          ],
          "heading": "Enkelvoud"
        },
        {
          "rows": [
            {
              "cells": [
                "-",
                "kita (inclusief)",
                "-"
              ],
              "label": "(wij) ons, onze"
            },
            {
              "cells": [
                "-",
                "kami (exclusief)",
                "-"
              ],
              "label": "(wij) ons, onze"
            },
            {
              "cells": [
                "-",
                "kalian",
                "-mu"
              ],
              "label": "(jullie) jullie"
            },
            {
              "cells": [
                "Tuan-Tuan",
                "Bapak-Bapak",
                "-"
              ],
              "label": "uw (heren)"
            },
            {
              "cells": [
                "Nyonya-Nyonya",
                "Ibu-Ibu",
                "-"
              ],
              "label": "uw (dames)"
            },
            {
              "cells": [
                "-",
                "Saudara-Saudara",
                "-"
              ],
              "label": "uw (jongemannen)"
            },
            {
              "cells": [
                "-",
                "Saudari-Saudari",
                "-"
              ],
              "label": "uw (jonge vrouwen)"
            },
            {
              "cells": [
                "-",
                "Saudara-Saudara",
                "-"
              ],
              "label": "uw (sexe-neutraal)"
            },
            {
              "cells": [
                "-",
                "Anda",
                "-"
              ],
              "label": "uw (tegen publiek)"
            },
            {
              "cells": [
                "-",
                "mereka, -nya *",
                "-"
              ],
              "label": "(zij) hun"
            }
          ],
          "heading": "Meervoud"
        }
      ],
      "footnotes": [
        "* In geschreven taal wordt -nya voor de derde persoon enkelvoud en meervoud gebruikt. In gesproken taal wordt, in plaats van -nya, ook wel dia voor de derde persoon enkelvoud en mereka voor de derde persoon meervoud gebruikt."
      ],
      "tableTitle": "Schema bezittelijk voornaamwoord",
      "title": "Bezittelijk voornaamwoord"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-5",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 600,
    "payload_json": {
      "type": "text",
      "paragraphs": [
        "Na de verovering van de belangrijke handelsplaatsen Goa in India in 1510 en Malakka in het huidige Maleisië in 1511, trokken de Portugezen verder in de richting van de Indonesische archipel. In 1522 bereikten zij de in moerasachtig gebied gelegen haven Sunda Kelapa van het Westjavaanse rijk Pajajaran. De Portugezen sloten een overeenkomst met de heerser om er een fort te kunnen bouwen, maar toen ze in 1527 terugkwamen om met de bouw te beginnen, was de havenplaats inmiddels ingelijfd door de sultan van Bantam (West-Java).",
        "De sultan weigerde de Portugezen toestemming om op deze plaats een vesting te bouwen. Tijdens de heerschappij van de sultan van Bantam werd de plaats omgedoopt in Jayakarta dat later werd verbasterd tot Jakatra, waarvan later Jakarta werd afgeleid."
      ],
      "title": "Cultuur: Jakarta"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-section-6",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 700,
    "payload_json": {
      "type": "vocabulary",
      "items": [
        {
          "dutch": "oudere broer",
          "indonesian": "abang"
        },
        {
          "dutch": "jongere broer/zus",
          "indonesian": "adik"
        },
        {
          "dutch": "hemel, goh, jemig (uitroep)",
          "indonesian": "aduh"
        },
        {
          "dutch": "ik (informeel)",
          "indonesian": "aku"
        },
        {
          "dutch": "vader",
          "indonesian": "ayah"
        },
        {
          "dutch": "komaan!",
          "indonesian": "ayo!"
        },
        {
          "dutch": "goed dan (maar)",
          "indonesian": "baiklah"
        },
        {
          "dutch": "leren (zie ook Les 11)",
          "indonesian": "belajar"
        },
        {
          "dutch": "zaailing, jong rijstplantje",
          "indonesian": "bibit padi"
        },
        {
          "dutch": "op z'n gemak, naar believen",
          "indonesian": "enak saja"
        },
        {
          "dutch": "ongepelde rijst (rijst/vliesje)",
          "indonesian": "gabah"
        },
        {
          "dutch": "vol van smaak",
          "indonesian": "gurih"
        },
        {
          "dutch": "op, afgelopen",
          "indonesian": "habis"
        },
        {
          "dutch": "hallo",
          "indonesian": "halo"
        },
        {
          "dutch": "dag",
          "indonesian": "hari"
        },
        {
          "dutch": "woensdag",
          "indonesian": "hari Rabu"
        },
        {
          "dutch": "meegaan, meedoen",
          "indonesian": "ikut"
        },
        {
          "dutch": "dus",
          "indonesian": "jadi"
        },
        {
          "dutch": "een wandeling maken",
          "indonesian": "jalan-jalan"
        },
        {
          "dutch": "oudere broer/zus",
          "indonesian": "kakak"
        },
        {
          "dutch": "wij (exclusief aangesprokene)",
          "indonesian": "kami"
        },
        {
          "dutch": "jij, jullie (informeel)",
          "indonesian": "kamu"
        },
        {
          "dutch": "droog",
          "indonesian": "kering"
        },
        {
          "dutch": "werken",
          "indonesian": "kerja"
        },
        {
          "dutch": "wij (inclusief aangesprokene)",
          "indonesian": "kita"
        },
        {
          "dutch": "rijstveld (droog)",
          "indonesian": "ladang"
        },
        {
          "dutch": "man, mannelijk",
          "indonesian": "laki-laki"
        },
        {
          "dutch": "kom!",
          "indonesian": "mari!"
        },
        {
          "dutch": "zij (meervoud)",
          "indonesian": "mereka"
        },
        {
          "dutch": "bamie, noedels",
          "indonesian": "mi"
        },
        {
          "dutch": "beginnen",
          "indonesian": "mulai"
        },
        {
          "dutch": "straks, zo meteen",
          "indonesian": "nanti"
        },
        {
          "dutch": "rijstgerecht (met kokosmelk)",
          "indonesian": "nasi gurih"
        },
        {
          "dutch": "rijstplant",
          "indonesian": "padi"
        },
        {
          "dutch": "hulp in de huishouding",
          "indonesian": "pembantu"
        },
        {
          "dutch": "vrouw, vrouwelijk",
          "indonesian": "perempuan"
        },
        {
          "dutch": "(weg)gaan",
          "indonesian": "pergi"
        },
        {
          "dutch": "bezitten, hebben",
          "indonesian": "punya"
        },
        {
          "dutch": "kapot, stuk",
          "indonesian": "rusak"
        },
        {
          "dutch": "rijstveld (nat)",
          "indonesian": "sawah"
        },
        {
          "dutch": "een moment(je), even",
          "indonesian": "sebentar"
        },
        {
          "dutch": "zich prettig voelen, blij, leuk",
          "indonesian": "senang"
        },
        {
          "dutch": "siroop",
          "indonesian": "setrop"
        },
        {
          "dutch": "zoet drankje (melk met siroop)",
          "indonesian": "setrop susu"
        },
        {
          "dutch": "namiddag, avond",
          "indonesian": "sore"
        },
        {
          "dutch": "melk",
          "indonesian": "susu"
        },
        {
          "dutch": "park, tuin",
          "indonesian": "taman"
        },
        {
          "dutch": "Klein Indonesie - park met traditionele gebouwen in Jakarta",
          "indonesian": "Taman Mini"
        },
        {
          "dutch": "maar, echter",
          "indonesian": "tapi / tetapi"
        },
        {
          "dutch": "vliegen",
          "indonesian": "terbang"
        },
        {
          "dutch": "voorts, steeds, maar door",
          "indonesian": "terus"
        },
        {
          "dutch": "geld",
          "indonesian": "uang"
        },
        {
          "dutch": "goh! nou! (stopwoord/uitroep)",
          "indonesian": "wah!"
        }
      ],
      "title": "Woordenlijst"
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-cloze",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5",
      "learning_items/terbang"
    ],
    "content_unit_slugs": [
      "item-terbang"
    ],
    "block_kind": "section",
    "display_order": 1000,
    "payload_json": {
      "type": "reading",
      "title": "cloze",
      "items": [
        {
          "indonesian": "terbang",
          "dutch": "vliegen"
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/terbang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terbang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terbang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terbang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-dialogue",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5",
      "learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah",
      "learning_items/aku-tidak-senang-tinggal-di-rumah-terus",
      "learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi",
      "learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang",
      "learning_items/besok-saja-jalan-jalan-dengan-ayahmu",
      "learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya"
    ],
    "content_unit_slugs": [
      "item-ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah",
      "item-aku-tidak-senang-tinggal-di-rumah-terus",
      "item-kita-harus-kerja-dulu-sebentar-nanti-kita-pergi",
      "item-aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang",
      "item-besok-saja-jalan-jalan-dengan-ayahmu",
      "item-baiklah-tapi-boleh-minta-setrop-susu-ya"
    ],
    "block_kind": "section",
    "display_order": 1010,
    "payload_json": {
      "type": "dialogue",
      "title": "Dialoog",
      "items": [
        {
          "indonesian": "Ibu dan bapak enak saja ke Taman Mini. Kita harus belajar di rumah.",
          "dutch": "Moeder en vader gaan zo maar naar Taman Mini. Wij moeten thuis studeren."
        },
        {
          "indonesian": "Aku tidak senang tinggal di rumah terus.",
          "dutch": "Ik vind het niet leuk om steeds thuis te blijven."
        },
        {
          "indonesian": "Kita harus kerja dulu sebentar. Nanti kita pergi.",
          "dutch": "We moeten eerst even werken. Daarna gaan we."
        },
        {
          "indonesian": "Aduh, kami mau ke luar, jalan-jalan dan makan di restoran Mi Enak tetapi tidak ada uang.",
          "dutch": "Ai, wij willen naar buiten, wandelen en eten in restaurant Mi Enak maar er is geen geld."
        },
        {
          "indonesian": "Besok saja jalan-jalan dengan ayahmu.",
          "dutch": "Ga morgen maar wandelen met je vader."
        },
        {
          "indonesian": "Baiklah, tapi boleh minta setrop susu ya?",
          "dutch": "Goed dan, maar mag ik een setrop susu?"
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-example-sentence",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5",
      "learning_items/kita-harus-belajar-di-rumah",
      "learning_items/kami-mau-ke-luar",
      "learning_items/di-mana-bukuku",
      "learning_items/mobilmu-rusak",
      "learning_items/pembantunya-sakit",
      "learning_items/uang-kita-sudah-habis",
      "learning_items/rumahnya-bagus-sekali"
    ],
    "content_unit_slugs": [
      "item-kita-harus-belajar-di-rumah",
      "item-kami-mau-ke-luar",
      "item-di-mana-bukuku",
      "item-mobilmu-rusak",
      "item-pembantunya-sakit",
      "item-uang-kita-sudah-habis",
      "item-rumahnya-bagus-sekali"
    ],
    "block_kind": "section",
    "display_order": 1020,
    "payload_json": {
      "type": "reading",
      "title": "example sentence",
      "items": [
        {
          "indonesian": "Kita harus belajar di rumah.",
          "dutch": "Wij moeten thuis studeren. (inclusief: jij ook)"
        },
        {
          "indonesian": "Kami mau ke luar.",
          "dutch": "Wij willen naar buiten. (exclusief: jij niet)"
        },
        {
          "indonesian": "Di mana bukuku?",
          "dutch": "Waar is mijn boek?"
        },
        {
          "indonesian": "Mobilmu rusak.",
          "dutch": "Jouw auto is kapot."
        },
        {
          "indonesian": "Pembantunya sakit.",
          "dutch": "Zijn/haar hulpje is ziek."
        },
        {
          "indonesian": "Uang kita sudah habis.",
          "dutch": "Ons geld is al op."
        },
        {
          "indonesian": "Rumahnya bagus sekali.",
          "dutch": "Hun huis is erg mooi."
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-vocabulary-list",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5",
      "learning_items/gabah",
      "learning_items/padi",
      "learning_items/abang",
      "learning_items/adik",
      "learning_items/aduh",
      "learning_items/aku",
      "learning_items/ayah",
      "learning_items/ayo",
      "learning_items/baiklah",
      "learning_items/belajar",
      "learning_items/bibit-padi",
      "learning_items/enak-saja",
      "learning_items/gurih",
      "learning_items/habis",
      "learning_items/halo",
      "learning_items/hari",
      "learning_items/hari-rabu",
      "learning_items/ikut",
      "learning_items/jadi",
      "learning_items/jalan-jalan",
      "learning_items/kakak",
      "learning_items/kami",
      "learning_items/kamu",
      "learning_items/kering",
      "learning_items/kerja",
      "learning_items/kita",
      "learning_items/ladang",
      "learning_items/laki-laki",
      "learning_items/mari",
      "learning_items/mereka",
      "learning_items/mi",
      "learning_items/mulai",
      "learning_items/nanti",
      "learning_items/nasi-gurih",
      "learning_items/pembantu",
      "learning_items/perempuan",
      "learning_items/pergi",
      "learning_items/punya",
      "learning_items/rusak",
      "learning_items/sawah",
      "learning_items/sebentar",
      "learning_items/senang",
      "learning_items/setrop",
      "learning_items/setrop-susu",
      "learning_items/sore",
      "learning_items/susu",
      "learning_items/taman",
      "learning_items/taman-mini",
      "learning_items/tapi-tetapi",
      "learning_items/terus",
      "learning_items/uang",
      "learning_items/wah"
    ],
    "content_unit_slugs": [
      "item-gabah",
      "item-padi",
      "item-abang",
      "item-adik",
      "item-aduh",
      "item-aku",
      "item-ayah",
      "item-ayo",
      "item-baiklah",
      "item-belajar",
      "item-bibit-padi",
      "item-enak-saja",
      "item-gurih",
      "item-habis",
      "item-halo",
      "item-hari",
      "item-hari-rabu",
      "item-ikut",
      "item-jadi",
      "item-jalan-jalan",
      "item-kakak",
      "item-kami",
      "item-kamu",
      "item-kering",
      "item-kerja",
      "item-kita",
      "item-ladang",
      "item-laki-laki",
      "item-mari",
      "item-mereka",
      "item-mi",
      "item-mulai",
      "item-nanti",
      "item-nasi-gurih",
      "item-pembantu",
      "item-perempuan",
      "item-pergi",
      "item-punya",
      "item-rusak",
      "item-sawah",
      "item-sebentar",
      "item-senang",
      "item-setrop",
      "item-setrop-susu",
      "item-sore",
      "item-susu",
      "item-taman",
      "item-taman-mini",
      "item-tapi-tetapi",
      "item-terus",
      "item-uang",
      "item-wah"
    ],
    "block_kind": "section",
    "display_order": 1030,
    "payload_json": {
      "type": "vocabulary",
      "title": "Woordenschat",
      "items": [
        {
          "indonesian": "gabah",
          "dutch": "ongepelde rijst (rijst/vliesje)"
        },
        {
          "indonesian": "padi",
          "dutch": "rijstplant"
        },
        {
          "indonesian": "abang",
          "dutch": "oudere broer"
        },
        {
          "indonesian": "adik",
          "dutch": "jongere broer/zus"
        },
        {
          "indonesian": "aduh",
          "dutch": "hemel, goh, jemig (uitroep)"
        },
        {
          "indonesian": "aku",
          "dutch": "ik (informeel)"
        },
        {
          "indonesian": "ayah",
          "dutch": "vader"
        },
        {
          "indonesian": "ayo!",
          "dutch": "komaan!"
        },
        {
          "indonesian": "baiklah",
          "dutch": "goed dan (maar)"
        },
        {
          "indonesian": "belajar",
          "dutch": "leren (zie ook Les 11)"
        },
        {
          "indonesian": "bibit padi",
          "dutch": "zaailing, jong rijstplantje"
        },
        {
          "indonesian": "enak saja",
          "dutch": "op z'n gemak, naar believen"
        },
        {
          "indonesian": "gurih",
          "dutch": "vol van smaak"
        },
        {
          "indonesian": "habis",
          "dutch": "op, afgelopen"
        },
        {
          "indonesian": "halo",
          "dutch": "hallo"
        },
        {
          "indonesian": "hari",
          "dutch": "dag"
        },
        {
          "indonesian": "hari Rabu",
          "dutch": "woensdag"
        },
        {
          "indonesian": "ikut",
          "dutch": "meegaan, meedoen"
        },
        {
          "indonesian": "jadi",
          "dutch": "dus"
        },
        {
          "indonesian": "jalan-jalan",
          "dutch": "een wandeling maken"
        },
        {
          "indonesian": "kakak",
          "dutch": "oudere broer/zus"
        },
        {
          "indonesian": "kami",
          "dutch": "wij (exclusief aangesprokene)"
        },
        {
          "indonesian": "kamu",
          "dutch": "jij, jullie (informeel)"
        },
        {
          "indonesian": "kering",
          "dutch": "droog"
        },
        {
          "indonesian": "kerja",
          "dutch": "werken"
        },
        {
          "indonesian": "kita",
          "dutch": "wij (inclusief aangesprokene)"
        },
        {
          "indonesian": "ladang",
          "dutch": "rijstveld (droog)"
        },
        {
          "indonesian": "laki-laki",
          "dutch": "man, mannelijk"
        },
        {
          "indonesian": "mari!",
          "dutch": "kom!"
        },
        {
          "indonesian": "mereka",
          "dutch": "zij (meervoud)"
        },
        {
          "indonesian": "mi",
          "dutch": "bamie, noedels"
        },
        {
          "indonesian": "mulai",
          "dutch": "beginnen"
        },
        {
          "indonesian": "nanti",
          "dutch": "straks, zo meteen"
        },
        {
          "indonesian": "nasi gurih",
          "dutch": "rijstgerecht (met kokosmelk)"
        },
        {
          "indonesian": "pembantu",
          "dutch": "hulp in de huishouding"
        },
        {
          "indonesian": "perempuan",
          "dutch": "vrouw, vrouwelijk"
        },
        {
          "indonesian": "pergi",
          "dutch": "(weg)gaan"
        },
        {
          "indonesian": "punya",
          "dutch": "bezitten, hebben"
        },
        {
          "indonesian": "rusak",
          "dutch": "kapot, stuk"
        },
        {
          "indonesian": "sawah",
          "dutch": "rijstveld (nat)"
        },
        {
          "indonesian": "sebentar",
          "dutch": "een moment(je), even"
        },
        {
          "indonesian": "senang",
          "dutch": "zich prettig voelen, blij, leuk"
        },
        {
          "indonesian": "setrop",
          "dutch": "siroop"
        },
        {
          "indonesian": "setrop susu",
          "dutch": "zoet drankje (melk met siroop)"
        },
        {
          "indonesian": "sore",
          "dutch": "namiddag, avond"
        },
        {
          "indonesian": "susu",
          "dutch": "melk"
        },
        {
          "indonesian": "taman",
          "dutch": "park, tuin"
        },
        {
          "indonesian": "Taman Mini",
          "dutch": "Klein Indonesie - park met traditionele Indonesische gebouwen in Jakarta"
        },
        {
          "indonesian": "tapi / tetapi",
          "dutch": "maar, echter"
        },
        {
          "indonesian": "terus",
          "dutch": "voorts, steeds, maar door"
        },
        {
          "indonesian": "uang",
          "dutch": "geld"
        },
        {
          "indonesian": "wah!",
          "dutch": "goh! nou! (stopwoord/uitroep)"
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/gabah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gabah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gabah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/gabah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/padi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/padi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/padi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/padi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/abang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/abang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/abang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/abang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/adik:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/adik:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/adik:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/adik:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayo:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayo:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayo:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayo:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/belajar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/belajar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/belajar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/belajar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bibit-padi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bibit-padi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bibit-padi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bibit-padi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enak-saja:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/enak-saja:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/enak-saja:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enak-saja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/gurih:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gurih:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gurih:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/gurih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/habis:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/habis:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/habis:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/habis:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/halo:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/halo:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/halo:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/halo:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari-rabu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari-rabu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari-rabu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari-rabu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ikut:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ikut:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ikut:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ikut:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jadi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jadi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jadi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jadi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kakak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kakak:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kakak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kakak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kamu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kamu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kamu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kamu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kering:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kering:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kering:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kering:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kerja:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kerja:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kerja:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kerja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ladang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ladang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ladang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ladang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/laki-laki:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/laki-laki:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/laki-laki:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/laki-laki:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mari:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mari:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mari:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mereka:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mereka:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mereka:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mereka:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mulai:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mulai:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mulai:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mulai:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nanti:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nanti:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nanti:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nanti:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/perempuan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/perempuan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/perempuan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/perempuan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pergi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pergi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pergi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pergi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/punya:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/punya:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/punya:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/punya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rusak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rusak:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rusak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rusak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sawah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sawah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sawah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sawah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sebentar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sebentar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sebentar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sebentar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/senang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/senang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/senang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/senang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop-susu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop-susu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop-susu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop-susu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sore:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sore:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sore:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sore:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/susu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/susu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/susu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/susu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman-mini:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman-mini:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman-mini:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman-mini:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/wah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/wah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/wah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/wah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-practice-bridge",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "practice_bridge",
    "display_order": 9000,
    "payload_json": {
      "label": "Oefen deze les"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/abang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/adik:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayo:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/belajar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bibit-padi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enak-saja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/gabah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/gurih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/habis:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/halo:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari-rabu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ikut:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jadi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kakak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kamu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kering:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kerja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ladang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/laki-laki:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mereka:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mulai:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nanti:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/padi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/perempuan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pergi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/punya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rusak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sawah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sebentar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/senang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop-susu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sore:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/susu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman-mini:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terbang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terus:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/wah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-recap",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "recap",
    "display_order": 9999,
    "payload_json": {
      "title": "Samenvatting"
    },
    "source_progress_event": "lesson_completed",
    "capability_key_refs": []
  }
]
