// Generated by generate-staging-files.ts
export const lessonPageBlocks = [
  {
    "block_key": "lesson-5-hero",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "hero",
    "display_order": 0,
    "payload_json": {
      "title": "Les 5 - Belajar",
      "level": "A1"
    },
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-item-terbang-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/terbang"
    ],
    "content_unit_slugs": [
      "item-terbang"
    ],
    "block_kind": "exposure",
    "display_order": 100,
    "payload_json": {
      "baseText": "terbang",
      "itemType": "word",
      "translationNl": "vliegen",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/terbang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terbang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terbang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terbang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-terbang-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/terbang"
    ],
    "content_unit_slugs": [
      "item-terbang"
    ],
    "block_kind": "practice_bridge",
    "display_order": 101,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/terbang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-gabah-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/gabah"
    ],
    "content_unit_slugs": [
      "item-gabah"
    ],
    "block_kind": "exposure",
    "display_order": 110,
    "payload_json": {
      "baseText": "gabah",
      "itemType": "word",
      "translationNl": "ongepelde rijst (rijst/vliesje)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/gabah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gabah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gabah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/gabah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-gabah-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/gabah"
    ],
    "content_unit_slugs": [
      "item-gabah"
    ],
    "block_kind": "practice_bridge",
    "display_order": 111,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/gabah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-padi-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/padi"
    ],
    "content_unit_slugs": [
      "item-padi"
    ],
    "block_kind": "exposure",
    "display_order": 120,
    "payload_json": {
      "baseText": "padi",
      "itemType": "word",
      "translationNl": "rijstplant",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/padi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/padi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/padi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/padi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-padi-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/padi"
    ],
    "content_unit_slugs": [
      "item-padi"
    ],
    "block_kind": "practice_bridge",
    "display_order": 121,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/padi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-abang-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/abang"
    ],
    "content_unit_slugs": [
      "item-abang"
    ],
    "block_kind": "exposure",
    "display_order": 130,
    "payload_json": {
      "baseText": "abang",
      "itemType": "word",
      "translationNl": "oudere broer",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/abang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/abang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/abang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/abang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-abang-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/abang"
    ],
    "content_unit_slugs": [
      "item-abang"
    ],
    "block_kind": "practice_bridge",
    "display_order": 131,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/abang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-adik-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/adik"
    ],
    "content_unit_slugs": [
      "item-adik"
    ],
    "block_kind": "exposure",
    "display_order": 140,
    "payload_json": {
      "baseText": "adik",
      "itemType": "word",
      "translationNl": "jongere broer/zus",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/adik:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/adik:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/adik:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/adik:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-adik-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/adik"
    ],
    "content_unit_slugs": [
      "item-adik"
    ],
    "block_kind": "practice_bridge",
    "display_order": 141,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/adik:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aduh-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aduh"
    ],
    "content_unit_slugs": [
      "item-aduh"
    ],
    "block_kind": "exposure",
    "display_order": 150,
    "payload_json": {
      "baseText": "aduh",
      "itemType": "word",
      "translationNl": "hemel, goh, jemig (uitroep)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aduh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aduh-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aduh"
    ],
    "content_unit_slugs": [
      "item-aduh"
    ],
    "block_kind": "practice_bridge",
    "display_order": 151,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aduh:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aku-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aku"
    ],
    "content_unit_slugs": [
      "item-aku"
    ],
    "block_kind": "exposure",
    "display_order": 160,
    "payload_json": {
      "baseText": "aku",
      "itemType": "word",
      "translationNl": "ik (informeel)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aku:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aku-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aku"
    ],
    "content_unit_slugs": [
      "item-aku"
    ],
    "block_kind": "practice_bridge",
    "display_order": 161,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aku:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ayah-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ayah"
    ],
    "content_unit_slugs": [
      "item-ayah"
    ],
    "block_kind": "exposure",
    "display_order": 170,
    "payload_json": {
      "baseText": "ayah",
      "itemType": "word",
      "translationNl": "vader",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ayah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ayah-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ayah"
    ],
    "content_unit_slugs": [
      "item-ayah"
    ],
    "block_kind": "practice_bridge",
    "display_order": 171,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ayah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ayo-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ayo"
    ],
    "content_unit_slugs": [
      "item-ayo"
    ],
    "block_kind": "exposure",
    "display_order": 180,
    "payload_json": {
      "baseText": "ayo!",
      "itemType": "word",
      "translationNl": "komaan!",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ayo:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayo:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ayo:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ayo:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ayo-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ayo"
    ],
    "content_unit_slugs": [
      "item-ayo"
    ],
    "block_kind": "practice_bridge",
    "display_order": 181,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ayo:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-baiklah-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/baiklah"
    ],
    "content_unit_slugs": [
      "item-baiklah"
    ],
    "block_kind": "exposure",
    "display_order": 190,
    "payload_json": {
      "baseText": "baiklah",
      "itemType": "word",
      "translationNl": "goed dan (maar)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/baiklah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-baiklah-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/baiklah"
    ],
    "content_unit_slugs": [
      "item-baiklah"
    ],
    "block_kind": "practice_bridge",
    "display_order": 191,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/baiklah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-belajar-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/belajar"
    ],
    "content_unit_slugs": [
      "item-belajar"
    ],
    "block_kind": "exposure",
    "display_order": 200,
    "payload_json": {
      "baseText": "belajar",
      "itemType": "word",
      "translationNl": "leren (zie ook Les 11)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/belajar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/belajar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/belajar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/belajar:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-belajar-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/belajar"
    ],
    "content_unit_slugs": [
      "item-belajar"
    ],
    "block_kind": "practice_bridge",
    "display_order": 201,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/belajar:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-bibit-padi-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/bibit-padi"
    ],
    "content_unit_slugs": [
      "item-bibit-padi"
    ],
    "block_kind": "exposure",
    "display_order": 210,
    "payload_json": {
      "baseText": "bibit padi",
      "itemType": "word",
      "translationNl": "zaailing, jong rijstplantje",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/bibit-padi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bibit-padi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bibit-padi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bibit-padi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-bibit-padi-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/bibit-padi"
    ],
    "content_unit_slugs": [
      "item-bibit-padi"
    ],
    "block_kind": "practice_bridge",
    "display_order": 211,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/bibit-padi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-enak-saja-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/enak-saja"
    ],
    "content_unit_slugs": [
      "item-enak-saja"
    ],
    "block_kind": "exposure",
    "display_order": 220,
    "payload_json": {
      "baseText": "enak saja",
      "itemType": "word",
      "translationNl": "op z'n gemak, naar believen",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/enak-saja:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/enak-saja:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/enak-saja:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enak-saja:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-enak-saja-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/enak-saja"
    ],
    "content_unit_slugs": [
      "item-enak-saja"
    ],
    "block_kind": "practice_bridge",
    "display_order": 221,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/enak-saja:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-gurih-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/gurih"
    ],
    "content_unit_slugs": [
      "item-gurih"
    ],
    "block_kind": "exposure",
    "display_order": 230,
    "payload_json": {
      "baseText": "gurih",
      "itemType": "word",
      "translationNl": "vol van smaak",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/gurih:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gurih:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/gurih:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/gurih:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-gurih-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/gurih"
    ],
    "content_unit_slugs": [
      "item-gurih"
    ],
    "block_kind": "practice_bridge",
    "display_order": 231,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/gurih:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-habis-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/habis"
    ],
    "content_unit_slugs": [
      "item-habis"
    ],
    "block_kind": "exposure",
    "display_order": 240,
    "payload_json": {
      "baseText": "habis",
      "itemType": "word",
      "translationNl": "op, afgelopen",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/habis:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/habis:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/habis:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/habis:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-habis-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/habis"
    ],
    "content_unit_slugs": [
      "item-habis"
    ],
    "block_kind": "practice_bridge",
    "display_order": 241,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/habis:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-halo-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/halo"
    ],
    "content_unit_slugs": [
      "item-halo"
    ],
    "block_kind": "exposure",
    "display_order": 250,
    "payload_json": {
      "baseText": "halo",
      "itemType": "word",
      "translationNl": "hallo",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/halo:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/halo:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/halo:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/halo:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-halo-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/halo"
    ],
    "content_unit_slugs": [
      "item-halo"
    ],
    "block_kind": "practice_bridge",
    "display_order": 251,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/halo:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-hari-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/hari"
    ],
    "content_unit_slugs": [
      "item-hari"
    ],
    "block_kind": "exposure",
    "display_order": 260,
    "payload_json": {
      "baseText": "hari",
      "itemType": "word",
      "translationNl": "dag",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/hari:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-hari-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/hari"
    ],
    "content_unit_slugs": [
      "item-hari"
    ],
    "block_kind": "practice_bridge",
    "display_order": 261,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/hari:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-hari-rabu-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/hari-rabu"
    ],
    "content_unit_slugs": [
      "item-hari-rabu"
    ],
    "block_kind": "exposure",
    "display_order": 270,
    "payload_json": {
      "baseText": "hari Rabu",
      "itemType": "word",
      "translationNl": "woensdag",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/hari-rabu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari-rabu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hari-rabu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hari-rabu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-hari-rabu-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/hari-rabu"
    ],
    "content_unit_slugs": [
      "item-hari-rabu"
    ],
    "block_kind": "practice_bridge",
    "display_order": 271,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/hari-rabu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ikut-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ikut"
    ],
    "content_unit_slugs": [
      "item-ikut"
    ],
    "block_kind": "exposure",
    "display_order": 280,
    "payload_json": {
      "baseText": "ikut",
      "itemType": "word",
      "translationNl": "meegaan, meedoen",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ikut:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ikut:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ikut:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ikut:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ikut-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ikut"
    ],
    "content_unit_slugs": [
      "item-ikut"
    ],
    "block_kind": "practice_bridge",
    "display_order": 281,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ikut:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-jadi-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/jadi"
    ],
    "content_unit_slugs": [
      "item-jadi"
    ],
    "block_kind": "exposure",
    "display_order": 290,
    "payload_json": {
      "baseText": "jadi",
      "itemType": "word",
      "translationNl": "dus",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/jadi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jadi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jadi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jadi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-jadi-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/jadi"
    ],
    "content_unit_slugs": [
      "item-jadi"
    ],
    "block_kind": "practice_bridge",
    "display_order": 291,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/jadi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-jalan-jalan-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/jalan-jalan"
    ],
    "content_unit_slugs": [
      "item-jalan-jalan"
    ],
    "block_kind": "exposure",
    "display_order": 300,
    "payload_json": {
      "baseText": "jalan-jalan",
      "itemType": "word",
      "translationNl": "een wandeling maken",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/jalan-jalan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/jalan-jalan:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-jalan-jalan-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/jalan-jalan"
    ],
    "content_unit_slugs": [
      "item-jalan-jalan"
    ],
    "block_kind": "practice_bridge",
    "display_order": 301,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/jalan-jalan:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kakak-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kakak"
    ],
    "content_unit_slugs": [
      "item-kakak"
    ],
    "block_kind": "exposure",
    "display_order": 310,
    "payload_json": {
      "baseText": "kakak",
      "itemType": "word",
      "translationNl": "oudere broer/zus",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kakak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kakak:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kakak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kakak:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kakak-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kakak"
    ],
    "content_unit_slugs": [
      "item-kakak"
    ],
    "block_kind": "practice_bridge",
    "display_order": 311,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kakak:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kami-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kami"
    ],
    "content_unit_slugs": [
      "item-kami"
    ],
    "block_kind": "exposure",
    "display_order": 320,
    "payload_json": {
      "baseText": "kami",
      "itemType": "word",
      "translationNl": "wij (exclusief aangesprokene)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kami:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kami-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kami"
    ],
    "content_unit_slugs": [
      "item-kami"
    ],
    "block_kind": "practice_bridge",
    "display_order": 321,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kami:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kamu-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kamu"
    ],
    "content_unit_slugs": [
      "item-kamu"
    ],
    "block_kind": "exposure",
    "display_order": 330,
    "payload_json": {
      "baseText": "kamu",
      "itemType": "word",
      "translationNl": "jij, jullie (informeel)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kamu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kamu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kamu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kamu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kamu-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kamu"
    ],
    "content_unit_slugs": [
      "item-kamu"
    ],
    "block_kind": "practice_bridge",
    "display_order": 331,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kamu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kering-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kering"
    ],
    "content_unit_slugs": [
      "item-kering"
    ],
    "block_kind": "exposure",
    "display_order": 340,
    "payload_json": {
      "baseText": "kering",
      "itemType": "word",
      "translationNl": "droog",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kering:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kering:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kering:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kering:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kering-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kering"
    ],
    "content_unit_slugs": [
      "item-kering"
    ],
    "block_kind": "practice_bridge",
    "display_order": 341,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kering:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kerja-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kerja"
    ],
    "content_unit_slugs": [
      "item-kerja"
    ],
    "block_kind": "exposure",
    "display_order": 350,
    "payload_json": {
      "baseText": "kerja",
      "itemType": "word",
      "translationNl": "werken",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kerja:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kerja:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kerja:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kerja:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kerja-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kerja"
    ],
    "content_unit_slugs": [
      "item-kerja"
    ],
    "block_kind": "practice_bridge",
    "display_order": 351,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kerja:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kita-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kita"
    ],
    "content_unit_slugs": [
      "item-kita"
    ],
    "block_kind": "exposure",
    "display_order": 360,
    "payload_json": {
      "baseText": "kita",
      "itemType": "word",
      "translationNl": "wij (inclusief aangesprokene)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kita:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kita-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kita"
    ],
    "content_unit_slugs": [
      "item-kita"
    ],
    "block_kind": "practice_bridge",
    "display_order": 361,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kita:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ladang-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ladang"
    ],
    "content_unit_slugs": [
      "item-ladang"
    ],
    "block_kind": "exposure",
    "display_order": 370,
    "payload_json": {
      "baseText": "ladang",
      "itemType": "word",
      "translationNl": "rijstveld (droog)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ladang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ladang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ladang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ladang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ladang-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ladang"
    ],
    "content_unit_slugs": [
      "item-ladang"
    ],
    "block_kind": "practice_bridge",
    "display_order": 371,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ladang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-laki-laki-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/laki-laki"
    ],
    "content_unit_slugs": [
      "item-laki-laki"
    ],
    "block_kind": "exposure",
    "display_order": 380,
    "payload_json": {
      "baseText": "laki-laki",
      "itemType": "word",
      "translationNl": "man, mannelijk",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/laki-laki:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/laki-laki:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/laki-laki:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/laki-laki:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-laki-laki-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/laki-laki"
    ],
    "content_unit_slugs": [
      "item-laki-laki"
    ],
    "block_kind": "practice_bridge",
    "display_order": 381,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/laki-laki:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mari-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mari"
    ],
    "content_unit_slugs": [
      "item-mari"
    ],
    "block_kind": "exposure",
    "display_order": 390,
    "payload_json": {
      "baseText": "mari!",
      "itemType": "word",
      "translationNl": "kom!",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mari:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mari:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mari:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mari:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mari-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mari"
    ],
    "content_unit_slugs": [
      "item-mari"
    ],
    "block_kind": "practice_bridge",
    "display_order": 391,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mari:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mereka-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mereka"
    ],
    "content_unit_slugs": [
      "item-mereka"
    ],
    "block_kind": "exposure",
    "display_order": 400,
    "payload_json": {
      "baseText": "mereka",
      "itemType": "word",
      "translationNl": "zij (meervoud)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mereka:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mereka:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mereka:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mereka:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mereka-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mereka"
    ],
    "content_unit_slugs": [
      "item-mereka"
    ],
    "block_kind": "practice_bridge",
    "display_order": 401,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mereka:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mi-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mi"
    ],
    "content_unit_slugs": [
      "item-mi"
    ],
    "block_kind": "exposure",
    "display_order": 410,
    "payload_json": {
      "baseText": "mi",
      "itemType": "word",
      "translationNl": "bamie, noedels",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mi-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mi"
    ],
    "content_unit_slugs": [
      "item-mi"
    ],
    "block_kind": "practice_bridge",
    "display_order": 411,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mulai-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mulai"
    ],
    "content_unit_slugs": [
      "item-mulai"
    ],
    "block_kind": "exposure",
    "display_order": 420,
    "payload_json": {
      "baseText": "mulai",
      "itemType": "word",
      "translationNl": "beginnen",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mulai:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mulai:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mulai:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mulai:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mulai-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mulai"
    ],
    "content_unit_slugs": [
      "item-mulai"
    ],
    "block_kind": "practice_bridge",
    "display_order": 421,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mulai:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-nanti-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/nanti"
    ],
    "content_unit_slugs": [
      "item-nanti"
    ],
    "block_kind": "exposure",
    "display_order": 430,
    "payload_json": {
      "baseText": "nanti",
      "itemType": "word",
      "translationNl": "straks, zo meteen",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/nanti:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nanti:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nanti:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nanti:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-nanti-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/nanti"
    ],
    "content_unit_slugs": [
      "item-nanti"
    ],
    "block_kind": "practice_bridge",
    "display_order": 431,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/nanti:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-nasi-gurih-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/nasi-gurih"
    ],
    "content_unit_slugs": [
      "item-nasi-gurih"
    ],
    "block_kind": "exposure",
    "display_order": 440,
    "payload_json": {
      "baseText": "nasi gurih",
      "itemType": "word",
      "translationNl": "rijstgerecht (met kokosmelk)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/nasi-gurih:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nasi-gurih:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-nasi-gurih-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/nasi-gurih"
    ],
    "content_unit_slugs": [
      "item-nasi-gurih"
    ],
    "block_kind": "practice_bridge",
    "display_order": 441,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/nasi-gurih:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-pembantu-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/pembantu"
    ],
    "content_unit_slugs": [
      "item-pembantu"
    ],
    "block_kind": "exposure",
    "display_order": 450,
    "payload_json": {
      "baseText": "pembantu",
      "itemType": "word",
      "translationNl": "hulp in de huishouding",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/pembantu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-pembantu-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/pembantu"
    ],
    "content_unit_slugs": [
      "item-pembantu"
    ],
    "block_kind": "practice_bridge",
    "display_order": 451,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/pembantu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-perempuan-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/perempuan"
    ],
    "content_unit_slugs": [
      "item-perempuan"
    ],
    "block_kind": "exposure",
    "display_order": 460,
    "payload_json": {
      "baseText": "perempuan",
      "itemType": "word",
      "translationNl": "vrouw, vrouwelijk",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/perempuan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/perempuan:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/perempuan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/perempuan:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-perempuan-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/perempuan"
    ],
    "content_unit_slugs": [
      "item-perempuan"
    ],
    "block_kind": "practice_bridge",
    "display_order": 461,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/perempuan:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-pergi-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/pergi"
    ],
    "content_unit_slugs": [
      "item-pergi"
    ],
    "block_kind": "exposure",
    "display_order": 470,
    "payload_json": {
      "baseText": "pergi",
      "itemType": "word",
      "translationNl": "(weg)gaan",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/pergi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pergi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pergi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pergi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-pergi-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/pergi"
    ],
    "content_unit_slugs": [
      "item-pergi"
    ],
    "block_kind": "practice_bridge",
    "display_order": 471,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/pergi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-punya-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/punya"
    ],
    "content_unit_slugs": [
      "item-punya"
    ],
    "block_kind": "exposure",
    "display_order": 480,
    "payload_json": {
      "baseText": "punya",
      "itemType": "word",
      "translationNl": "bezitten, hebben",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/punya:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/punya:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/punya:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/punya:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-punya-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/punya"
    ],
    "content_unit_slugs": [
      "item-punya"
    ],
    "block_kind": "practice_bridge",
    "display_order": 481,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/punya:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-rusak-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/rusak"
    ],
    "content_unit_slugs": [
      "item-rusak"
    ],
    "block_kind": "exposure",
    "display_order": 490,
    "payload_json": {
      "baseText": "rusak",
      "itemType": "word",
      "translationNl": "kapot, stuk",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/rusak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rusak:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rusak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rusak:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-rusak-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/rusak"
    ],
    "content_unit_slugs": [
      "item-rusak"
    ],
    "block_kind": "practice_bridge",
    "display_order": 491,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/rusak:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-sawah-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/sawah"
    ],
    "content_unit_slugs": [
      "item-sawah"
    ],
    "block_kind": "exposure",
    "display_order": 500,
    "payload_json": {
      "baseText": "sawah",
      "itemType": "word",
      "translationNl": "rijstveld (nat)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/sawah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sawah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sawah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sawah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-sawah-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/sawah"
    ],
    "content_unit_slugs": [
      "item-sawah"
    ],
    "block_kind": "practice_bridge",
    "display_order": 501,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/sawah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-sebentar-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/sebentar"
    ],
    "content_unit_slugs": [
      "item-sebentar"
    ],
    "block_kind": "exposure",
    "display_order": 510,
    "payload_json": {
      "baseText": "sebentar",
      "itemType": "word",
      "translationNl": "een moment(je), even",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/sebentar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sebentar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sebentar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sebentar:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-sebentar-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/sebentar"
    ],
    "content_unit_slugs": [
      "item-sebentar"
    ],
    "block_kind": "practice_bridge",
    "display_order": 511,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/sebentar:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-senang-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/senang"
    ],
    "content_unit_slugs": [
      "item-senang"
    ],
    "block_kind": "exposure",
    "display_order": 520,
    "payload_json": {
      "baseText": "senang",
      "itemType": "word",
      "translationNl": "zich prettig voelen, blij, leuk",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/senang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/senang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/senang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/senang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-senang-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/senang"
    ],
    "content_unit_slugs": [
      "item-senang"
    ],
    "block_kind": "practice_bridge",
    "display_order": 521,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/senang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-setrop-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/setrop"
    ],
    "content_unit_slugs": [
      "item-setrop"
    ],
    "block_kind": "exposure",
    "display_order": 530,
    "payload_json": {
      "baseText": "setrop",
      "itemType": "word",
      "translationNl": "siroop",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/setrop:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-setrop-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/setrop"
    ],
    "content_unit_slugs": [
      "item-setrop"
    ],
    "block_kind": "practice_bridge",
    "display_order": 531,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/setrop:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-setrop-susu-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/setrop-susu"
    ],
    "content_unit_slugs": [
      "item-setrop-susu"
    ],
    "block_kind": "exposure",
    "display_order": 540,
    "payload_json": {
      "baseText": "setrop susu",
      "itemType": "word",
      "translationNl": "zoet drankje (melk met siroop)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/setrop-susu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop-susu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/setrop-susu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/setrop-susu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-setrop-susu-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/setrop-susu"
    ],
    "content_unit_slugs": [
      "item-setrop-susu"
    ],
    "block_kind": "practice_bridge",
    "display_order": 541,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/setrop-susu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-sore-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/sore"
    ],
    "content_unit_slugs": [
      "item-sore"
    ],
    "block_kind": "exposure",
    "display_order": 550,
    "payload_json": {
      "baseText": "sore",
      "itemType": "word",
      "translationNl": "namiddag, avond",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/sore:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sore:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sore:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sore:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-sore-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/sore"
    ],
    "content_unit_slugs": [
      "item-sore"
    ],
    "block_kind": "practice_bridge",
    "display_order": 551,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/sore:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-susu-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/susu"
    ],
    "content_unit_slugs": [
      "item-susu"
    ],
    "block_kind": "exposure",
    "display_order": 560,
    "payload_json": {
      "baseText": "susu",
      "itemType": "word",
      "translationNl": "melk",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/susu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/susu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/susu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/susu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-susu-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/susu"
    ],
    "content_unit_slugs": [
      "item-susu"
    ],
    "block_kind": "practice_bridge",
    "display_order": 561,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/susu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-taman-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/taman"
    ],
    "content_unit_slugs": [
      "item-taman"
    ],
    "block_kind": "exposure",
    "display_order": 570,
    "payload_json": {
      "baseText": "taman",
      "itemType": "word",
      "translationNl": "park, tuin",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/taman:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-taman-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/taman"
    ],
    "content_unit_slugs": [
      "item-taman"
    ],
    "block_kind": "practice_bridge",
    "display_order": 571,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/taman:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-taman-mini-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/taman-mini"
    ],
    "content_unit_slugs": [
      "item-taman-mini"
    ],
    "block_kind": "exposure",
    "display_order": 580,
    "payload_json": {
      "baseText": "Taman Mini",
      "itemType": "word",
      "translationNl": "Klein Indonesie - park met traditionele Indonesische gebouwen in Jakarta",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/taman-mini:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman-mini:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/taman-mini:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/taman-mini:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-taman-mini-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/taman-mini"
    ],
    "content_unit_slugs": [
      "item-taman-mini"
    ],
    "block_kind": "practice_bridge",
    "display_order": 581,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/taman-mini:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-tapi-tetapi-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/tapi-tetapi"
    ],
    "content_unit_slugs": [
      "item-tapi-tetapi"
    ],
    "block_kind": "exposure",
    "display_order": 590,
    "payload_json": {
      "baseText": "tapi / tetapi",
      "itemType": "word",
      "translationNl": "maar, echter",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/tapi-tetapi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tapi-tetapi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-tapi-tetapi-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/tapi-tetapi"
    ],
    "content_unit_slugs": [
      "item-tapi-tetapi"
    ],
    "block_kind": "practice_bridge",
    "display_order": 591,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/tapi-tetapi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-terus-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/terus"
    ],
    "content_unit_slugs": [
      "item-terus"
    ],
    "block_kind": "exposure",
    "display_order": 600,
    "payload_json": {
      "baseText": "terus",
      "itemType": "word",
      "translationNl": "voorts, steeds, maar door",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/terus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terus:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-terus-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/terus"
    ],
    "content_unit_slugs": [
      "item-terus"
    ],
    "block_kind": "practice_bridge",
    "display_order": 601,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/terus:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-uang-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/uang"
    ],
    "content_unit_slugs": [
      "item-uang"
    ],
    "block_kind": "exposure",
    "display_order": 610,
    "payload_json": {
      "baseText": "uang",
      "itemType": "word",
      "translationNl": "geld",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/uang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-uang-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/uang"
    ],
    "content_unit_slugs": [
      "item-uang"
    ],
    "block_kind": "practice_bridge",
    "display_order": 611,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/uang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-wah-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/wah"
    ],
    "content_unit_slugs": [
      "item-wah"
    ],
    "block_kind": "exposure",
    "display_order": 620,
    "payload_json": {
      "baseText": "wah!",
      "itemType": "word",
      "translationNl": "goh! nou! (stopwoord/uitroep)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/wah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/wah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/wah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/wah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-wah-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/wah"
    ],
    "content_unit_slugs": [
      "item-wah"
    ],
    "block_kind": "practice_bridge",
    "display_order": 621,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/wah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah"
    ],
    "content_unit_slugs": [
      "item-ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah"
    ],
    "block_kind": "exposure",
    "display_order": 630,
    "payload_json": {
      "baseText": "Ibu dan bapak enak saja ke Taman Mini. Kita harus belajar di rumah.",
      "itemType": "dialogue_chunk",
      "translationNl": "Moeder en vader gaan zo maar naar Taman Mini. Wij moeten thuis studeren.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah"
    ],
    "content_unit_slugs": [
      "item-ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah"
    ],
    "block_kind": "practice_bridge",
    "display_order": 631,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/ibu-dan-bapak-enak-saja-ke-taman-mini-kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aku-tidak-senang-tinggal-di-rumah-terus-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aku-tidak-senang-tinggal-di-rumah-terus"
    ],
    "content_unit_slugs": [
      "item-aku-tidak-senang-tinggal-di-rumah-terus"
    ],
    "block_kind": "exposure",
    "display_order": 640,
    "payload_json": {
      "baseText": "Aku tidak senang tinggal di rumah terus.",
      "itemType": "dialogue_chunk",
      "translationNl": "Ik vind het niet leuk om steeds thuis te blijven.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aku-tidak-senang-tinggal-di-rumah-terus-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aku-tidak-senang-tinggal-di-rumah-terus"
    ],
    "content_unit_slugs": [
      "item-aku-tidak-senang-tinggal-di-rumah-terus"
    ],
    "block_kind": "practice_bridge",
    "display_order": 641,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aku-tidak-senang-tinggal-di-rumah-terus:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kita-harus-kerja-dulu-sebentar-nanti-kita-pergi-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi"
    ],
    "content_unit_slugs": [
      "item-kita-harus-kerja-dulu-sebentar-nanti-kita-pergi"
    ],
    "block_kind": "exposure",
    "display_order": 650,
    "payload_json": {
      "baseText": "Kita harus kerja dulu sebentar. Nanti kita pergi.",
      "itemType": "dialogue_chunk",
      "translationNl": "We moeten eerst even werken. Daarna gaan we.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kita-harus-kerja-dulu-sebentar-nanti-kita-pergi-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi"
    ],
    "content_unit_slugs": [
      "item-kita-harus-kerja-dulu-sebentar-nanti-kita-pergi"
    ],
    "block_kind": "practice_bridge",
    "display_order": 651,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kita-harus-kerja-dulu-sebentar-nanti-kita-pergi:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang"
    ],
    "content_unit_slugs": [
      "item-aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang"
    ],
    "block_kind": "exposure",
    "display_order": 660,
    "payload_json": {
      "baseText": "Aduh, kami mau ke luar, jalan-jalan dan makan di restoran Mi Enak tetapi tidak ada uang.",
      "itemType": "dialogue_chunk",
      "translationNl": "Ai, wij willen naar buiten, wandelen en eten in restaurant Mi Enak maar er is geen geld.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang"
    ],
    "content_unit_slugs": [
      "item-aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang"
    ],
    "block_kind": "practice_bridge",
    "display_order": 661,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/aduh-kami-mau-ke-luar-jalan-jalan-dan-makan-di-restoran-mi-enak-tetapi-tidak-ada-uang:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-besok-saja-jalan-jalan-dengan-ayahmu-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/besok-saja-jalan-jalan-dengan-ayahmu"
    ],
    "content_unit_slugs": [
      "item-besok-saja-jalan-jalan-dengan-ayahmu"
    ],
    "block_kind": "exposure",
    "display_order": 670,
    "payload_json": {
      "baseText": "Besok saja jalan-jalan dengan ayahmu.",
      "itemType": "dialogue_chunk",
      "translationNl": "Ga morgen maar wandelen met je vader.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-besok-saja-jalan-jalan-dengan-ayahmu-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/besok-saja-jalan-jalan-dengan-ayahmu"
    ],
    "content_unit_slugs": [
      "item-besok-saja-jalan-jalan-dengan-ayahmu"
    ],
    "block_kind": "practice_bridge",
    "display_order": 671,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/besok-saja-jalan-jalan-dengan-ayahmu:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-baiklah-tapi-boleh-minta-setrop-susu-ya-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya"
    ],
    "content_unit_slugs": [
      "item-baiklah-tapi-boleh-minta-setrop-susu-ya"
    ],
    "block_kind": "exposure",
    "display_order": 680,
    "payload_json": {
      "baseText": "Baiklah, tapi boleh minta setrop susu ya?",
      "itemType": "dialogue_chunk",
      "translationNl": "Goed dan, maar mag ik een setrop susu?",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-baiklah-tapi-boleh-minta-setrop-susu-ya-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya"
    ],
    "content_unit_slugs": [
      "item-baiklah-tapi-boleh-minta-setrop-susu-ya"
    ],
    "block_kind": "practice_bridge",
    "display_order": 681,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/baiklah-tapi-boleh-minta-setrop-susu-ya:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kita-harus-belajar-di-rumah-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kita-harus-belajar-di-rumah"
    ],
    "content_unit_slugs": [
      "item-kita-harus-belajar-di-rumah"
    ],
    "block_kind": "exposure",
    "display_order": 690,
    "payload_json": {
      "baseText": "Kita harus belajar di rumah.",
      "itemType": "sentence",
      "translationNl": "Wij moeten thuis studeren. (inclusief: jij ook)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kita-harus-belajar-di-rumah-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kita-harus-belajar-di-rumah"
    ],
    "content_unit_slugs": [
      "item-kita-harus-belajar-di-rumah"
    ],
    "block_kind": "practice_bridge",
    "display_order": 691,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kita-harus-belajar-di-rumah:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kami-mau-ke-luar-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kami-mau-ke-luar"
    ],
    "content_unit_slugs": [
      "item-kami-mau-ke-luar"
    ],
    "block_kind": "exposure",
    "display_order": 700,
    "payload_json": {
      "baseText": "Kami mau ke luar.",
      "itemType": "sentence",
      "translationNl": "Wij willen naar buiten. (exclusief: jij niet)",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kami-mau-ke-luar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kami-mau-ke-luar:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-kami-mau-ke-luar-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/kami-mau-ke-luar"
    ],
    "content_unit_slugs": [
      "item-kami-mau-ke-luar"
    ],
    "block_kind": "practice_bridge",
    "display_order": 701,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/kami-mau-ke-luar:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-di-mana-bukuku-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/di-mana-bukuku"
    ],
    "content_unit_slugs": [
      "item-di-mana-bukuku"
    ],
    "block_kind": "exposure",
    "display_order": 710,
    "payload_json": {
      "baseText": "Di mana bukuku?",
      "itemType": "sentence",
      "translationNl": "Waar is mijn boek?",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/di-mana-bukuku:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di-mana-bukuku:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-di-mana-bukuku-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/di-mana-bukuku"
    ],
    "content_unit_slugs": [
      "item-di-mana-bukuku"
    ],
    "block_kind": "practice_bridge",
    "display_order": 711,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/di-mana-bukuku:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mobilmu-rusak-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mobilmu-rusak"
    ],
    "content_unit_slugs": [
      "item-mobilmu-rusak"
    ],
    "block_kind": "exposure",
    "display_order": 720,
    "payload_json": {
      "baseText": "Mobilmu rusak.",
      "itemType": "sentence",
      "translationNl": "Jouw auto is kapot.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mobilmu-rusak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mobilmu-rusak:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-mobilmu-rusak-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/mobilmu-rusak"
    ],
    "content_unit_slugs": [
      "item-mobilmu-rusak"
    ],
    "block_kind": "practice_bridge",
    "display_order": 721,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/mobilmu-rusak:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-pembantunya-sakit-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/pembantunya-sakit"
    ],
    "content_unit_slugs": [
      "item-pembantunya-sakit"
    ],
    "block_kind": "exposure",
    "display_order": 730,
    "payload_json": {
      "baseText": "Pembantunya sakit.",
      "itemType": "sentence",
      "translationNl": "Zijn/haar hulpje is ziek.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/pembantunya-sakit:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pembantunya-sakit:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-pembantunya-sakit-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/pembantunya-sakit"
    ],
    "content_unit_slugs": [
      "item-pembantunya-sakit"
    ],
    "block_kind": "practice_bridge",
    "display_order": 731,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/pembantunya-sakit:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-uang-kita-sudah-habis-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/uang-kita-sudah-habis"
    ],
    "content_unit_slugs": [
      "item-uang-kita-sudah-habis"
    ],
    "block_kind": "exposure",
    "display_order": 740,
    "payload_json": {
      "baseText": "Uang kita sudah habis.",
      "itemType": "sentence",
      "translationNl": "Ons geld is al op.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/uang-kita-sudah-habis:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/uang-kita-sudah-habis:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-uang-kita-sudah-habis-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/uang-kita-sudah-habis"
    ],
    "content_unit_slugs": [
      "item-uang-kita-sudah-habis"
    ],
    "block_kind": "practice_bridge",
    "display_order": 741,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/uang-kita-sudah-habis:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-rumahnya-bagus-sekali-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/rumahnya-bagus-sekali"
    ],
    "content_unit_slugs": [
      "item-rumahnya-bagus-sekali"
    ],
    "block_kind": "exposure",
    "display_order": 750,
    "payload_json": {
      "baseText": "Rumahnya bagus sekali.",
      "itemType": "sentence",
      "translationNl": "Hun huis is erg mooi.",
      "translationEn": ""
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:l1_to_id_choice:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-item-rumahnya-bagus-sekali-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "learning_items/rumahnya-bagus-sekali"
    ],
    "content_unit_slugs": [
      "item-rumahnya-bagus-sekali"
    ],
    "block_kind": "practice_bridge",
    "display_order": 751,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/rumahnya-bagus-sekali:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-5-pattern-kami-vs-kita-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5/pattern-kami-vs-kita"
    ],
    "content_unit_slugs": [
      "pattern-kami-vs-kita"
    ],
    "block_kind": "exposure",
    "display_order": 760,
    "payload_json": {
      "slug": "kami-vs-kita",
      "name": "KITA vs KAMI — Inclusief en exclusief wij",
      "description": "Indonesisch heeft twee woorden voor 'wij': kita (inclusief — de aangesprokene telt mee) en kami (exclusief — de aangesprokene is uitgesloten).",
      "complexityScore": 4
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": [
      "cap:v1:pattern:lesson-5/pattern-kami-vs-kita:pattern_recognition:none:text:none"
    ]
  },
  {
    "block_key": "lesson-5-pattern-kami-vs-kita-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5/pattern-kami-vs-kita"
    ],
    "content_unit_slugs": [
      "pattern-kami-vs-kita"
    ],
    "block_kind": "practice_bridge",
    "display_order": 761,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "guided_practice_completed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-pattern-possessive-suffix-placement-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5/pattern-possessive-suffix-placement"
    ],
    "content_unit_slugs": [
      "pattern-possessive-suffix-placement"
    ],
    "block_kind": "exposure",
    "display_order": 770,
    "payload_json": {
      "slug": "possessive-suffix-placement",
      "name": "Bezittelijk voornaamwoord — achterplaatsing en afgekorte vormen",
      "description": "Het bezittelijk voornaamwoord staat altijd achter het zelfstandig naamwoord. Voor aku en kamu bestaan afgekorte vormen: -ku (mijn), -mu/-kau (jouw), -nya (zijn/haar/hun).",
      "complexityScore": 4
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": [
      "cap:v1:pattern:lesson-5/pattern-possessive-suffix-placement:pattern_recognition:none:text:none"
    ]
  },
  {
    "block_key": "lesson-5-pattern-possessive-suffix-placement-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5/pattern-possessive-suffix-placement"
    ],
    "content_unit_slugs": [
      "pattern-possessive-suffix-placement"
    ],
    "block_kind": "practice_bridge",
    "display_order": 771,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "guided_practice_completed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-pattern-pronoun-register-levels-exposure",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5/pattern-pronoun-register-levels"
    ],
    "content_unit_slugs": [
      "pattern-pronoun-register-levels"
    ],
    "block_kind": "exposure",
    "display_order": 780,
    "payload_json": {
      "slug": "pronoun-register-levels",
      "name": "Persoonlijk voornaamwoord — formeel, neutraal en informeel",
      "description": "Het Indonesisch heeft veel meer persoonlijke voornaamwoorden dan het Nederlands. De keuze hangt af van situatie, sexe, leeftijd en status: formeel (Tuan/Nyonya), neutraal (Bapak/Ibu/Anda), informeel (kamu/aku).",
      "complexityScore": 5
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": [
      "cap:v1:pattern:lesson-5/pattern-pronoun-register-levels:pattern_recognition:none:text:none"
    ]
  },
  {
    "block_key": "lesson-5-pattern-pronoun-register-levels-practice",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5/pattern-pronoun-register-levels"
    ],
    "content_unit_slugs": [
      "pattern-pronoun-register-levels"
    ],
    "block_kind": "practice_bridge",
    "display_order": 781,
    "payload_json": {
      "label": "Practice this content"
    },
    "source_progress_event": "guided_practice_completed",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-5-recap",
    "source_ref": "lesson-5",
    "source_refs": [
      "lesson-5"
    ],
    "content_unit_slugs": [],
    "block_kind": "recap",
    "display_order": 9999,
    "payload_json": {
      "title": "Recap"
    },
    "source_progress_event": "lesson_completed",
    "capability_key_refs": []
  }
]
