#!/usr/bin/env bun
// scripts/backup-cloud.ts
//
// Local backup of the IRREPLACEABLE half of the Supabase Cloud project
// (wodpkxsmildtgndnbraa): learner + usage data, and the auth schema.
//
// WHY THIS EXISTS: the homelab's nightly pg_dump container
// (docs/process/restore-runbook.md) protects the HOMELAB Postgres and never
// touches cloud. Supabase does take daily backups on the Free plan, but they
// are only *accessible after upgrading* — so until Pro, cloud learner data has
// no restorable copy. CLAUDE.md's Operating Context calls that data PRECIOUS.
//
// WHAT IT DELIBERATELY DOES NOT BACK UP, and why:
//
//   - Lesson/reader content — pipeline-is-writer (ADR 0011). The staging files
//     under scripts/data/staging/ are canonical; a re-publish regenerates every
//     row. Backing it up would duplicate what git already versions.
//   - Storage bytes (~462 MB) — the masters live on this Mac under content/,
//     and TTS is regenerable. A nightly full pull would also be 13.9 GB/month
//     against the Free plan's 5 GB egress quota: the backup would break the
//     budget it runs inside.
//   - Capability content — regenerable by re-seeding. ⚠ Residual: ADR 0011
//     makes capability content DB-authoritative *after* seeding, so post-publish
//     corrections made via the flag→review loop live only in the DB and would
//     need redoing after a restore. Accepted — content is replaceable effort,
//     learner history is not.
//
// A learner's FSRS state cannot be regenerated by anything. That asymmetry is
// the whole design: this script is small and cheap precisely so it can run
// often without thought.
//
// Usage:
//   bun scripts/backup-cloud.ts                 # learner + auth data
//   bun scripts/backup-cloud.ts --full          # whole database (incl. content)
//   BACKUP_DIR=/elsewhere KEEP_DUMPS=30 bun scripts/backup-cloud.ts
//
// Requires in .env.local: CLOUD_DB_HOST / CLOUD_DB_PORT / CLOUD_DB_USER /
// CLOUD_DB_PASSWORD.

import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { mkdir, readdir, stat, unlink, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { homedir } from 'node:os'

const run = promisify(execFile)

for (const line of (await readFile('.env.local', 'utf8')).split('\n')) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2]
}

const BACKUP_DIR = process.env.BACKUP_DIR ?? join(homedir(), 'kamoebisa-backups')
const KEEP_DUMPS = Number.parseInt(process.env.KEEP_DUMPS ?? '30', 10)
const full = process.argv.includes('--full')

/**
 * Every table a user's activity writes to. Losing any of these loses something
 * no pipeline can rebuild.
 *
 * Verified against the live cloud project 2026-08-02 — `lesson_progress` is
 * NOT in this list because it does not exist there; add it only if a migration
 * later introduces it.
 */
const LEARNER_TABLES = [
  'learner_capability_state',   // FSRS scheduling state — the irreplaceable core
  'capability_review_events',   // every answer ever given
  'learning_sessions',
  'learner_lesson_activation',
  'profiles',
  'entitlements',               // who has paid; rebuildable from Stripe, but slowly
  'stripe_webhook_events',      // idempotency ledger — replaying without it double-writes
  'user_roles',
  'error_logs',
]

/**
 * Content tables that must ALSO be captured — not for their content, but for
 * their IDENTITY.
 *
 * `learning_capabilities.id` is `default gen_random_uuid()`. The capability
 * stage upserts on the stable `canonical_key`, but the id itself is random, so
 * reseeding content into a FRESH database mints entirely new UUIDs. Every
 * learner_capability_state.capability_id and capability_review_events row in a
 * backup would then reference ids that no longer exist, and the restore would
 * fail every foreign key — losing exactly the FSRS history this script exists
 * to protect. Same story for lessons.id via learner_lesson_activation.
 *
 * Proven by the restore drill on 2026-08-02: with these excluded, the drill hit
 *   ERROR: insert or update on "learner_lesson_activation" violates foreign key
 * and learner rows landed at 0.
 *
 * This is not a retreat from "content is regenerable" — the other 43 content
 * tables stay out. It is only the two whose primary keys learner data points
 * at. Cost: ~13 MB.
 */
const IDENTITY_TABLES = ['learning_capabilities', 'lessons']

/**
 * Tables whose absence makes a restore useless. Asserted against the dump's own
 * manifest after every run — see the note at the verification step.
 *
 * auth.identities is here because losing it orphans every Google login even if
 * auth.users survives; learner_capability_state is the FSRS scheduling core.
 */
const REQUIRED_IN_DUMP = [
  'auth.users',
  'auth.identities',
  'indonesian.learner_capability_state',
  'indonesian.profiles',
  // Without these the FSRS rows above cannot be restored at all — see
  // IDENTITY_TABLES.
  'indonesian.learning_capabilities',
  'indonesian.lessons',
]

const need = (k: string) => {
  const v = process.env[k]
  if (!v) throw new Error(`${k} missing from .env.local`)
  return v
}
const DB = {
  host: need('CLOUD_DB_HOST'),
  port: need('CLOUD_DB_PORT'),
  user: need('CLOUD_DB_USER'),
  password: need('CLOUD_DB_PASSWORD'),
}
const mb = (n: number) => (n / 1e6).toFixed(2)

const dir = join(BACKUP_DIR, 'postgres')
await mkdir(dir, { recursive: true })
const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
const kind = full ? 'full' : 'learner'
const path = join(dir, `cloud_${kind}_${stamp}.dump`)

// ⚠ MUST be `-t 'auth.*'`, NOT `-n auth`. pg_dump does not union -n with -t:
// when both are given the -t filter wins and the schema selection contributes
// nothing, so `-n auth -t indonesian.x` silently produces a dump with NO auth
// tables at all. That passed every check — non-zero size, valid TOC, clean exit
// — and would have restored learner rows keyed to user IDs that no longer
// exist. Caught 2026-08-02 only by listing the dump's actual contents.
//
// auth.identities is the load-bearing one: it maps a Google account to a user,
// so losing it orphans every OAuth login even if auth.users survives.
const scope = full
  ? []
  : ["-t", "auth.*",
     ...[...LEARNER_TABLES, ...IDENTITY_TABLES].flatMap(t => ['-t', `indonesian.${t}`])]

console.log(`Backing up cloud (${kind}) → ${path}`)

// pg_dump creates the output file BEFORE it can fail (bad credentials, dropped
// connection), leaving a 0-byte artefact that a naive retention sweep counts as
// a backup and that looks real in a directory listing. Observed 2026-08-02.
// Any failure past this point must remove the file.
let stdout: string
try {
  await run('pg_dump', [
    '-h', DB.host, '-p', DB.port, '-U', DB.user, '-d', 'postgres',
    '--format=custom',
    // Cloud roles differ from any restore target; ownership and ACLs are
    // recreated by scripts/migration.sql, not carried in the dump.
    '--no-owner', '--no-privileges',
    ...scope,
    '-f', path,
  ], { env: { ...process.env, PGPASSWORD: DB.password }, maxBuffer: 1 << 28 })

  // A dump that cannot be listed is not a backup. Failing here is cheap;
  // failing during an incident is not. Mirrors the restore runbook's first check.
  ;({ stdout } = await run('pg_restore', ['--list', path], { maxBuffer: 1 << 28 }))
  if (!stdout.includes('Archive created at')) {
    throw new Error('pg_restore --list produced no TOC')
  }

  // CONTENT assertion, not just structural. The `-n auth` bug produced a dump
  // that was non-empty, had a valid TOC and exited 0 — while containing no auth
  // tables whatsoever. Only listing the contents revealed it. Never trust a
  // backup's exit code over its manifest.
  const missing = REQUIRED_IN_DUMP.filter(t => !stdout.includes(`TABLE DATA ${t.replace('.', ' ')} `))
  if (missing.length) {
    throw new Error(
      `dump is missing required tables: ${missing.join(', ')}. ` +
      'A restore from this file would produce orphaned or incomplete learner data.',
    )
  }
} catch (err) {
  await unlink(path).catch(() => {})
  console.error(`  ✗ backup FAILED — removed incomplete ${path.split('/').pop()}`)
  throw err
}
const tocEntries = stdout.split('\n').filter(l => l.trim() && !l.startsWith(';')).length
const bytes = (await stat(path)).size

// Retention. Names sort lexicographically because the stamp is ISO-8601.
const existing = (await readdir(dir)).filter(f => f.startsWith(`cloud_${kind}_`) && f.endsWith('.dump')).sort().reverse()
for (const old of existing.slice(KEEP_DUMPS)) {
  await unlink(join(dir, old))
  console.log(`  pruned ${old}`)
}

console.log(`  ✓ ${mb(bytes)} MB, ${tocEntries} TOC entries, verified`)
console.log(`  retained: ${Math.min(existing.length, KEEP_DUMPS)} ${kind} dumps (KEEP_DUMPS=${KEEP_DUMPS})`)
if (!full) console.log(`  scope: auth schema + ${LEARNER_TABLES.length} learner tables + ${IDENTITY_TABLES.length} identity tables (${IDENTITY_TABLES.join(', ')})`)
console.log('\nRestore: docs/process/restore-runbook.md § cloud')
