#!/usr/bin/env bun
/**
 * generate-staging-files.ts — Step 4 of content pipeline
 *
 * Reads sections-catalog.json and deterministically generates staging files.
 * All decisions were made by catalog-lesson-sections.ts — this script only transforms.
 *
 * Usage:
 *   bun scripts/generate-staging-files.ts <lesson-number> [--force]
 *
 * Reads:   scripts/data/staging/lesson-<N>/sections-catalog.json
 * Writes:  scripts/data/staging/lesson-<N>/lesson.ts
 *          scripts/data/staging/lesson-<N>/learning-items.ts
 *          scripts/data/staging/lesson-<N>/grammar-patterns.ts  (empty scaffold if absent)
 *          scripts/data/staging/lesson-<N>/candidates.ts        (empty scaffold if absent)
 *          scripts/data/staging/lesson-<N>/cloze-contexts.ts    (empty scaffold if absent)
 *          scripts/data/staging/lesson-<N>/index.ts             (barrel export)
 *
 * Idempotent — skips existing files unless --force.
 * lesson.ts and learning-items.ts always overwrite (they are purely derived from the catalog).
 * grammar-patterns.ts, candidates.ts, cloze-contexts.ts only get scaffolded if absent.
 */

import fs from 'fs'
import path from 'path'

// ── Types (mirrors catalog schema) ───────────────────────────────────────────

type SectionType =
  | 'vocabulary' | 'expressions' | 'numbers'
  | 'grammar' | 'exercises' | 'dialogue'
  | 'text' | 'pronunciation' | 'reference_table'

interface VocabItem { indonesian: string; dutch: string }
interface DialogueLine { speaker: string; text: string }

interface CatalogSection {
  id: number
  type: SectionType
  title: string
  source_pages: number[]
  confidence: 'high' | 'medium' | 'low'
  items?: VocabItem[]
  lines?: DialogueLine[]
  paragraphs?: string[]
  raw_text?: string
}

interface SectionsCatalog {
  lesson: number
  generatedAt: string
  sourcePages: number
  lessonMeta: {
    title: string
    level: string
    module_id: string
    order_index: number
  }
  sections: CatalogSection[]
  flags: string[]
}

// ── Helpers ───────────────────────────────────────────────────────────────────


function alwaysWrite(filePath: string, content: string, label: string) {
  fs.writeFileSync(filePath, content)
  console.log(`  WRITE: ${label}`)
}

function scaffoldIfAbsent(filePath: string, content: string, label: string) {
  if (fs.existsSync(filePath)) {
    console.log(`  SKIP (exists): ${label}`)
    return
  }
  fs.writeFileSync(filePath, content)
  console.log(`  SCAFFOLD: ${label}`)
}

// ── lesson.ts generation ──────────────────────────────────────────────────────

function buildSectionContent(section: CatalogSection): Record<string, unknown> {
  switch (section.type) {
    case 'vocabulary':
    case 'expressions':
    case 'numbers':
      return {
        type: section.type,
        items: (section.items || []).map(item => ({
          indonesian: item.indonesian,
          dutch: item.dutch,
        })),
      }

    case 'dialogue':
      return {
        type: 'dialogue',
        lines: (section.lines || []).map(line => ({
          speaker: line.speaker,
          text: line.text,
          translation: '',
        })),
      }

    case 'text':
      return {
        type: 'text',
        paragraphs: section.paragraphs || [],
      }

    case 'grammar':
    case 'reference_table':
      // Raw text — linguist-creator will structure into categories array
      return {
        type: section.type,
        body: section.raw_text || '',
      }

    case 'exercises':
      // Raw text — linguist-creator will structure into sections array
      return {
        type: 'exercises',
        body: section.raw_text || '',
      }

    case 'pronunciation':
      return {
        type: 'pronunciation',
        body: section.raw_text || '',
      }

    default:
      return { type: section.type, body: section.raw_text || '' }
  }
}

function generateLessonTs(catalog: SectionsCatalog): string {
  const { lessonMeta, sections } = catalog

  const lessonSections = sections.map((section, idx) => ({
    title: section.title,
    order_index: idx,
    content: buildSectionContent(section),
  }))

  return `// Generated by generate-staging-files.ts from sections-catalog.json
// Do not edit manually — re-run generate-staging-files.ts to regenerate.
// Grammar and exercise sections contain raw_text body — run linguist-creator to structure them.
export const lesson = ${JSON.stringify({
    title: lessonMeta.title,
    description: '',
    level: lessonMeta.level,
    module_id: lessonMeta.module_id,
    order_index: lessonMeta.order_index,
    sections: lessonSections,
  }, null, 2)}
`
}

// ── learning-items.ts generation ─────────────────────────────────────────────

function itemTypeFromSection(sectionType: SectionType, indonesian: string): 'word' | 'phrase' {
  if (sectionType === 'expressions') return 'phrase'
  // Vocabulary/numbers: compound nouns (air putih, nasi goreng) stay 'word'.
  // Only treat as 'phrase' when 3+ tokens — single-word and compound nouns are 'word'.
  return indonesian.trim().split(/\s+/).length >= 3 ? 'phrase' : 'word'
}

interface LearningItemsReport {
  totalGenerated: number
  droppedEmptyIndonesian: number
  droppedEmptyDutch: number
  emptyEnglish: number  // expected but notable
}

function generateLearningItemsTs(catalog: SectionsCatalog): { content: string; report: LearningItemsReport } {
  const items: unknown[] = []
  const report: LearningItemsReport = {
    totalGenerated: 0,
    droppedEmptyIndonesian: 0,
    droppedEmptyDutch: 0,
    emptyEnglish: 0,
  }

  for (const section of catalog.sections) {
    if (['vocabulary', 'expressions', 'numbers'].includes(section.type) && section.items) {
      for (const item of section.items) {
        if (!item.indonesian?.trim()) { report.droppedEmptyIndonesian++; continue }
        if (!item.dutch?.trim())      { report.droppedEmptyDutch++;      continue }
        if (!item.translation_en?.trim()) report.emptyEnglish++
        items.push({
          base_text: item.indonesian.trim(),
          item_type: itemTypeFromSection(section.type as SectionType, item.indonesian),
          context_type: 'vocabulary_list',
          translation_nl: item.dutch.trim(),
          translation_en: '',
          source_page: section.source_pages[0] ?? null,
          review_status: 'pending_review',
        })
      }
    }

    if (section.type === 'dialogue' && section.lines) {
      for (const line of section.lines) {
        if (!line.text?.trim() || line.speaker === 'narrator') continue
        items.push({
          base_text: line.text.trim(),
          item_type: 'dialogue_chunk',
          context_type: 'dialogue',
          translation_nl: '',
          translation_en: '',
          source_page: section.source_pages[0] ?? null,
          review_status: 'pending_review',
        })
      }
    }
  }

  report.totalGenerated = items.length

  const content = `// Generated by generate-staging-files.ts from sections-catalog.json
// Do not edit manually — re-run generate-staging-files.ts to regenerate.
// review_status starts as 'pending_review' — items publish immediately; review happens live in the app.
export const learningItems = ${JSON.stringify(items, null, 2)}
`
  return { content, report }
}

// ── Scaffold templates ────────────────────────────────────────────────────────

function scaffoldGrammarPatterns(lessonNumber: number): string {
  return `// Grammar patterns for Lesson ${lessonNumber}
// Generated as empty scaffold — linguist-creator will populate this.
// Schema: pattern_name, description, confusion_group, page_reference, slug, complexity_score
export const grammarPatterns = []
`
}

function scaffoldCandidates(lessonNumber: number): string {
  return `// Exercise candidates for Lesson ${lessonNumber}
// Generated as empty scaffold — linguist-creator will populate this.
export const candidates = []
`
}

function scaffoldClozeContexts(lessonNumber: number): string {
  return `// Cloze contexts for Lesson ${lessonNumber}
// Generated as empty scaffold — linguist-creator will populate this.
export const clozeContexts = []
`
}

function generateIndexTs(): string {
  return `export { lesson } from './lesson'
export { learningItems } from './learning-items'
export { grammarPatterns } from './grammar-patterns'
export { candidates } from './candidates'
export { clozeContexts } from './cloze-contexts'
`
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2)
  const lessonNumber = parseInt(args[0], 10)
  if (isNaN(lessonNumber)) {
    console.error('Usage: bun scripts/generate-staging-files.ts <lesson-number> [--force]')
    process.exit(1)
  }


  const stagingDir = path.join(process.cwd(), 'scripts', 'data', 'staging', `lesson-${lessonNumber}`)
  const catalogPath = path.join(stagingDir, 'sections-catalog.json')

  if (!fs.existsSync(catalogPath)) {
    console.error(`Error: No catalog found at ${catalogPath}`)
    console.error('Run first: bun scripts/catalog-lesson-sections.ts ' + lessonNumber)
    process.exit(1)
  }

  const catalog: SectionsCatalog = JSON.parse(fs.readFileSync(catalogPath, 'utf-8'))

  console.log(`Generating staging files for lesson ${lessonNumber} (${catalog.lessonMeta.title})...`)
  console.log(`  Sections in catalog: ${catalog.sections.length}`)
  if (catalog.flags.length > 0) {
    console.log(`  Catalog flags: ${catalog.flags.length} (see sections-catalog.json)`)
  }
  console.log()

  fs.mkdirSync(stagingDir, { recursive: true })

  // lesson.ts and learning-items.ts are always regenerated from catalog
  alwaysWrite(path.join(stagingDir, 'lesson.ts'), generateLessonTs(catalog), 'lesson.ts')
  const { content: learningItemsContent, report: itemsReport } = generateLearningItemsTs(catalog)
  alwaysWrite(path.join(stagingDir, 'learning-items.ts'), learningItemsContent, 'learning-items.ts')

  // Quality gate: report dropped and missing items
  if (itemsReport.droppedEmptyIndonesian > 0) {
    console.warn(`  ⚠️  ${itemsReport.droppedEmptyIndonesian} catalog items dropped — missing indonesian text`)
  }
  if (itemsReport.droppedEmptyDutch > 0) {
    console.warn(`  ⚠️  ${itemsReport.droppedEmptyDutch} catalog items dropped — missing dutch translation`)
  }
  if (itemsReport.emptyEnglish > 0) {
    console.warn(`  ⓘ  ${itemsReport.emptyEnglish} items have no translation_en — EN users won't see these until filled in`)
  }

  const vocabSectionsInCatalog = catalog.sections.filter(s =>
    ['vocabulary', 'expressions', 'numbers'].includes(s.type) && (s.items?.length ?? 0) > 0
  )
  if (vocabSectionsInCatalog.length > 0 && itemsReport.totalGenerated === 0) {
    console.error(`\n✗ Catalog has ${vocabSectionsInCatalog.length} vocabulary section(s) but 0 learning items were generated.`)
    console.error('  This means all items had empty indonesian or dutch fields. Fix the catalog before proceeding.')
    process.exit(1)
  }

  // Scaffolds only written if file doesn't exist (preserve linguist work)
  scaffoldIfAbsent(path.join(stagingDir, 'grammar-patterns.ts'), scaffoldGrammarPatterns(lessonNumber), 'grammar-patterns.ts')
  scaffoldIfAbsent(path.join(stagingDir, 'candidates.ts'), scaffoldCandidates(lessonNumber), 'candidates.ts')
  scaffoldIfAbsent(path.join(stagingDir, 'cloze-contexts.ts'), scaffoldClozeContexts(lessonNumber), 'cloze-contexts.ts')

  // index.ts always regenerated (just re-exports)
  alwaysWrite(path.join(stagingDir, 'index.ts'), generateIndexTs(), 'index.ts')

  // Summary
  const vocabSections = catalog.sections.filter(s => ['vocabulary', 'expressions', 'numbers'].includes(s.type))
  const totalItems = vocabSections.reduce((n, s) => n + (s.items?.length ?? 0), 0)
  const dialogueSections = catalog.sections.filter(s => s.type === 'dialogue')
  const dialogueLines = dialogueSections.reduce((n, s) => n + (s.lines?.filter(l => l.speaker !== 'narrator').length ?? 0), 0)
  const rawSections = catalog.sections.filter(s => ['grammar', 'exercises', 'pronunciation', 'reference_table'].includes(s.type))

  console.log('\nSummary:')
  console.log(`  learning_items to review: ${totalItems + dialogueLines}`)
  console.log(`    vocabulary/expressions/numbers: ${totalItems}`)
  console.log(`    dialogue chunks: ${dialogueLines}`)
  console.log(`  raw sections for linguist-creator: ${rawSections.length}`)
  rawSections.forEach(s => console.log(`    - ${s.title} (${s.type})`))

  console.log('\nNext steps:')
  console.log(`  1. Run linguist-creator to structure grammar/exercises and generate candidates`)
  console.log(`  2. Run linguist-reviewer to validate creator output`)
  console.log(`  3. bun scripts/publish-approved-content.ts ${lessonNumber}`)
  console.log(`     All content publishes immediately — review happens live in the app via admin account`)
}

main()
