// Regenerate lesson-page-blocks.ts for every lesson under scripts/data/staging/lesson-N/
// using the rich-projection bridge in scripts/lib/content-pipeline-output.ts.
//
// Run: npx tsx scripts/regenerate-all-lesson-page-blocks.ts
import fs from 'node:fs'
import path from 'node:path'
import {
  buildContentUnitsFromStaging,
  buildLessonPageBlocksFromStaging,
} from './lib/content-pipeline-output'

async function loadModule(stagingDir: string, file: string): Promise<unknown> {
  const fullPath = path.join(stagingDir, file)
  if (!fs.existsSync(fullPath)) return null
  const url = path.resolve(fullPath)
  return await import(url)
}

async function regenerateLesson(lessonNumber: number): Promise<{ blocks: number; kinds: Record<string, number> } | null> {
  const stagingDir = path.join(process.cwd(), 'scripts/data/staging', `lesson-${lessonNumber}`)
  if (!fs.existsSync(stagingDir)) return null

  const lessonModule = await loadModule(stagingDir, 'lesson.ts') as { lesson: unknown } | null
  const itemsModule = await loadModule(stagingDir, 'learning-items.ts') as { learningItems: unknown } | null
  const grammarModule = await loadModule(stagingDir, 'grammar-patterns.ts') as { grammarPatterns: unknown } | null
  const morphologyModule = await loadModule(stagingDir, 'morphology-patterns.ts') as { affixedFormPairs: unknown } | null
  const capsModule = await loadModule(stagingDir, 'capabilities.ts') as { capabilities: unknown } | null

  if (!lessonModule || !itemsModule || !capsModule) {
    console.log(`Skipping lesson-${lessonNumber}: missing required staging files`)
    return null
  }

  const input = {
    lessonNumber,
    lesson: lessonModule.lesson as Parameters<typeof buildContentUnitsFromStaging>[0]['lesson'],
    learningItems: itemsModule.learningItems as Parameters<typeof buildContentUnitsFromStaging>[0]['learningItems'],
    grammarPatterns: (grammarModule?.grammarPatterns ?? []) as Parameters<typeof buildContentUnitsFromStaging>[0]['grammarPatterns'],
    affixedFormPairs: (morphologyModule?.affixedFormPairs ?? []) as NonNullable<Parameters<typeof buildContentUnitsFromStaging>[0]['affixedFormPairs']>,
  }

  const contentUnits = buildContentUnitsFromStaging(input)
  // Use the published static capabilities.ts so block refs match what publish-approved-content.ts validates against.
  const capabilities = capsModule.capabilities as Parameters<typeof buildLessonPageBlocksFromStaging>[0]['capabilities']
  const blocks = buildLessonPageBlocksFromStaging({ ...input, contentUnits, capabilities })

  const out = `// Regenerated by regenerate-all-lesson-page-blocks.ts
export const lessonPageBlocks = ${JSON.stringify(blocks, null, 2)}
`
  fs.writeFileSync(path.join(stagingDir, 'lesson-page-blocks.ts'), out, 'utf8')

  const kinds: Record<string, number> = {}
  for (const block of blocks) kinds[block.block_kind] = (kinds[block.block_kind] ?? 0) + 1
  return { blocks: blocks.length, kinds }
}

async function main() {
  for (let lessonNumber = 1; lessonNumber <= 9; lessonNumber++) {
    const result = await regenerateLesson(lessonNumber)
    if (result) {
      const summary = Object.entries(result.kinds).map(([k, v]) => `${k}=${v}`).join(', ')
      console.log(`lesson-${lessonNumber}: ${result.blocks} blocks (${summary})`)
    }
  }
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
