// Generated by generate-staging-files.ts from sections-catalog.json
export const learningItems = [
  {
    "base_text": "adat istiadat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zeden en gebruiken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "alam",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "natuur",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "alam, meng-i",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "meemaken / ervaren",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "alir, meng-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "stromen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "arus",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "stroom",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bakar, ter-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verbrand",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "batal, mem-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "niet doorgaan / afzeggen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "biasa, ter-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gewoon / gewend",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "bunyi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "geluid",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "cegah, men-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "voorkomen / tegenhouden / verhinderen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "cerah",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "helder",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "cuaca",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "het weer",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "demikian",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "aldus / zodanig",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "derajat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "graden",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "deras",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "hard (v. regen)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "frustrasi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "frustratie",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gerimis",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "motregen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gores (gorès)",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "schram / kras",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "harap, meng-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verwachten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "hawa",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "het weer / lucht",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "iklim",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "klimaat",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "jemur",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "drogen in de zon, zonnebaden",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "jua = juga",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "ook / weer",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  },
  {
    "base_text": "ketawa",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "lachen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "komputer",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "computer",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "listrik",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "electriciteit",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "luka",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "wond",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "main, per-an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "spelletje",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "masalah",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "probleem / kwestie",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "muncul",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "opkomen / opduiken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "penuh, memenuhi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vervullen, zich houden aan",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "prakira, -an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "voorspelling",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "putus",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kapot / verbroken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "salep",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zalf",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "salur, -an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "lijn",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "sehabis",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "na",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "preposition"
  },
  {
    "base_text": "selokan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "goot / afvoer / sloot",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "sinar, ber-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "schijnen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "suhu",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "temperatuur",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "tergesa-gesa",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gehaast",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "udara",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "lucht / het weer",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "undang, meng-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "uitnodigen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "video",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "video",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kabar angin",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "gerucht",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "masuk angin",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "kouvatten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "prakiraan cuaca",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "weerbericht / weersvoorspelling",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim dingin",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "winter",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim gugur",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "herfst",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim panas",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "zomer",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim semi",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "lente",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim hujan",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "regentijd (oktober - maart)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim kemarau",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "droge tijd (april - september)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim semi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "lente",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim panas",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zomer",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim gugur",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "herfst",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "musim dingin",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "winter",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "salju",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "sneeuw",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "beku",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bevroren",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "berawan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bewolkt",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "angin",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "wind",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kilat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bliksem",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gerimis",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "motregen",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "hujan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "regen",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "petir",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "donderslag",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "matahari",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zon",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bulan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "maan",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bintang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ster",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "banjir",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "overstroming",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gempa bumi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "aardbeving",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "derajat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "graden",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review",
    "pos": "noun"
  }
]
