// Generated by generate-staging-files.ts from sections-catalog.json
export const learningItems = [
  {
    "base_text": "alur, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "geul",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "Taman Impian Ancol",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "pretpark in N.-Jakarta",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "ancol",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "landtong",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "aneh",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vreemd",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "band",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "band (muziek)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "baris, ber-~~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "in rijen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "bebas",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vrij",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "bising",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "herrie / lawaai",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "Blok M",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "winkelcomplex in Jakarta",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "dangdut",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dans en muziek met Indiase invloed",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "dangdut, ber~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dansen op dangdut muziek",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "dansa, ber~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dansen (westers)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "diam, men~i",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bewonen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "disko, ber~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "naar de discotheek gaan",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "Dunia Fantasi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "pretpark in Jakarta",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "fantasi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "fantasie",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gerak-gerik, ber~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bewegingen / gebaren maken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "Glodok",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "winkelwijk in Jakarta",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "hibur, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vermaak / amusement",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "hibur, mencari ~an",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "uitgaan / stappen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "hibur, meng~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "(zich) vermaken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "ikut, meng~i",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "volgen / meedoen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "impi, ~an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "droom",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "jasa",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verdienste / nut",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kena, mengenakan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "aantrekken / aandoen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "kerumun, mengerumuni",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "omstuwen / rondzwermen om",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "kolam ombak",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "golfslagbad",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "konon",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "men zegt dat ...",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  },
  {
    "base_text": "kota metropolitan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "metropool",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kunjung, mengunjungi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bezoeken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "pengunjung",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bezoeker",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "lampau",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "voorbij / vroeger",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "malam hari",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "avond",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "masa",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "tijd / periode",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "masa lampau",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vroeger tijden / vroeger",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "maupun",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "of / hetzij",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "conjunction"
  },
  {
    "base_text": "musik",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "muziek",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "namun",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "echter / toch / maar",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "conjunction"
  },
  {
    "base_text": "pula",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ook / eveneens",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  },
  {
    "base_text": "pun",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ook",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  },
  {
    "base_text": "punya, mem~i",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bezitten / hebben",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "putar, ber~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ronddraaien",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "ria",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vrolijk / uitgelaten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "rupa, me~kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vormen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "sebut, menyebut",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "noemen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "tersebut",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "genoemde",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "seni",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kunst",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "seringkali",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vaak",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "sifat, ber~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "het karakter hebben van",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "temu, menemui",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ontmoeten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "terkenal",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bekend / gekend",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "usaha, ber~",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "inspannen / moeite doen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  }
]
