import type { MorphologyRoot } from '@/lib/capabilities'

// GENERATED by scripts/propose-morphology-roots.ts — affix -i, home L23 (ADR 0020).
// Roots = taught learning_items whose -i form kaikki attests (not a loanword). Re-run additive.

const CAT_0 = "Hoofdfunctie van de werkwoordsvorm met -i"

export const morphologyRoots: MorphologyRoot[] = [
  // ── Hoofdfunctie van de werkwoordsvorm met -i ──
  { root: 'ada', affix: '-i', illustratesCategory: CAT_0 }, // adai
  { root: 'kerja', affix: '-i', illustratesCategory: CAT_0 }, // kerjai
  { root: 'jalan', affix: '-i', illustratesCategory: CAT_0 }, // jalani
  { root: 'lihat', affix: '-i', illustratesCategory: CAT_0 }, // lihati
  { root: 'tahu', affix: '-i', illustratesCategory: CAT_0 }, // tahui
  { root: 'harga', affix: '-i', illustratesCategory: CAT_0 }, // hargai
  { root: 'mau', affix: '-i', illustratesCategory: CAT_0 }, // maui
  { root: 'bangun', affix: '-i', illustratesCategory: CAT_0 }, // banguni
  { root: 'mula', affix: '-i', illustratesCategory: CAT_0 }, // mulai
  { root: 'ingin', affix: '-i', illustratesCategory: CAT_0 }, // ingini
  { root: 'tua', affix: '-i', illustratesCategory: CAT_0 }, // tuai
  { root: 'datang', affix: '-i', illustratesCategory: CAT_0 }, // datangi
  { root: 'nama', affix: '-i', illustratesCategory: CAT_0 }, // namai
  { root: 'punya', affix: '-i', illustratesCategory: CAT_0 }, // punyai
  { root: 'buka', affix: '-i', illustratesCategory: CAT_0 }, // bukai
  { root: 'minta', affix: '-i', illustratesCategory: CAT_0 }, // mintai
  { root: 'sehat', affix: '-i', illustratesCategory: CAT_0 }, // sehati
  { root: 'tulis', affix: '-i', illustratesCategory: CAT_0 }, // tulisi
  { root: 'makan', affix: '-i', illustratesCategory: CAT_0 }, // makani
  { root: 'penuh', affix: '-i', illustratesCategory: CAT_0 }, // penuhi
  { root: 'pikir', affix: '-i', illustratesCategory: CAT_0 }, // pikiri
  { root: 'tangan', affix: '-i', illustratesCategory: CAT_0 }, // tangani
]
