// Generated by generate-staging-files.ts from sections-catalog.json
export const learningItems = [
  {
    "base_text": "Selamat siang, Pak. Berapa prangko untuk kartu pos dan surat ini?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Goedemiddag, meneer. Hoeveel postzegels heb ik nodig voor deze ansichtkaart en brief?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Yang satu ini yang ke negeri Belanda dengan pos udara harganya Rp 550 dan surat kilat khusus yang ke Malang ini Rp 675. Saya kasih prangko yang bagus-bagus untuk surat Ibu ke negeri Belanda. Prangko Indonesia kadang-kadang tidak melekat Bu, sebaiknya kasih lem saja. Ibu sendiri saja kasih lem, ya?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Deze ene, die naar Nederland gaat met luchtpost, kost Rp 550, en deze extra snelle expresse brief naar Malang kost Rp 675. Ik geef u mooie postzegels voor uw brief naar Nederland. Indonesische postzegels plakken soms niet, mevrouw, doet u er liever wat lijm op. Doet u zelf maar lijm erop, ja?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Ya, tidak apa-apa.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Ja, geen probleem.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Jadi, harga keduanya Rp 1225, Bu.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Dus, de prijs van allebei samen is Rp 1225, mevrouw.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Nah, ini uangnya. Ah, Pak, hampir saya lupa. Di mana loket untuk mengirim paket pos laut?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Kijk, hier is het geld. Ach, meneer, ik was het bijna vergeten. Waar is het loket om een zeepostpakket te versturen?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Di situ, Bu, loket nomor enam.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Daar, mevrouw, loket nummer zes.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Terima kasih, Pak.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Dank u wel, meneer.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Halo Dik, bisa saya mengirim paket pos laut ke negeri Belanda di sini?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Hallo, kan ik hier een zeepostpakket naar Nederland versturen?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Bisa, Bu. Formulir ini harus diisi dulu. Formulir ini keterangan untuk pabean. Jangan lupa tanda tangan, ya Bu. Ibu mau mengirim apa?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Dat kan, mevrouw. Dit formulier moet eerst ingevuld worden. Dit formulier is een verklaring voor de douane. Vergeet uw handtekening niet, mevrouw. Wat wilt u versturen?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Buku dan kain saja, Dik.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Alleen boeken en stof.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Oh, tentulah kiriman itu berat sekali. Harus ditimbang dulu. Oh, iya, 4 kilo, Bu.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Oh, die zending is vast heel zwaar. Hij moet eerst gewogen worden. Oh ja, 4 kilo, mevrouw.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Paket ini, kapan sampai di negeri Belanda? Saya rasa makan waktu tiga bulan, bukan?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Dit pakket, wanneer komt het in Nederland aan? Ik denk dat het drie maanden duurt, nietwaar?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Betul Bu, makan waktu kira-kira tiga bulan tetapi mungkin sudah bisa diterima sedikit lebih cepat juga.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Klopt, mevrouw, het duurt ongeveer drie maanden, maar misschien kan het ook al iets sneller ontvangen worden.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Ini harus dibayar di mana? Di loket ini atau bagaimana?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Waar moet dit betaald worden? Bij dit loket of hoe?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Di sini saja, Bu.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Gewoon hier, mevrouw.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Dik, anak saya mengumpulkan prangko. Apakah prangko yang terbaru dapat dibeli di sini? Apa ada loket filateli?",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Mijn kind verzamelt postzegels. Kunnen de nieuwste postzegels hier gekocht worden? Is er een filatelieloket?",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "Ada, tetapi baru buka jam 12.00. Sekarang baru jam 9.00. Kantor pos tutup jam 13.00 jadi kalau Ibu mau ke mari untuk membeli prangko yang terbaru jangan terlambat.",
    "item_type": "dialogue_chunk",
    "context_type": "dialogue",
    "translation_nl": "Ja, maar dat gaat pas om 12.00 uur open. Het is nu pas 9.00 uur. Het postkantoor sluit om 13.00 uur, dus als u hierheen wilt komen om de nieuwste postzegels te kopen, kom dan niet te laat.",
    "translation_en": "",
    "source_page": 3,
    "review_status": "pending_review"
  },
  {
    "base_text": "anjing",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "hond",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bagus-bagus",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "heel mooi",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "baru",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "pas / zojuist",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "buat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "voor / maken",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "preposition"
  },
  {
    "base_text": "cendol (cèndol)",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "drankje met kokossap",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "daging",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vlees",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "dapur",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "keuken",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "dibayar",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "betaald",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "diisi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gevuld",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "Dik (Adik)",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "aanspreektitel voor jongeman / jonge vrouw",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "ditimbang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gewogen",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "ekspor (èkspor)",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "export",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "filateli",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "filatelie",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kartu pos",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ansichtkaart",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kejar",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "najagen / achterna zitten",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "ke mari",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "hierheen",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "keranjang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "mand",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kilat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bliksemschicht",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kilo",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kilo (gewicht) / kilometer",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kualitas",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kwaliteit",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "lekat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kleven / plakken",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "lem (lèm)",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "lijm",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "loket (lokèt)",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "loket",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "makan waktu",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "tijd kosten",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "mengumpulkan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verzamelen",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "pilih",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kiezen",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "pinjam",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "lenen",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "pos laut",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zeepost",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "pos udara",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "luchtpost",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "surat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "brief",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "surat kilat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "expresse brief",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "surat kilat khusus",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "extra snelle expresse brief",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "tanda",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "teken",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "tanda tangan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "handtekening",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "tangkap",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vangen",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "timbang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "wegen",
    "translation_en": "",
    "source_page": 4,
    "review_status": "pending_review",
    "pos": "verb"
  }
]
