// Generated by generate-staging-files.ts from sections-catalog.json
export const learningItems = [
  {
    "base_text": "acara",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "ceremonie",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "akrab",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "goed bevriend / intiem",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "ajak, meng-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "uitnodigen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "asal, ber-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "afkomstig zijn van",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "basah kuyup",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "doorweekt",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "bendera",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vlag",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "bodoh",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dom / dwaas",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "cerita, men-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "iets vertellen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "cup",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "plons",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "dalam",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "diep",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "degung!",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "boem! / bang!",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  },
  {
    "base_text": "dongeng",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "sprookje",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "gigit, meng-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bijten",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "gubernur",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gouverneur",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "guna, meng-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "gebruik / nut / gebruiken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "hujan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "regen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "jatuh, men-kan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "laten vallen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "kail",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "hengel",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kering, mengeringkan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "iets drogen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "kerja, mengerjakan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bewerken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "kolam",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vijver",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kolam renang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "zwembad",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "kura-kura",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "schildpad",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "langit",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "hemel",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "lebat",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "hard (regen)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "mata kail",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dobber",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "mendung",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bewolkt",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "ombak, ber-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "met golven",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "Pancatantra",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "dierfabels",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "pancing, memancing",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vishaak / hengel / hengelen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "pegang, memegang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "vasthouden",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "pekerjaan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "werk",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "perempatan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kruispunt",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "petik, memetik",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "plukken",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "punggung",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "rug",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "sendiri, -an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "alleen / in z'n eentje",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "sesuatu",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "iets / een",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "pronoun"
  },
  {
    "base_text": "si",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "de (persoonlijk lidwoord)",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "particle"
  },
  {
    "base_text": "siul, ber- - -",
    "item_type": "phrase",
    "context_type": "vocabulary_list",
    "translation_nl": "fluitend",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "sobek, menyobek",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verscheuren",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "susah payah",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "met moeite",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "tarik, menarik",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "trekken / aantrekkelijk / interessant",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "teman, ber-",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "bevriend",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "tenang",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "rustig / kalm",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  },
  {
    "base_text": "tepi",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "kant",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "teriak, -an",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "schreeuwen / gillen / schreeuw / gil",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "terjun",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "naar beneden springen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "tiba-tiba",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "plotseling",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adverb"
  },
  {
    "base_text": "tolong, menolong",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "helpen",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "verb"
  },
  {
    "base_text": "umpan",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "aas / lokaas",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "noun"
  },
  {
    "base_text": "wajib",
    "item_type": "word",
    "context_type": "vocabulary_list",
    "translation_nl": "verplicht",
    "translation_en": "",
    "source_page": 2,
    "review_status": "pending_review",
    "pos": "adjective"
  }
]
