import type { MorphologyRoot } from '@/lib/capabilities'

// GENERATED by scripts/propose-morphology-roots.ts — affix -kan, home L21 (ADR 0020).
// Roots = taught learning_items whose -kan form kaikki attests (not a loanword). Re-run additive.
// Entries for other affixes in this lesson are preserved verbatim below.

const CAT_0 = "Zes woordklassen als basiswoord voor -KAN"

export const morphologyRoots: MorphologyRoot[] = [
  // ── Zes woordklassen als basiswoord voor -KAN ──
  { root: 'laku', affix: '-kan', illustratesCategory: CAT_0 }, // lakukan
  { root: 'kata', affix: '-kan', illustratesCategory: CAT_0 }, // katakan
  { root: 'beri', affix: '-kan', illustratesCategory: CAT_0 }, // berikan
  { root: 'henti', affix: '-kan', illustratesCategory: CAT_0 }, // hentikan
  { root: 'ingin', affix: '-kan', illustratesCategory: CAT_0 }, // inginkan
  { root: 'dengar', affix: '-kan', illustratesCategory: CAT_0 }, // dengarkan
  { root: 'dapat', affix: '-kan', illustratesCategory: CAT_0 }, // dapatkan
  { root: 'lepas', affix: '-kan', illustratesCategory: CAT_0 }, // lepaskan
  { root: 'pikir', affix: '-kan', illustratesCategory: CAT_0 }, // pikirkan
  { root: 'bicara', affix: '-kan', illustratesCategory: CAT_0 }, // bicarakan
  { root: 'tinggal', affix: '-kan', illustratesCategory: CAT_0 }, // tinggalkan
  { root: 'lupa', affix: '-kan', illustratesCategory: CAT_0 }, // lupakan
  { root: 'cerita', affix: '-kan', illustratesCategory: CAT_0 }, // ceritakan
  { root: 'keluar', affix: '-kan', illustratesCategory: CAT_0 }, // keluarkan
  { root: 'letak', affix: '-kan', illustratesCategory: CAT_0 }, // letakkan
  { root: 'selamat', affix: '-kan', illustratesCategory: CAT_0 }, // selamatkan
  { root: 'selesai', affix: '-kan', illustratesCategory: CAT_0 }, // selesaikan
  { root: 'mati', affix: '-kan', illustratesCategory: CAT_0 }, // matikan
  { root: 'kerja', affix: '-kan', illustratesCategory: CAT_0 }, // kerjakan
  { root: 'bersih', affix: '-kan', illustratesCategory: CAT_0 }, // bersihkan
  { root: 'ucap', affix: '-kan', illustratesCategory: CAT_0 }, // ucapkan
  { root: 'main', affix: '-kan', illustratesCategory: CAT_0 }, // mainkan
  // ── preserved: other affixes taught in this lesson ──
  { root: 'beli', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // membelikan
  { root: 'naik', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // menaikkan
  { root: 'turun', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // menurunkan
  { root: 'bersih', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // membersihkan
  { root: 'kering', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // mengeringkan
  { root: 'tempat', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // menempatkan
  { root: 'duduk', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // mendudukkan
  { root: 'ambil', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // mengambilkan
  { root: 'jatuh', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // menjatuhkan
  { root: 'guna', affix: 'meN-…-kan', illustratesCategory: 'De werkwoordsvorm met -KAN — hoofdfunctie' }, // menggunakan
  { root: 'beli', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // dibelikan
  { root: 'naik', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // dinaikkan
  { root: 'turun', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // diturunkan
  { root: 'bersih', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // dibersihkan
  { root: 'kering', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // dikeringkan
  { root: 'tempat', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // ditempatkan
  { root: 'duduk', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // didudukkan
  { root: 'ambil', affix: 'di-…-kan', illustratesCategory: 'ME-...-KAN naast DI-...-KAN' }, // diambilkan
]
