// Regenerated by regenerate-all-lesson-page-blocks.ts
export const lessonPageBlocks = [
  {
    "block_key": "lesson-1-hero",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "hero",
    "display_order": 0,
    "payload_json": {
      "title": "Les 1 - Di Pasar (Op de markt)",
      "level": "A1"
    },
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-1-section-2-grammar-intro",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 300,
    "payload_json": {
      "type": "grammar",
      "title": "Grammatica",
      "intro": "In de voorgaande Indonesische zinnen zijn enkele bijzonderheden op te merken, namelijk:"
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-1-section-2-pattern-werkwoord",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 310,
    "payload_json": {
      "type": "grammar",
      "title": "Werkwoord",
      "categories": [
        {
          "title": "Werkwoord",
          "rules": [
            "Zinnen zonder een werkwoord zijn heel gewoon.",
            "Werkwoorden worden niet vervoegd naar enkel- of meervoud.",
            "Werkwoorden worden niet vervoegd naar tegenwoordige of verleden tijd. Tenzij uit de context anders blijkt, vertaalt men het werkwoord in de tegenwoordige tijd.",
            "Werkwoorden worden bij elkaar gezet."
          ],
          "examples": [
            {
              "indonesian": "Itu mahal",
              "dutch": "Dat [is] duur (geen koppelwerkwoord)"
            },
            {
              "indonesian": "Saya beli buah",
              "dutch": "Ik koop een vrucht (geen vervoeging)"
            },
            {
              "indonesian": "Saya mau beli rumah besar",
              "dutch": "Ik wil een groot huis kopen (werkwoorden bij elkaar)"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-1-section-2-pattern-zelfstandig-naamwoord",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 311,
    "payload_json": {
      "type": "grammar",
      "title": "Zelfstandig naamwoord",
      "categories": [
        {
          "title": "Zelfstandig naamwoord",
          "rules": [
            "Zelfstandige naamwoorden hebben geen lidwoord (de, het, een).",
            "Er wordt bij zelfstandige naamwoorden geen onderscheid gemaakt tussen enkelvoud en meervoud.",
            "Herhaling van een zelfstandig naamwoord geeft meervoud of verscheidenheid aan.",
            "Als uit de context blijkt dat er sprake is van meervoud of verscheidenheid, wordt een zelfstandig naamwoord niet verdubbeld (2 huizen = dua rumah en niet dua rumah-rumah)."
          ],
          "examples": [
            {
              "indonesian": "Saya beli rumah",
              "dutch": "Ik koop een/het huis (geen lidwoord)"
            },
            {
              "indonesian": "Dua rumah",
              "dutch": "Twee huizen (geen meervoud bij telwoord)"
            },
            {
              "indonesian": "Buah-buahan",
              "dutch": "Allerlei fruit (reduplicatie = verscheidenheid)"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-1-section-2-pattern-bijvoeglijk-naamwoord",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 312,
    "payload_json": {
      "type": "grammar",
      "title": "Bijvoeglijk naamwoord",
      "categories": [
        {
          "title": "Bijvoeglijk naamwoord",
          "rules": [
            "Het bijvoeglijk naamwoord wordt achter het zelfstandig naamwoord geplaatst."
          ],
          "examples": [
            {
              "indonesian": "Rumah besar",
              "dutch": "Een groot huis (bijv.nw. na znw.)"
            }
          ]
        }
      ]
    },
    "source_progress_event": "pattern_noticing_seen",
    "capability_key_refs": []
  },
  {
    "block_key": "lesson-1-vocabulary-list",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [
      "item-akhir",
      "item-apa",
      "item-bahasa",
      "item-baik",
      "item-bapak",
      "item-beli",
      "item-belum",
      "item-berapa",
      "item-besar",
      "item-bisa",
      "item-boleh",
      "item-buah",
      "item-cukup",
      "item-dan",
      "item-dari",
      "item-datang",
      "item-di",
      "item-harga",
      "item-hotel",
      "item-ibu",
      "item-indonesia",
      "item-itu",
      "item-kabar",
      "item-kalau",
      "item-kasih",
      "item-ke",
      "item-kosong",
      "item-mahal",
      "item-makan",
      "item-mau",
      "item-murah",
      "item-nanas",
      "item-nyonya",
      "item-orang",
      "item-pasar",
      "item-penjual",
      "item-pisang",
      "item-rumah",
      "item-rupiah",
      "item-saya",
      "item-selamat",
      "item-terima",
      "item-tetapi",
      "item-tidak",
      "item-apa-kabar",
      "item-baik-baik-saja",
      "item-berapa-harganya",
      "item-harganya-murah",
      "item-selamat-datang",
      "item-terima-kasih",
      "item-nol",
      "item-satu",
      "item-dua",
      "item-tiga",
      "item-empat",
      "item-lima",
      "item-enam",
      "item-tujuh",
      "item-delapan",
      "item-sembilan",
      "item-sepuluh"
    ],
    "block_kind": "section",
    "display_order": 1000,
    "payload_json": {
      "type": "vocabulary",
      "title": "Woordenschat",
      "items": [
        {
          "indonesian": "akhir",
          "dutch": "einde"
        },
        {
          "indonesian": "apa?",
          "dutch": "wat?"
        },
        {
          "indonesian": "bahasa",
          "dutch": "taal"
        },
        {
          "indonesian": "baik",
          "dutch": "goed"
        },
        {
          "indonesian": "bapak",
          "dutch": "meneer, vader, u"
        },
        {
          "indonesian": "beli",
          "dutch": "kopen"
        },
        {
          "indonesian": "belum",
          "dutch": "nog niet"
        },
        {
          "indonesian": "berapa?",
          "dutch": "hoeveel?"
        },
        {
          "indonesian": "besar",
          "dutch": "groot"
        },
        {
          "indonesian": "bisa",
          "dutch": "kunnen, mogen"
        },
        {
          "indonesian": "boleh",
          "dutch": "mogen, kunnen"
        },
        {
          "indonesian": "buah",
          "dutch": "vrucht"
        },
        {
          "indonesian": "cukup",
          "dutch": "voldoende"
        },
        {
          "indonesian": "dan",
          "dutch": "en"
        },
        {
          "indonesian": "dari",
          "dutch": "uit, van"
        },
        {
          "indonesian": "datang",
          "dutch": "komen"
        },
        {
          "indonesian": "di",
          "dutch": "in, op, te"
        },
        {
          "indonesian": "harga",
          "dutch": "prijs"
        },
        {
          "indonesian": "hotel",
          "dutch": "hotel"
        },
        {
          "indonesian": "ibu",
          "dutch": "mevrouw, moeder, u"
        },
        {
          "indonesian": "Indonesia",
          "dutch": "Indonesië"
        },
        {
          "indonesian": "itu",
          "dutch": "dat, die"
        },
        {
          "indonesian": "kabar",
          "dutch": "bericht"
        },
        {
          "indonesian": "kalau",
          "dutch": "indien, wanneer"
        },
        {
          "indonesian": "kasih",
          "dutch": "gunst, genegenheid"
        },
        {
          "indonesian": "ke",
          "dutch": "naar"
        },
        {
          "indonesian": "kosong",
          "dutch": "leeg"
        },
        {
          "indonesian": "mahal",
          "dutch": "duur"
        },
        {
          "indonesian": "makan",
          "dutch": "eten"
        },
        {
          "indonesian": "mau",
          "dutch": "willen"
        },
        {
          "indonesian": "murah",
          "dutch": "goedkoop"
        },
        {
          "indonesian": "nanas",
          "dutch": "ananas"
        },
        {
          "indonesian": "nyonya",
          "dutch": "mevrouw, u"
        },
        {
          "indonesian": "orang",
          "dutch": "mens"
        },
        {
          "indonesian": "pasar",
          "dutch": "markt"
        },
        {
          "indonesian": "penjual",
          "dutch": "verkoper"
        },
        {
          "indonesian": "pisang",
          "dutch": "banaan"
        },
        {
          "indonesian": "rumah",
          "dutch": "huis"
        },
        {
          "indonesian": "rupiah",
          "dutch": "munteenheid"
        },
        {
          "indonesian": "saya",
          "dutch": "ik, mijn"
        },
        {
          "indonesian": "selamat",
          "dutch": "veilig, welzijn"
        },
        {
          "indonesian": "terima",
          "dutch": "ontvangen"
        },
        {
          "indonesian": "tetapi",
          "dutch": "maar, echter"
        },
        {
          "indonesian": "tidak",
          "dutch": "niet, nee"
        },
        {
          "indonesian": "apa kabar?",
          "dutch": "Hoe gaat het ermee?"
        },
        {
          "indonesian": "baik-baik saja",
          "dutch": "Goed, dank u wel"
        },
        {
          "indonesian": "berapa harganya?",
          "dutch": "Wat kost het?"
        },
        {
          "indonesian": "harganya murah",
          "dutch": "Het is goedkoop; de prijs is laag"
        },
        {
          "indonesian": "selamat datang",
          "dutch": "Welkom"
        },
        {
          "indonesian": "terima kasih",
          "dutch": "Dank u wel"
        },
        {
          "indonesian": "nol",
          "dutch": "0"
        },
        {
          "indonesian": "satu",
          "dutch": "1"
        },
        {
          "indonesian": "dua",
          "dutch": "2"
        },
        {
          "indonesian": "tiga",
          "dutch": "3"
        },
        {
          "indonesian": "empat",
          "dutch": "4"
        },
        {
          "indonesian": "lima",
          "dutch": "5"
        },
        {
          "indonesian": "enam",
          "dutch": "6"
        },
        {
          "indonesian": "tujuh",
          "dutch": "7"
        },
        {
          "indonesian": "delapan",
          "dutch": "8"
        },
        {
          "indonesian": "sembilan",
          "dutch": "9"
        },
        {
          "indonesian": "sepuluh",
          "dutch": "10"
        }
      ]
    },
    "source_progress_event": "section_exposed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/akhir:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/akhir:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/akhir:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/apa:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/apa:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/apa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bahasa:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bahasa:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bahasa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baik:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baik:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baik:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bapak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bapak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bapak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/beli:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/beli:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/beli:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/belum:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/belum:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/belum:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/berapa:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/berapa:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/berapa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/besar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bisa:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/bisa:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bisa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/boleh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/boleh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/boleh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/buah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/buah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/buah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/cukup:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/cukup:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/cukup:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/dan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dari:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/dari:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/datang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/datang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/datang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/di:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harga:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/harga:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harga:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hotel:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/hotel:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hotel:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ibu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ibu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ibu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/indonesia:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/indonesia:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/indonesia:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/itu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/itu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/itu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kabar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kabar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kabar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kalau:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kalau:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kalau:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kasih:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kasih:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kasih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ke:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/ke:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ke:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kosong:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/kosong:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kosong:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mahal:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mahal:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mahal:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/makan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/makan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/makan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mau:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/mau:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mau:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/murah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/murah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/murah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nanas:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nanas:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nanas:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nyonya:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nyonya:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nyonya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/orang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/orang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/orang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pasar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pasar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pasar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/penjual:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/penjual:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/penjual:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pisang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/pisang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pisang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rumah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rumah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rumah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rupiah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/rupiah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rupiah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/saya:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/saya:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/saya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selamat:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/selamat:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selamat:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terima:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tetapi:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tetapi:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tetapi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tidak:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tidak:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tidak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/apa-kabar:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/apa-kabar:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/apa-kabar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baik-baik-saja:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/baik-baik-saja:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baik-baik-saja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/berapa-harganya:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/berapa-harganya:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/berapa-harganya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harganya-murah:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/harganya-murah:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harganya-murah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selamat-datang:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/selamat-datang:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selamat-datang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima-kasih:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/terima-kasih:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima-kasih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nol:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/nol:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nol:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/satu:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/satu:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/satu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/dua:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tiga:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tiga:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tiga:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/empat:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/empat:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/empat:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lima:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/lima:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lima:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enam:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/enam:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enam:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tujuh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/tujuh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tujuh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/delapan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/delapan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/delapan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sembilan:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sembilan:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sembilan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepuluh:form_recall:l1_to_id:text:nl",
      "cap:v1:item:learning_items/sepuluh:meaning_recall:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepuluh:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-1-practice-bridge",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "practice_bridge",
    "display_order": 9000,
    "payload_json": {
      "label": "Oefen deze les"
    },
    "source_progress_event": "intro_completed",
    "capability_key_refs": [
      "cap:v1:item:learning_items/akhir:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/apa-kabar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/apa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bahasa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baik-baik-saja:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/baik:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bapak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/beli:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/belum:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/berapa-harganya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/berapa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/besar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/bisa:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/boleh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/buah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/cukup:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dari:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/datang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/delapan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/di:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/dua:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/empat:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/enam:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harga:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/harganya-murah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/hotel:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ibu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/indonesia:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/itu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kabar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kalau:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kasih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/ke:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/kosong:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/lima:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mahal:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/makan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/mau:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/murah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nanas:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nol:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/nyonya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/orang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pasar:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/penjual:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/pisang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rumah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/rupiah:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/satu:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/saya:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selamat-datang:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/selamat:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sembilan:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/sepuluh:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima-kasih:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/terima:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tetapi:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tidak:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tiga:text_recognition:id_to_l1:text:nl",
      "cap:v1:item:learning_items/tujuh:text_recognition:id_to_l1:text:nl"
    ]
  },
  {
    "block_key": "lesson-1-recap",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "recap",
    "display_order": 9999,
    "payload_json": {
      "title": "Samenvatting"
    },
    "source_progress_event": "lesson_completed",
    "capability_key_refs": []
  }
]
