// Regenerated by capability-stage runner
export const lessonPageBlocks = [
  {
    "block_key": "lesson-1-hero",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "hero",
    "display_order": 0,
    "payload_json": {
      "title": "Les 1 - Di Pasar (Op de markt)",
      "level": "A1"
    }
  },
  {
    "block_key": "lesson-1-section-0",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 100,
    "payload_json": {
      "type": "text",
      "intro": "De Indonesische woorden kan men in het begin het best rustig en zonder klemtoon uitspreken. Van belang bij de uitspraak is een gelijkmatig ritme. Hierbij worden we geholpen door het feit dat de woorden over het algemeen niet lang zijn en een indeling in lettergrepen makkelijk te maken is.",
      "examples": [
        {
          "dutch": "Welkom",
          "phonetic": "Se-la-mat da-tang",
          "indonesian": "Selamat datang"
        },
        {
          "dutch": "Hoe is het ermee?",
          "phonetic": "A-pa ka-bar?",
          "indonesian": "Apa kabar?"
        },
        {
          "dutch": "Goed, dank u wel",
          "phonetic": "Ba-ik, te-ri-ma ka-sih",
          "indonesian": "Baik, terima kasih"
        },
        {
          "dutch": "Gaat u naar Bandung?",
          "phonetic": "Ba-pak ke Ban-dung?",
          "indonesian": "Bapak ke Bandung?"
        }
      ],
      "spelling": [
        {
          "rule": "c = tj",
          "dutch": "voldoende",
          "example": "cukup (tjoekoep)"
        },
        {
          "rule": "j = dj",
          "dutch": "Jakarta",
          "example": "Jakarta (Djakarta)"
        },
        {
          "rule": "u = oe",
          "dutch": "mevrouw, u",
          "example": "Ibu (Iboe)"
        },
        {
          "rule": "y = j",
          "dutch": "Surabaya",
          "example": "Surabaya (Soerabaja)"
        },
        {
          "rule": "ny = nj",
          "dutch": "mevrouw, u",
          "example": "nyonya (njonja)"
        },
        {
          "rule": "kh = ch",
          "dutch": "einde",
          "example": "akhir (achir)"
        }
      ],
      "title": "Uitspraak"
    }
  },
  {
    "block_key": "lesson-1-section-1",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 200,
    "payload_json": {
      "type": "text",
      "intro": "Een paar eenvoudige zinnen om de basisstructuur van het Indonesisch te oefenen:",
      "sentences": [
        {
          "dutch": "Ik ga/ging naar de/een markt",
          "indonesian": "Saya ke pasar"
        },
        {
          "dutch": "Ik koop/kocht een vrucht/vruchten",
          "indonesian": "Saya beli buah"
        },
        {
          "dutch": "Meneer koopt/kocht fruit",
          "indonesian": "Bapak beli buah-buahan"
        },
        {
          "dutch": "Meneer en mevrouw kopen/kochten een ananas",
          "indonesian": "Bapak dan Ibu beli nanas"
        },
        {
          "dutch": "Ik wil/wilde een groot huis kopen",
          "indonesian": "Saya mau beli rumah besar"
        }
      ],
      "title": "Eenvoudige zinnen"
    }
  },
  {
    "block_key": "lesson-1-section-2-grammar-intro",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 300,
    "payload_json": {
      "type": "grammar",
      "title": "Grammatica",
      "intro": "In de voorgaande Indonesische zinnen zijn enkele bijzonderheden op te merken, namelijk:"
    }
  },
  {
    "block_key": "lesson-1-section-2-pattern-werkwoord",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 310,
    "payload_json": {
      "type": "grammar",
      "title": "Werkwoord",
      "categories": [
        {
          "rules": [
            "Zinnen zonder een werkwoord zijn heel gewoon.",
            "Werkwoorden worden niet vervoegd naar enkel- of meervoud.",
            "Werkwoorden worden niet vervoegd naar tegenwoordige of verleden tijd. Tenzij uit de context anders blijkt, vertaalt men het werkwoord in de tegenwoordige tijd.",
            "Werkwoorden worden bij elkaar gezet."
          ],
          "title": "Werkwoord",
          "examples": [
            {
              "dutch": "Dat [is] duur (geen koppelwerkwoord)",
              "indonesian": "Itu mahal"
            },
            {
              "dutch": "Ik koop een vrucht (geen vervoeging)",
              "indonesian": "Saya beli buah"
            },
            {
              "dutch": "Ik wil een groot huis kopen (werkwoorden bij elkaar)",
              "indonesian": "Saya mau beli rumah besar"
            }
          ]
        }
      ]
    }
  },
  {
    "block_key": "lesson-1-section-2-pattern-zelfstandig-naamwoord",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 311,
    "payload_json": {
      "type": "grammar",
      "title": "Zelfstandig naamwoord",
      "categories": [
        {
          "rules": [
            "Zelfstandige naamwoorden hebben geen lidwoord (de, het, een).",
            "Er wordt bij zelfstandige naamwoorden geen onderscheid gemaakt tussen enkelvoud en meervoud.",
            "Herhaling van een zelfstandig naamwoord geeft meervoud of verscheidenheid aan.",
            "Als uit de context blijkt dat er sprake is van meervoud of verscheidenheid, wordt een zelfstandig naamwoord niet verdubbeld (2 huizen = dua rumah en niet dua rumah-rumah)."
          ],
          "title": "Zelfstandig naamwoord",
          "examples": [
            {
              "dutch": "Ik koop een/het huis (geen lidwoord)",
              "indonesian": "Saya beli rumah"
            },
            {
              "dutch": "Twee huizen (geen meervoud bij telwoord)",
              "indonesian": "Dua rumah"
            },
            {
              "dutch": "Allerlei fruit (reduplicatie = verscheidenheid)",
              "indonesian": "Buah-buahan"
            }
          ]
        }
      ]
    }
  },
  {
    "block_key": "lesson-1-section-2-pattern-bijvoeglijk-naamwoord",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 312,
    "payload_json": {
      "type": "grammar",
      "title": "Bijvoeglijk naamwoord",
      "categories": [
        {
          "rules": [
            "Het bijvoeglijk naamwoord wordt achter het zelfstandig naamwoord geplaatst."
          ],
          "title": "Bijvoeglijk naamwoord",
          "examples": [
            {
              "dutch": "Een groot huis (bijv.nw. na znw.)",
              "indonesian": "Rumah besar"
            }
          ]
        }
      ]
    }
  },
  {
    "block_key": "lesson-1-section-3",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 400,
    "payload_json": {
      "type": "dialogue",
      "lines": [
        {
          "text": "Pak, saya mau beli tiga buah pisang. Berapa harganya?",
          "speaker": "Ibu",
          "translation": "Meneer, ik wil graag drie bananen kopen. Hoeveel kosten ze?"
        },
        {
          "text": "Harganya murah Bu, delapan rupiah.",
          "speaker": "Penjual",
          "translation": "Ze zijn goedkoop mevrouw, acht roepiah."
        },
        {
          "text": "Itu mahal ya! Empat rupiah boleh?",
          "speaker": "Ibu",
          "translation": "Dat is duur! Vier roepiah mogelijk?"
        },
        {
          "text": "Belum bisa Bu. Tetapi kalau mau lima buah, bisa sembilan rupiah.",
          "speaker": "Penjual",
          "translation": "Dat kan niet mevrouw. Maar als u vijf stuks wilt, kan het voor negen roepiah."
        }
      ],
      "setup": "Ibu mau ke pasar. Mau beli pisang.",
      "title": "Di Pasar (Op de markt)"
    }
  },
  {
    "block_key": "lesson-1-section-4",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 500,
    "payload_json": {
      "type": "vocabulary",
      "items": [
        {
          "dutch": "einde",
          "indonesian": "akhir"
        },
        {
          "dutch": "wat?",
          "indonesian": "apa?"
        },
        {
          "dutch": "taal",
          "indonesian": "bahasa"
        },
        {
          "dutch": "goed",
          "indonesian": "baik"
        },
        {
          "dutch": "meneer, vader, u",
          "indonesian": "bapak"
        },
        {
          "dutch": "kopen",
          "indonesian": "beli"
        },
        {
          "dutch": "nog niet",
          "indonesian": "belum"
        },
        {
          "dutch": "hoeveel?",
          "indonesian": "berapa?"
        },
        {
          "dutch": "groot",
          "indonesian": "besar"
        },
        {
          "dutch": "kunnen, mogen",
          "indonesian": "bisa"
        },
        {
          "dutch": "mogen, kunnen",
          "indonesian": "boleh"
        },
        {
          "dutch": "vrucht",
          "indonesian": "buah"
        },
        {
          "dutch": "voldoende",
          "indonesian": "cukup"
        },
        {
          "dutch": "en",
          "indonesian": "dan"
        },
        {
          "dutch": "uit, van",
          "indonesian": "dari"
        },
        {
          "dutch": "komen",
          "indonesian": "datang"
        },
        {
          "dutch": "in, op, te",
          "indonesian": "di"
        },
        {
          "dutch": "prijs",
          "indonesian": "harga"
        },
        {
          "dutch": "hotel",
          "indonesian": "hotel"
        },
        {
          "dutch": "mevrouw, moeder, u",
          "indonesian": "ibu"
        },
        {
          "dutch": "indonesië",
          "indonesian": "indonesia"
        },
        {
          "dutch": "dat, die",
          "indonesian": "itu"
        },
        {
          "dutch": "bericht",
          "indonesian": "kabar"
        },
        {
          "dutch": "indien, wanneer",
          "indonesian": "kalau"
        },
        {
          "dutch": "gunst, genegenheid",
          "indonesian": "kasih"
        },
        {
          "dutch": "naar",
          "indonesian": "ke"
        },
        {
          "dutch": "leeg",
          "indonesian": "kosong"
        },
        {
          "dutch": "duur",
          "indonesian": "mahal"
        },
        {
          "dutch": "eten",
          "indonesian": "makan"
        },
        {
          "dutch": "willen",
          "indonesian": "mau"
        },
        {
          "dutch": "goedkoop",
          "indonesian": "murah"
        },
        {
          "dutch": "ananas",
          "indonesian": "nanas"
        },
        {
          "dutch": "mevrouw, u",
          "indonesian": "nyonya"
        },
        {
          "dutch": "mens",
          "indonesian": "orang"
        },
        {
          "dutch": "markt",
          "indonesian": "pasar"
        },
        {
          "dutch": "verkoper",
          "indonesian": "penjual"
        },
        {
          "dutch": "banaan",
          "indonesian": "pisang"
        },
        {
          "dutch": "huis",
          "indonesian": "rumah"
        },
        {
          "dutch": "munteenheid",
          "indonesian": "rupiah (Rp)"
        },
        {
          "dutch": "ik, mijn",
          "indonesian": "saya"
        },
        {
          "dutch": "veilig, welzijn",
          "indonesian": "selamat"
        },
        {
          "dutch": "ontvangen",
          "indonesian": "terima"
        },
        {
          "dutch": "maar, echter",
          "indonesian": "tetapi"
        },
        {
          "dutch": "niet, nee",
          "indonesian": "tidak"
        }
      ],
      "title": "Woordenlijst"
    }
  },
  {
    "block_key": "lesson-1-section-5",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 600,
    "payload_json": {
      "type": "expressions",
      "items": [
        {
          "dutch": "Hoe gaat het ermee?",
          "indonesian": "Apa kabar?"
        },
        {
          "dutch": "Goed, dank u wel",
          "indonesian": "Baik-baik saja"
        },
        {
          "dutch": "Wat kost het?",
          "indonesian": "Berapa harganya?"
        },
        {
          "dutch": "Het is goedkoop; de prijs is laag",
          "indonesian": "Harganya murah"
        },
        {
          "dutch": "Welkom",
          "indonesian": "Selamat datang"
        },
        {
          "dutch": "Dank u wel",
          "indonesian": "Terima kasih"
        }
      ],
      "title": "Uitdrukkingen"
    }
  },
  {
    "block_key": "lesson-1-section-6",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 700,
    "payload_json": {
      "type": "numbers",
      "items": [
        {
          "dutch": "0",
          "indonesian": "nol, kosong"
        },
        {
          "dutch": "1",
          "indonesian": "satu"
        },
        {
          "dutch": "2",
          "indonesian": "dua"
        },
        {
          "dutch": "3",
          "indonesian": "tiga"
        },
        {
          "dutch": "4",
          "indonesian": "empat"
        },
        {
          "dutch": "5",
          "indonesian": "lima"
        },
        {
          "dutch": "6",
          "indonesian": "enam"
        },
        {
          "dutch": "7",
          "indonesian": "tujuh"
        },
        {
          "dutch": "8",
          "indonesian": "delapan"
        },
        {
          "dutch": "9",
          "indonesian": "sembilan"
        },
        {
          "dutch": "10",
          "indonesian": "sepuluh"
        }
      ],
      "title": "Telwoorden"
    }
  },
  {
    "block_key": "lesson-1-section-7",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "section",
    "display_order": 800,
    "payload_json": {
      "type": "pronunciation",
      "letters": [
        {
          "rule": "kort als in kam",
          "letter": "a",
          "examples": [
            "apa",
            "akan",
            "siapa",
            "tetapi"
          ]
        },
        {
          "rule": "als in bang",
          "letter": "b",
          "examples": [
            "bagus",
            "bapak",
            "barang",
            "berapa"
          ]
        },
        {
          "rule": "als in tjalk",
          "letter": "c",
          "examples": [
            "cendol",
            "coklat",
            "kecil",
            "kunci"
          ]
        },
        {
          "rule": "als in denken",
          "letter": "d",
          "examples": [
            "dan",
            "dari",
            "delapan",
            "datang"
          ]
        },
        {
          "rule": "als in bericht",
          "letter": "e",
          "examples": [
            "beli",
            "berat",
            "dekat",
            "enam"
          ]
        },
        {
          "rule": "als in Eva",
          "letter": "é",
          "examples": [
            "sate (saté)",
            "sore (soré)"
          ]
        },
        {
          "rule": "als in bek",
          "letter": "è",
          "examples": [
            "enak (ènak)",
            "teh (tèh)"
          ]
        },
        {
          "rule": "als in falen",
          "letter": "f",
          "examples": [
            "fanatik",
            "famili",
            "fakir",
            "faham"
          ]
        },
        {
          "rule": "als in 'go'",
          "letter": "g",
          "examples": [
            "gampang",
            "gelas",
            "gigi",
            "gengsi"
          ]
        },
        {
          "rule": "als in heet",
          "letter": "h",
          "examples": [
            "hangat",
            "harus",
            "hati",
            "helai"
          ]
        },
        {
          "rule": "als in iep",
          "letter": "i",
          "examples": [
            "ikan",
            "istri",
            "ikut",
            "isi"
          ]
        },
        {
          "rule": "als in 'James'",
          "letter": "j",
          "examples": [
            "jam",
            "jangan",
            "juga",
            "saja"
          ]
        },
        {
          "rule": "als in kalm",
          "letter": "k",
          "examples": [
            "kabar",
            "kamar",
            "kalau",
            "ke"
          ]
        },
        {
          "rule": "als in lang",
          "letter": "l",
          "examples": [
            "lama",
            "lalu",
            "lagi",
            "laku"
          ]
        },
        {
          "rule": "als in mak",
          "letter": "m",
          "examples": [
            "makan",
            "masih",
            "mau",
            "mati"
          ]
        },
        {
          "rule": "als in na",
          "letter": "n",
          "examples": [
            "nasi",
            "nanas",
            "nanti",
            "negeri"
          ]
        },
        {
          "rule": "als in optiek",
          "letter": "o",
          "examples": [
            "opelet",
            "orang",
            "otak",
            "otot"
          ]
        },
        {
          "rule": "als in pa",
          "letter": "p",
          "examples": [
            "pada",
            "pagi",
            "paksa",
            "pasar"
          ]
        },
        {
          "rule": "als in kalm",
          "letter": "q",
          "examples": [
            "qari",
            "qariah",
            "Quran",
            "Alquran"
          ]
        },
        {
          "rule": "als in radio",
          "letter": "r",
          "examples": [
            "raba",
            "rambut",
            "rasa",
            "rumah"
          ]
        },
        {
          "rule": "als in staan",
          "letter": "s",
          "examples": [
            "saya",
            "sayang",
            "sudah",
            "sayur"
          ]
        },
        {
          "rule": "als in trein",
          "letter": "t",
          "examples": [
            "terima",
            "teman",
            "tenun",
            "tiga"
          ]
        },
        {
          "rule": "als in oever",
          "letter": "u",
          "examples": [
            "uang",
            "ubi",
            "utara",
            "tubuh"
          ]
        },
        {
          "rule": "als in varen",
          "letter": "v",
          "examples": [
            "via",
            "visa",
            "vitamin",
            "vokal"
          ]
        },
        {
          "rule": "als in waar",
          "letter": "w",
          "examples": [
            "wah!",
            "walau",
            "warta",
            "wisma"
          ]
        },
        {
          "rule": "als in ex",
          "letter": "x",
          "examples": [
            "xerox",
            "sinar-X",
            "xilofon",
            "xenograf"
          ]
        },
        {
          "rule": "als in ja",
          "letter": "y",
          "examples": [
            "yakin",
            "yang",
            "ayam",
            "ya"
          ]
        },
        {
          "rule": "als in zang",
          "letter": "z",
          "examples": [
            "zaman",
            "ziarah",
            "zina",
            "zakat"
          ]
        }
      ],
      "title": "Uitspraakoefening"
    }
  },
  {
    "block_key": "lesson-1-cloze",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1",
      "learning_items/berapa harganya?",
      "learning_items/cukup",
      "learning_items/di",
      "learning_items/hotel",
      "learning_items/pasar",
      "learning_items/sepuluh",
      "learning_items/bisa",
      "learning_items/dan",
      "learning_items/tujuh",
      "learning_items/kasih",
      "learning_items/selamat",
      "learning_items/nol",
      "learning_items/delapan",
      "learning_items/mau",
      "learning_items/saya",
      "learning_items/tidak",
      "learning_items/sembilan",
      "learning_items/berapa?",
      "learning_items/penjual"
    ],
    "content_unit_slugs": [
      "item-berapa-harganya",
      "item-cukup",
      "item-di",
      "item-hotel",
      "item-pasar",
      "item-sepuluh",
      "item-bisa",
      "item-dan",
      "item-tujuh",
      "item-kasih",
      "item-selamat",
      "item-nol",
      "item-delapan",
      "item-mau",
      "item-saya",
      "item-tidak",
      "item-sembilan",
      "item-berapa",
      "item-penjual"
    ],
    "block_kind": "section",
    "display_order": 1000,
    "payload_json": {
      "type": "reading",
      "title": "cloze",
      "items": [
        {
          "indonesian": "Berapa harganya?",
          "dutch": "Wat kost het?"
        },
        {
          "indonesian": "cukup",
          "dutch": "voldoende"
        },
        {
          "indonesian": "di",
          "dutch": "in, op, te"
        },
        {
          "indonesian": "hotel",
          "dutch": "hotel"
        },
        {
          "indonesian": "pasar",
          "dutch": "markt"
        },
        {
          "indonesian": "sepuluh",
          "dutch": "10"
        },
        {
          "indonesian": "bisa",
          "dutch": "kunnen, mogen"
        },
        {
          "indonesian": "dan",
          "dutch": "en"
        },
        {
          "indonesian": "tujuh",
          "dutch": "7"
        },
        {
          "indonesian": "kasih",
          "dutch": "gunst, genegenheid"
        },
        {
          "indonesian": "selamat",
          "dutch": "veilig, welzijn"
        },
        {
          "indonesian": "nol",
          "dutch": "0"
        },
        {
          "indonesian": "delapan",
          "dutch": "8"
        },
        {
          "indonesian": "mau",
          "dutch": "willen"
        },
        {
          "indonesian": "saya",
          "dutch": "ik, mijn"
        },
        {
          "indonesian": "tidak",
          "dutch": "niet, nee"
        },
        {
          "indonesian": "sembilan",
          "dutch": "9"
        },
        {
          "indonesian": "berapa?",
          "dutch": "hoeveel?"
        },
        {
          "indonesian": "penjual",
          "dutch": "verkoper"
        }
      ]
    }
  },
  {
    "block_key": "lesson-1-lesson-snippet",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1",
      "learning_items/apa?",
      "learning_items/harganya murah",
      "learning_items/terima kasih",
      "learning_items/indonesia",
      "learning_items/apa kabar?",
      "learning_items/selamat datang",
      "learning_items/baik-baik saja"
    ],
    "content_unit_slugs": [
      "item-apa",
      "item-harganya-murah",
      "item-terima-kasih",
      "item-indonesia",
      "item-apa-kabar",
      "item-selamat-datang",
      "item-baik-baik-saja"
    ],
    "block_kind": "section",
    "display_order": 1010,
    "payload_json": {
      "type": "reading",
      "title": "lesson snippet",
      "items": [
        {
          "indonesian": "apa?",
          "dutch": "wat?"
        },
        {
          "indonesian": "harganya murah",
          "dutch": "Het is goedkoop; de prijs is laag"
        },
        {
          "indonesian": "terima kasih",
          "dutch": "Dank u wel"
        },
        {
          "indonesian": "Indonesia",
          "dutch": "Indonesië"
        },
        {
          "indonesian": "Apa kabar?",
          "dutch": "Hoe gaat het?"
        },
        {
          "indonesian": "selamat datang",
          "dutch": "Welkom"
        },
        {
          "indonesian": "baik-baik saja",
          "dutch": "Goed, dank u wel"
        }
      ]
    }
  },
  {
    "block_key": "lesson-1-vocabulary-list",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1",
      "learning_items/akhir",
      "learning_items/bapak",
      "learning_items/besar",
      "learning_items/boleh",
      "learning_items/dari",
      "learning_items/murah",
      "learning_items/pisang",
      "learning_items/tetapi",
      "learning_items/dua",
      "learning_items/enam",
      "learning_items/beli",
      "learning_items/ibu",
      "learning_items/ke",
      "learning_items/mahal",
      "learning_items/nanas",
      "learning_items/rumah",
      "learning_items/terima",
      "learning_items/satu",
      "learning_items/tiga",
      "learning_items/bahasa",
      "learning_items/belum",
      "learning_items/kabar",
      "learning_items/makan",
      "learning_items/nyonya",
      "learning_items/rupiah",
      "learning_items/empat",
      "learning_items/baik",
      "learning_items/buah",
      "learning_items/datang",
      "learning_items/harga",
      "learning_items/itu",
      "learning_items/kalau",
      "learning_items/lima",
      "learning_items/orang",
      "learning_items/kosong"
    ],
    "content_unit_slugs": [
      "item-akhir",
      "item-bapak",
      "item-besar",
      "item-boleh",
      "item-dari",
      "item-murah",
      "item-pisang",
      "item-tetapi",
      "item-dua",
      "item-enam",
      "item-beli",
      "item-ibu",
      "item-ke",
      "item-mahal",
      "item-nanas",
      "item-rumah",
      "item-terima",
      "item-satu",
      "item-tiga",
      "item-bahasa",
      "item-belum",
      "item-kabar",
      "item-makan",
      "item-nyonya",
      "item-rupiah",
      "item-empat",
      "item-baik",
      "item-buah",
      "item-datang",
      "item-harga",
      "item-itu",
      "item-kalau",
      "item-lima",
      "item-orang",
      "item-kosong"
    ],
    "block_kind": "section",
    "display_order": 1020,
    "payload_json": {
      "type": "vocabulary",
      "title": "Woordenschat",
      "items": [
        {
          "indonesian": "akhir",
          "dutch": "einde"
        },
        {
          "indonesian": "bapak",
          "dutch": "meneer, vader, u"
        },
        {
          "indonesian": "besar",
          "dutch": "groot"
        },
        {
          "indonesian": "boleh",
          "dutch": "mogen, kunnen"
        },
        {
          "indonesian": "dari",
          "dutch": "uit, van"
        },
        {
          "indonesian": "murah",
          "dutch": "goedkoop"
        },
        {
          "indonesian": "pisang",
          "dutch": "banaan"
        },
        {
          "indonesian": "tetapi",
          "dutch": "maar, echter"
        },
        {
          "indonesian": "dua",
          "dutch": "2"
        },
        {
          "indonesian": "enam",
          "dutch": "6"
        },
        {
          "indonesian": "beli",
          "dutch": "kopen"
        },
        {
          "indonesian": "ibu",
          "dutch": "mevrouw, moeder, u"
        },
        {
          "indonesian": "ke",
          "dutch": "naar"
        },
        {
          "indonesian": "mahal",
          "dutch": "duur"
        },
        {
          "indonesian": "nanas",
          "dutch": "ananas"
        },
        {
          "indonesian": "rumah",
          "dutch": "huis"
        },
        {
          "indonesian": "terima",
          "dutch": "ontvangen"
        },
        {
          "indonesian": "satu",
          "dutch": "1"
        },
        {
          "indonesian": "tiga",
          "dutch": "3"
        },
        {
          "indonesian": "bahasa",
          "dutch": "taal"
        },
        {
          "indonesian": "belum",
          "dutch": "nog niet"
        },
        {
          "indonesian": "kabar",
          "dutch": "bericht"
        },
        {
          "indonesian": "makan",
          "dutch": "eten"
        },
        {
          "indonesian": "nyonya",
          "dutch": "mevrouw, u"
        },
        {
          "indonesian": "rupiah",
          "dutch": "munteenheid"
        },
        {
          "indonesian": "empat",
          "dutch": "4"
        },
        {
          "indonesian": "baik",
          "dutch": "goed"
        },
        {
          "indonesian": "buah",
          "dutch": "vrucht"
        },
        {
          "indonesian": "datang",
          "dutch": "komen"
        },
        {
          "indonesian": "harga",
          "dutch": "prijs"
        },
        {
          "indonesian": "itu",
          "dutch": "dat, die"
        },
        {
          "indonesian": "kalau",
          "dutch": "indien, wanneer"
        },
        {
          "indonesian": "lima",
          "dutch": "5"
        },
        {
          "indonesian": "orang",
          "dutch": "mens"
        },
        {
          "indonesian": "kosong",
          "dutch": "leeg"
        }
      ]
    }
  },
  {
    "block_key": "lesson-1-practice-bridge",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "practice_bridge",
    "display_order": 9000,
    "payload_json": {
      "label": "Oefen deze les"
    }
  },
  {
    "block_key": "lesson-1-recap",
    "source_ref": "lesson-1",
    "source_refs": [
      "lesson-1"
    ],
    "content_unit_slugs": [],
    "block_kind": "recap",
    "display_order": 9999,
    "payload_json": {
      "title": "Samenvatting"
    }
  }
]
