// Auto-generated by review UI
// Do not edit manually

import type { GeneratedExerciseCandidate } from '@/types/contentGeneration'

export const candidates: GeneratedExerciseCandidate[] = [
  {
    "exercise_type": "contrast_pair",
    "page_reference": 1,
    "grammar_pattern_id": "subject_verb_agreement",
    "source_text": "Saya bekerja sebagai guru.",
    "prompt_text_nl": "Welke zin is correct voor \"Ik werk als leraar\"?",
    "prompt_text_en": "Which sentence is correct for \"I work as a teacher\"?",
    "answer_key": [
      "0"
    ],
    "correctOptionId": "0",
    "options": [
      "Saya bekerja sebagai guru.",
      "Saya bekerja seperti guru."
    ],
    "explanation_nl": "Gebruik \"sebagai\" (als) voor beroepen, niet \"seperti\" (zoals)",
    "explanation_en": "Use \"sebagai\" (as) for professions, not \"seperti\" (like)",
    "review_status": "approved",
    "created_at": "2026-04-03T21:54:37.958Z",
    "reviewer_notes": ""
  },
  {
    "exercise_type": "sentence_transformation",
    "page_reference": 2,
    "grammar_pattern_id": "question_words",
    "source_text": "Anda berasal dari mana?",
    "transformationInstruction_nl": "Zet om naar bewering: \"Ik kom uit Jakarta\"",
    "transformationInstruction_en": "Transform to statement: \"I come from Jakarta\"",
    "expected_answer_nl": "Saya berasal dari Jakarta",
    "expected_answer_en": "I come from Jakarta",
    "answer_key": [
      "Saya berasal dari Jakarta",
      "Saya berasal dari Jakarta."
    ],
    "explanation_nl": "Verander de vraag in een bewering door \"Anda\" (u) te vervangen door \"Saya\" (ik) en een locatie op te geven.",
    "explanation_en": "Change the question to a statement by replacing \"Anda\" (you) with \"Saya\" (I) and providing a location.",
    "review_status": "approved",
    "created_at": "2026-04-03T21:54:37.958Z",
    "reviewer_notes": ""
  },
  {
    "exercise_type": "constrained_translation",
    "page_reference": 2,
    "grammar_pattern_id": "noun_phrases",
    "source_text": "I am an engineer.",
    "prompt_text_nl": "Vertaal: \"Ik ben een ingenieur.\" (Gebruik: seorang, insinyur)",
    "prompt_text_en": "Translate: \"I am an engineer.\" (Use: seorang, insinyur)",
    "answer_key": [
      "Saya seorang insinyur",
      "Saya adalah seorang insinyur"
    ],
    "requiredTargetPattern": "seorang insinyur",
    "explanation_nl": "In het Indonesisch gebruiken beroepen \"seorang\" (een/a) + zelfstandig naamwoord. Je kunt \"adalah\" weglaten.",
    "explanation_en": "In Indonesian, professions use \"seorang\" (an/a) + noun. You can omit \"adalah\".",
    "review_status": "approved",
    "created_at": "2026-04-03T21:54:37.958Z",
    "reviewer_notes": ""
  },
  {
    "exercise_type": "speaking",
    "page_reference": 1,
    "source_text": "Memperkenalkan diri",
    "prompt_text_nl": "Stel jezelf voor: naam, waar je vandaan komt en je beroep",
    "prompt_text_en": "Introduce yourself: name, where you are from, and your occupation",
    "answer_key": [
      "Open-ended"
    ],
    "explanation_nl": "Gebruik de patronen: \"Nama saya...\", \"Saya dari...\", \"Saya seorang...\"",
    "explanation_en": "Use the patterns: \"Nama saya...\", \"Saya dari...\", \"Saya seorang...\"",
    "targetPatternOrScenario": "Self-introduction with name, origin, and profession",
    "review_status": "approved",
    "created_at": "2026-04-03T21:54:37.958Z",
    "reviewer_notes": ""
  }
]
